const FAMOUS_POLES = [
  // STYCZEŃ
  {d:15, m:1,  year:1869, name:'Stanisław Wyspiański',    desc:'Malarz, poeta i dramaturg — jeden z najważniejszych twórców Młodej Polski. Zaprojektował słynne witraże w Kościele Franciszkanów w Krakowie. Jego dramat „Wesele" uznawany jest za arcydzieło polskiej literatury.'},
  {d:23, m:1,  year:1983, name:'Justyna Kowalczyk',       desc:'Najlepsza polska biegaczka narciarska w historii. Czterokrotna zdobywczyni Pucharu Świata i wielokrotna mistrzyni olimpijska oraz światowa. Znana z niezwykłej determinacji — wygrała olimpijskie złoto mimo złamanej stopy.'},
  {d:25, m:1,  year:1913, name:'Witold Lutosławski',      desc:'Jeden z najwybitniejszych kompozytorów XX wieku. Jego muzyka łączy tradycję z nowoczesnymi technikami kompozytorskimi. Laureat m.in. Nagrody Gramercy i Polar Music Prize — muzycznego Nobla.'},
  {d:28, m:1,  year:1611, name:'Jan Heweliusz',           desc:'Gdański astronom, jeden z najważniejszych obserwatorów nieba XVII wieku. Skatalogował ponad 1500 gwiazd i opisał wiele zjawisk księżycowych. Na Księżycu znajduje się krater jego imienia.'},
  {d:28, m:1,  year:1887, name:'Artur Rubinstein',        desc:'Jeden z największych pianistów w historii muzyki. Zasłynął wykonaniami Chopina, które rozsławiły polską muzykę na całym świecie. Koncertował przez ponad 80 lat, zachwycając publiczność na wszystkich kontynentach.'},
  {d:29, m:1,  year:1962, name:'Olga Tokarczuk',          desc:'Pisarka, laureatka Literackiej Nagrody Nobla przyznanej w 2018 roku. Jej powieść „Bieguni" zdobyła Nagrodę Bookera. Jest jedną z najchętniej tłumaczonych polskich autorek na świecie.'},

  // LUTY
  {d:4,  m:2,  year:1746, name:'Tadeusz Kościuszko',      desc:'Generał i bohater narodowy, symbol walki o wolność. Dowodził insurekcją kościuszkowską i walczył w wojnie o niepodległość Stanów Zjednoczonych u boku Waszyngtona. Jest jedynym człowiekiem w historii odznaczonym zarówno polskim Orderem Virtuti Militari, jak i najwyższym odznaczeniem wojskowym USA.'},
  {d:17, m:2,  year:1984, name:'Marcin Gortat',           desc:'Pierwszy Polak, który stał się gwiazdą NBA. Przez ponad dekadę grał w najlepszej lidze koszykówki świata, m.in. w Phoenix Suns i Washington Wizards. Wielokrotny reprezentant Polski, symbol polskiego basketu.'},
  {d:19, m:2,  year:1473, name:'Mikołaj Kopernik',        desc:'Astronom, który zmienił nasze rozumienie Wszechświata — udowodnił, że Ziemia krąży wokół Słońca, a nie odwrotnie. Jego dzieło „O obrotach sfer niebieskich" wywołało rewolucję naukową. Urodził się w Toruniu, pracował w Fromborku.'},
  {d:24, m:2,  year:1929, name:'Zdzisław Beksiński',      desc:'Malarz i fotografik tworzący mroczne, surrealistyczne wizje. Jego obrazy przedstawiają apokaliptyczne pejzaże i postacie, które fascynują i niepokoją jednocześnie. Uznawany za jednego z najbardziej oryginalnych polskich artystów XX wieku.'},
  {d:27, m:2,  year:1945, name:'Daniel Olbrychski',       desc:'Legendarny polski aktor filmowy i teatralny. Wieloletni współpracownik Andrzeja Wajdy, zagrał w ponad 200 filmach. Jeden z symboli polskiego kina, znany też z ról w produkcjach europejskich.'},

  // MARZEC
  {d:1,  m:3,  year:1810, name:'Fryderyk Chopin',         desc:'Najsłynniejszy polski kompozytor i pianista w historii. Jego mazurki, polonezy i nokturny należą do kanonu muzyki klasycznej na całym świecie. Spędził większość życia w Paryżu, lecz zawsze pozostał duchem Polakiem.'},
  {d:3,  m:3,  year:1956, name:'Zbigniew Boniek',         desc:'Jeden z najlepszych polskich piłkarzy wszech czasów, w latach 80. gwiazda Juventusu Turyn. Pomocnik zwany „Zibim" zachwyciło świat podczas Mundialu 1982, gdy Polska zajęła trzecie miejsce. Wieloletni prezes Polskiego Związku Piłki Nożnej.'},
  {d:3,  m:3,  year:1977, name:'Adam Małysz',             desc:'Legenda polskich skoków narciarskich. Czterokrotny zdobywca Pucharu Świata i czterokrotny mistrz świata. Przez lata był idolem milionów Polaków, a „Małyszmania" stała się prawdziwym fenomenem społecznym.'},
  {d:4,  m:3,  year:1745, name:'Kazimierz Pułaski',       desc:'Generał brygady, jeden z ojców założycieli amerykańskiej kawalerii. Walczył za wolność Polski, a potem za niepodległość Stanów Zjednoczonych u boku George'a Waszyngtona. Jest jednym z nielicznych cudzoziemców uhonorowanych obywatelstwem USA.'},
  {d:4,  m:3,  year:1932, name:'Ryszard Kapuściński',     desc:'Dziennikarz i pisarz reportażysta, jeden z najwybitniejszych na świecie. Relacjonował kilkanaście wojen i rewolucji w Afryce, Azji i Ameryce Łacińskiej. Jego książki, m.in. „Cesarz" i „Szachinszach", tłumaczone są na dziesiątki języków.'},
  {d:6,  m:3,  year:1926, name:'Andrzej Wajda',           desc:'Najważniejszy polski reżyser filmowy, laureat Oscara za całokształt twórczości. Twórca „Kanału", „Popiołu i diamentu", „Człowieka z żelaza" — filmów, które stały się ikonami kina. Jego filmy opowiadają historię Polski z odwagą i głębią.'},
  {d:13, m:3,  year:1869, name:'Józef Mehoffer',          desc:'Malarz i witrażysta, jeden z czołowych przedstawicieli Młodej Polski. Jego witraże zdobią wiele świątyń w Polsce i za granicą, w tym katedrę we Fryburgu Szwajcarskim. Tworzył też plakaty, grafiki i projekty użytkowe.'},
  {d:30, m:3,  year:1892, name:'Stefan Banach',           desc:'Jeden z największych matematyków XX wieku, twórca nowoczesnej analizy funkcjonalnej. Jego nazwiskiem nazwano przestrzenie Banacha — fundamentalne pojęcie współczesnej matematyki. Działał w słynnej Lwowskiej Szkole Matematycznej.'},

  // KWIECIEŃ
  {d:6,  m:4,  year:1915, name:'Tadeusz Kantor',          desc:'Reżyser, malarz i twórca teatralny, jedna z najważniejszych postaci awangardowego teatru XX wieku. Założył Teatr Cricot 2 w Krakowie, gdzie tworzył spektakle łączące teatr z plastyką. Jego „Umarła klasa" obiegła sceny całego świata.'},
  {d:8,  m:4,  year:1950, name:'Grzegorz Lato',           desc:'Legendarny polski piłkarz, król strzelców Mistrzostw Świata 1974 w Niemczech. Zdobył 7 bramek na mundialu, a Polska zajęła trzecie miejsce. Uznawany za jednego z najlepszych skrzydłowych w historii piłki nożnej.'},

  // MAJ
  {d:5,  m:5,  year:1819, name:'Stanisław Moniuszko',     desc:'Kompozytor, ojciec polskiej opery narodowej. Stworzył opery „Halka" i „Straszny dwór", które do dziś są grywane na scenach całego świata. Jego muzyka czerpie z polskiej tradycji ludowej i szlacheckiej.'},
  {d:5,  m:5,  year:1846, name:'Henryk Sienkiewicz',      desc:'Pisarz, laureat Literackiej Nagrody Nobla przyznanej w 1905 roku. Autor „Trylogii" (Ogniem i mieczem, Potop, Pan Wołodyjowski) oraz „Quo vadis" — powieści przetłumaczonej na 50 języków. Pisał, by „pokrzepić serca" Polaków w czasie zaborów.'},
  {d:16, m:5,  year:1898, name:'Tamara Łempicka',         desc:'Malarka, ikona stylu art déco. Jej portrety kobiet emanują zmysłowością i elegancją epoki lat 20. i 30. XX wieku. Obrazy Łempickiej osiągają na aukcjach ceny wielu milionów dolarów.'},
  {d:18, m:5,  year:1920, name:'Karol Wojtyła',           desc:'Papież Jan Paweł II — jedna z najważniejszych postaci XX wieku. Pierwszy w historii papież z Polski, pełnił urząd przez 27 lat. Jego rola w upadku komunizmu w Europie Środkowej jest powszechnie uznawana.'},
  {d:20, m:5,  year:1955, name:'Zbigniew Preisner',       desc:'Kompozytor muzyki filmowej, znany przede wszystkim ze współpracy z Krzysztofem Kieślowskim. Stworzył muzykę do Trylogii Trzech Kolorów i „Podwójnego życia Weroniki". Jego kompozycje brzmią w salach koncertowych na całym świecie.'},
  {d:23, m:5,  year:1842, name:'Maria Konopnicka',        desc:'Poetka i pisarka, autorka słów do pieśni „Rota" — polskiego hymnu patriotycznego. Jej twórczość dla dzieci, w tym „O krasnoludkach i o sierotce Marysi", należy do klasyki polskiej literatury. Angażowała się w walkę o prawa kobiet i chłopów.'},
  {d:24, m:5,  year:1946, name:'Irena Szewińska',         desc:'Najwybitniejsza polska lekkoatletka w historii. Trzykrotna mistrzyni olimpijska, siedmiokrotna medalistka olimpijska w sumie. Zdobyła medale na czterech kolejnych igrzyskach i ustanowiła siedem rekordów świata.'},
  {d:25, m:5,  year:1987, name:'Kamil Stoch',             desc:'Trzykrotny mistrz olimpijski w skokach narciarskich. Zdobył złoto na igrzyskach w Soczi (2014) i podwójne złoto w Pjongczangu (2018). Jeden z najbardziej utytułowanych skoczków w historii polskiego sportu.'},
  {d:31, m:5,  year:2001, name:'Iga Świątek',             desc:'Tenisistka, wieloletnia liderka światowego rankingu WTA. Pierwsza Polka i pierwsza zawodniczka z Europy Środkowej, która wygrała wielkoszlemowy French Open. Swoje sukcesy zawdzięcza wyjątkowej konsekwencji i mentalnej sile.'},

  // CZERWIEC
  {d:6,  m:6,  year:1841, name:'Eliza Orzeszkowa',        desc:'Pisarka epoki pozytywizmu, autorka „Nad Niemnem" — jednej z najważniejszych powieści polskich. Była trzykrotnie nominowana do Nagrody Nobla. Aktywnie walczyła o prawa kobiet i równouprawnienie społeczne.'},
  {d:20, m:6,  year:1793, name:'Aleksander Fredro',       desc:'Najwybitniejszy polski komediopisarz, twórca „Zemsty" i „Ślubów panieńskich". Jego komedie wyróżnia doskonały humor, celne obserwacje i żywy język. Grywane są na polskich scenach nieprzerwanie od ponad 150 lat.'},
  {d:21, m:6,  year:1948, name:'Andrzej Sapkowski',       desc:'Pisarz fantasy, twórca sagi o Wiedźminie — jednego z największych sukcesów eksportowych polskiej kultury. Jego książki przetłumaczono na ponad 20 języków, a na ich podstawie powstały gry wideo i serial Netflixa oglądany przez miliony na całym świecie.'},
  {d:24, m:6,  year:1838, name:'Jan Matejko',             desc:'Najwybitniejszy polski malarz historyczny. Jego wielkie obrazy, jak „Bitwa pod Grunwaldem" czy „Hołd pruski", utrwaliły w świadomości Polaków ważne momenty historii. Przez całe życie tworzył w Krakowie, odmawiając atrakcyjnych propozycji zagranicznych.'},
  {d:26, m:6,  year:1930, name:'Sławomir Mrożek',         desc:'Dramaturg i satyryk, jeden z najważniejszych polskich twórców teatralnych XX wieku. Jego absurdalne sztuki, jak „Tango", były grywane na scenach całego świata. Tworzył też rysunki satyryczne i opowiadania.'},
  {d:27, m:6,  year:1941, name:'Krzysztof Kieślowski',    desc:'Jeden z najwybitniejszych reżyserów filmowych świata. Twórca Dekalogu, „Podwójnego życia Weroniki" i Trylogii Trzech Kolorów (Niebieski, Biały, Czerwony). Jego filmy wyróżnia głęboka refleksja nad ludzkim losem i mistrzowska narracja.'},
  {d:30, m:6,  year:1911, name:'Czesław Miłosz',          desc:'Poeta i pisarz, laureat Literackiej Nagrody Nobla z 1980 roku. Jeden z najważniejszych intelektualistów XX wieku, autor „Zniewolony umysł" — kluczowej analizy totalitaryzmu. Przez dziesięciolecia żył na emigracji, lecz zawsze pozostał wierny polskiej kulturze.'},

  // LIPIEC
  {d:2,  m:7,  year:1923, name:'Wisława Szymborska',      desc:'Poetka, laureatka Literackiej Nagrody Nobla z 1996 roku. Jej wiersze łączą filozoficzną głębię z niepowtarzalnym humorem i dystansem do świata. Nazywana „Mozartem poezji", była jedną z najbardziej lubianych polskich poetek.'},
  {d:6,  m:7,  year:1923, name:'Wojciech Jaruzelski',     desc:'Generał i polityk, ostatni komunistyczny przywódca Polski i jej pierwszy prezydent wybrany w wolnych wyborach. Wprowadził stan wojenny w 1981 roku, co do dziś budzi kontrowersje. Odegrał kluczową rolę w negocjacjach Okrągłego Stołu.'},
  {d:10, m:7,  year:1835, name:'Henryk Wieniawski',       desc:'Skrzypek wirtuoz i kompozytor, jeden z najwybitniejszych muzyków XIX wieku. Jako dziesięciolatek zadebiutował w Paryżu, zachwycając Europę. Jego Koncerty skrzypcowe i Polonez A-dur należą do żelaznego repertuaru skrzypków na całym świecie.'},
  {d:12, m:7,  year:1892, name:'Bruno Schulz',            desc:'Pisarz i grafik, twórca prozy poetyckiej o wyjątkowej urodzie. Jego „Sklepy cynamonowe" i „Sanatorium Pod Klepsydrą" to arcydzieła literatury europejskiej. Zginął tragicznie podczas II wojny światowej w Drohobyczu.'},
  {d:15, m:7,  year:1854, name:'Jacek Malczewski',        desc:'Najwybitniejszy malarz polskiego symbolizmu. Tworzył obrazy pełne fantazji, mitologii i odniesień do polskiej historii. Jego postać Tanatosa i Erosa stały się ikonami polskiej sztuki przełomu XIX i XX wieku.'},

  // SIERPIEŃ
  {d:16, m:8,  year:1905, name:'Marian Rejewski',         desc:'Matematyk i kryptolog, który jako pierwszy na świecie złamał szyfr Enigmy używanej przez Niemców. Jego odkrycie miało ogromny wpływ na przebieg II wojny światowej. Pracował w tajemnicy, a jego zasługi przez lata były nieznane opinii publicznej.'},
  {d:17, m:8,  year:1629, name:'Jan III Sobieski',        desc:'Król Polski i hetman wielki koronny, jeden z najwybitniejszych polskich władców. Zasłynął zwycięstwem w Bitwie pod Wiedniem (1683), które ocaliło Europę przed ekspansją osmańską. Był też mecenasem sztuki i architektury.'},
  {d:18, m:8,  year:1933, name:'Roman Polański',          desc:'Reżyser filmowy o światowej sławie, twórca „Pianisty", „Chinatown" i „Dziecka Rosemary". Laureat Oscara, Złotej Palmy i Złotego Niedźwiedzia. Jako dziecko przeżył getto krakowskie, co wywarło głęboki wpływ na jego twórczość.'},
  {d:20, m:8,  year:1847, name:'Bolesław Prus',           desc:'Pisarz i publicysta, jeden z najważniejszych twórców polskiego pozytywizmu. Autor „Lalki" — powieści uznawanej za najwybitniejsze dzieło polskiej literatury realistycznej. Jego kroniki i felietony były lustrem ówczesnego społeczeństwa.'},
  {d:21, m:8,  year:1988, name:'Robert Lewandowski',      desc:'Najlepszy polski piłkarz w historii, jeden z najskuteczniejszych napastników na świecie. Dwukrotny zdobywca Złotego Buta, MVP Bundesligi przez wiele sezonów i strzelec rekordowej liczby goli dla Bayernu Monachium. Gra w FC Barcelona.'},

  // WRZESIEŃ
  {d:4,  m:9,  year:1809, name:'Juliusz Słowacki',        desc:'Jeden z trzech polskich wieszczów romantycznych, obok Mickiewicza i Krasińskiego. Autor dramatów „Kordian" i „Balladyna" oraz poematu „Beniowski". Spędził większość życia na emigracji, tęskniąc za Polską i pisząc o niej z niezwykłą siłą.'},
  {d:12, m:9,  year:1921, name:'Stanisław Lem',           desc:'Pisarz science fiction, jeden z najlepiej sprzedających się autorów w historii tego gatunku. Jego powieści, jak „Solaris" czy „Cyberiada", tłumaczone są na ponad 40 języków. Łączył filozofię, satyrę i wizjonerstwo technologiczne.'},
  {d:24, m:9,  year:1821, name:'Cyprian Kamil Norwid',    desc:'Poeta, rzeźbiarz i dramaturg, jeden z czterech wieszczów polskiego romantyzmu. Za życia niedoceniany, po śmierci uznany za geniusza. Jego twórczość, pełna głębokich przemyśleń o czasie, pięknie i pracy, jest ciągle aktualna.'},
  {d:29, m:9,  year:1943, name:'Lech Wałęsa',            desc:'Elektryk ze Stoczni Gdańskiej, przywódca ruchu Solidarność i prezydent Polski. Laureat Pokojowej Nagrody Nobla z 1983 roku. Jego rola w pokojowym obaleniu komunizmu w Polsce i Europie jest powszechnie uznawana za historyczną.'},

  // PAŹDZIERNIK
  {d:9,  m:10, year:1921, name:'Tadeusz Różewicz',        desc:'Poeta i dramaturg, jeden z najważniejszych polskich twórców po II wojnie światowej. Jego twórczość wyrasta z traumy wojennej i poszukiwania sensu w zrujnowanym świecie. Był też wybitnym dramaturgiem, twórcą „Kartoteki".'},
  {d:23, m:10, year:1927, name:'Leszek Kołakowski',       desc:'Filozof i historyk idei, jeden z najważniejszych intelektualistów XX wieku. Jego monumentalne „Główne nurty marksizmu" to fundamentalna analiza tej ideologii. Przez lata wykładał w Oxfordzie i na University of Chicago.'},
  {d:23, m:10, year:1947, name:'Kazimierz Deyna',         desc:'Jeden z najlepszych polskich piłkarzy wszech czasów, pomocnik o niezwykłej technice i wizji gry. Kapitan reprezentacji, która zdobyła złoty medal olimpijski w 1972 roku i srebrny medal mundialu w 1974. Grał też w Manchesterze City.'},

  // LISTOPAD
  {d:7,  m:11, year:1867, name:'Maria Skłodowska-Curie',  desc:'Fizyczka i chemiczka, jedyna osoba w historii, która zdobyła Nagrody Nobla w dwóch różnych dziedzinach nauki. Odkryła polon i rad, pionierka badań nad promieniotwórczością. Pierwsza kobieta, która otrzymała Nagrodę Nobla.'},
  {d:14, m:11, year:1878, name:'Leopold Staff',           desc:'Poeta i tłumacz, jeden z najważniejszych twórców polskiego modernizmu. Jego liryka wyróżnia się klasycznym pięknem, spokojem i filozoficzną głębią. Tłumaczył na polski dzieła Nietzschego, Goethego i poetów starożytnych.'},
  {d:18, m:11, year:1860, name:'Ignacy Jan Paderewski',   desc:'Wybitny pianista i kompozytor, a zarazem polityk i mąż stanu. Był pierwszym premierem odrodzonej Polski w 1919 roku. Swoją muzyczną sławą służył sprawie polskiej niepodległości przed rządami całego świata.'},
  {d:23, m:11, year:1933, name:'Krzysztof Penderecki',    desc:'Jeden z najwybitniejszych kompozytorów XX wieku. Jego „Tren ofiarom Hiroszimy" i „Pasja według św. Łukasza" należą do arcydzieł muzyki współczesnej. Wielokrotnie nagradzany, w tym Grammy, Polar Music Prize i nagrodami UNESCO.'},

  // GRUDZIEŃ
  {d:5,  m:12, year:1867, name:'Józef Piłsudski',         desc:'Marszałek Polski i główny architekt odrodzonej niepodległości w 1918 roku. Dowódca wojsk polskich w zwycięskiej wojnie z bolszewicką Rosją (1920). Jedna z najważniejszych postaci w historii Polski, wciąż budząca ogromne emocje.'},
  {d:13, m:12, year:1983, name:'Otylia Jędrzejczak',      desc:'Pływaczka, mistrzyni olimpijska z Aten 2004 na 200 m stylem motylkowym. Pierwsza polska złota medalistka olimpijska w pływaniu. Wielokrotna medalistka mistrzostw świata i Europy.'},
  {d:24, m:12, year:1798, name:'Adam Mickiewicz',         desc:'Największy polski poeta romantyczny, wieszcz narodowy. Autor „Pana Tadeusza" — polskiej epopei narodowej i „Dziadów" — dramatu o wyjątkowej sile. Jego poezja towarzyszyła Polakom przez wszystkie lata zaborów i wojen.'},
];
