const HISTORY_DATA = {
  '25-6': [
    {y:1373, t:'Joanna II, królowa Neapolu (zm. 1435)'},
    {y:1642, t:'Maximilian Ernst von Dohna, władca sycowskiego wolnego państwa stanowego (ur. ?)'},
    {y:1856, t:'Stanisław Nowosielecki, polski polityk (zm. 1918)'},
    {y:1921, t:'Zdzisław Trześniowski, polski major piechoty (ur. 1868)'},
    {y:1988, t:'Hillel Slovak, amerykański gitarzysta, członek zespołu Red Hot Chili Peppers (ur. 1962)'},
  ],
  '26-6': [
    {y:1407, t:'Ulrich von Jungingen został wielkim mistrzem zakonu krzyżackiego.'},
    {y:1673, t:'Wojna Francji z koalicją hiszpańsko-austriacko-lotaryńską: wojska francuskie pod wodzą Sébastiena Vaubana zdobyły po oblężeniu Maastricht.'},
    {y:1857, t:'Królowa Wiktoria wręczyła pierwsze Krzyże Wiktorii 66 weteranom wojny krymskiej.'},
    {y:1926, t:'Dominik Staszewski, polski prawnik, historyk regionalny (ur. 1861)'},
    {y:1987, t:'50 osób zginęło w katastrofie samolotu Hawker Siddeley 748 na Filipinach.'},
  ],
  '27-6': [
    {y:1350, t:'Manuel II Paleolog, cesarz bizantyński (zm. 1425)'},
    {y:1667, t:'Jacques-Ignace Parrocel, francuski malarz (zm. 1722)'},
    {y:1859, t:'Leon Inchausti, hiszpański augustianin rekolekta, męczennik, błogosławiony (zm. 1936)'},
    {y:1927, t:'Jan Gołdyn, polski kapitan piechoty, działacz niepodległościowy (ur. 1898)'},
    {y:1985, t:'Zamknięto Route 66 łączącą Chicago z Los Angeles.'},
  ],
  '28-6': [
    {y:1385, t:'Andronik IV Paleolog, cesarz bizantyński (ur. 1348)'},
    {y:1681, t:'Marie Angélique de Scorailles, francuska arystokratka (ur. 1661)'},
    {y:1853, t:'Adolf von Strümpell, niemiecki internista (zm. 1925)'},
    {y:1926, t:'William Lyon Mackenzie King ustąpił z funkcji premiera Kanady.'},
    {y:1993, t:'Premiera filmu Pograbek w reżyserii Jana Jakuba Kolskiego.'},
  ],
  '29-6': [
    {y:1397, t:'Jan II Aragoński, król Aragonii i Nawarry (zm. 1479)'},
    {y:1672, t:'Francesco Maria Mancini, włoski kardynał (ur. 1606)'},
    {y:1855, t:'Delphine de Girardin, francuska pisarka, dziennikarka (ur. 1804)'},
    {y:1925, t:'Christian Michelsen, norweski potentat handlowy, polityk, premier Norwegii (ur. 1857)'},
    {y:1986, t:'W rozegranym na Estadio Azteca w mieście Meksyk finale XIII Mistrzostw Świata w Piłce Nożnej Argentyna pokonała RFN 3:2.'},
  ],
  '30-6': [
    {y:1422, t:'Zwycięstwo wojsk księstwa Mediolanu nad siłami kantonów szwajcarskich w bitwie pod Arbedo.'},
    {y:1728, t:'Otto Friedrich von der Groeben, pruski wojskowy, podróżnik, naukowiec (ur. 1657)'},
    {y:1846, t:'John Russell został premierem Wielkiej Brytanii.'},
    {y:1922, t:'Sekretarz stanu USA Charles Evans Hughes i dominikański ambasador Francisco J. Peynado podpisali porozumienie o zakończeniu trwającej od 1916 roku amerykańskiej okupacji wojskowej Dominikany.'},
    {y:1992, t:'Fidel Ramos został prezydentem Filipin.'},
  ],
  '1-7': [
    {y:1408, t:'Jean Gilles, francuski kardynał (ur. ?)'},
    {y:1650, t:'Maria Anna Teresa Wazówna, polska królewna (zm. 1651)'},
    {y:1862, t:'Ernest Greene, irlandzki rugbysta (zm. 1937)'},
    {y:1920, t:'Powołano Radę Obrony Państwa.'},
    {y:1990, t:'Iwan Sierow, radziecki generał, szef KGB i GRU (ur. 1905)'},
  ],
  '2-7': [
    {y:1309, t:'Po półrocznym pobycie w więzieniu biskup krakowski Jan Muskata podpisał ugodę kapitulacyjną z Władysławem Łokietkiem i udał się na wygnanie.'},
    {y:1647, t:'Daniel Finch, angielski arystokrata, polityk (zm. 1730)'},
    {y:1861, t:'Wojna secesyjna: zwycięstwo Unionistów w bitwie nad Hoke’s Run.'},
    {y:1924, t:'Mitchell Red Cloud, amerykański kapral pochodzenia indiańskiego (zm. 1950)'},
    {y:1986, t:'Szymon Hens, szwajcarsko-amerykański psychiatra pochodzenia polsko-żydowskiego (ur. 1891)'},
  ],
  '3-7': [
    {y:1423, t:'Ludwik XI, król Francji (zm. 1483)'},
    {y:1705, t:'Leopold von Auersperg, austriacki hrabia, dyplomata (ur. 1662)'},
    {y:1870, t:'Richard Bedford Bennett, kanadyjski polityk, premier Kanady (zm. 1947)'},
    {y:1924, t:'W Warszawie rozpoczął się I Narodowy Zlot Harcerzy.'},
    {y:1980, t:'Przygotowująca się do Igrzysk Olimpijskich w Moskwie 20-letnia radziecka gimnastyczka Jelena Muchina uległa wypadkowi w trakcie treningu, uszkadzając odcinek szyjny rdzenia kręgowego, co doprowadziło do paraliżu czterokończynowego.'},
  ],
  '4-7': [
    {y:1308, t:'Eberhard II, hrabia Mark (ur. przed 1265)'},
    {y:1706, t:'Giambettino Cignaroli, włoski malarz (zm. 1770)'},
    {y:1851, t:'Joseph Partsch, niemiecki geograf (zm. 1925)'},
    {y:1925, t:'44 osoby zginęły w wyniku zawalenia budynku klubu nocnego Pickwick Club w Bostonie.'},
    {y:1987, t:'Bengt Strömgren, duński astronom, astrofizyk (ur. 1908)'},
  ],
};
