  [1,1,'Świętej Bożej Rodzicielki Maryi','','Inne'],
  [1,1,'Światowy Dzień Pokoju','','Historia'],
  [1,1,'Nowy Rok','','Inne'],
  [6,1,'Dzień Filatelisty','','Inne'],
  [6,1,'Trzech Króli (Objawienie Pańskie)','','Inne'],
  [9,1,'Dzień Ligi Ochrony Przyrody','','Zwierzęta'],
  [11,1,'Chrzest Pański','','Inne'],
  [12,1,'Dzień Sprzątania Biurka','','Inne'],
  [15,1,'Dzień Wikipedii','','Inne'],
  [17,1,'Dzień Dialogu z Judaizmem (obchodzony przez Kościół Katolicki)','','Historia'],
  [18,1,'Dzień Kubusia Puchatka','','Inne'],
  [21,1,'Dzień Babci','','Rodzina'],
  [22,1,'Dzień Dziadka','','Rodzina'],
  [24,1,'Światowy Dzień Środków Masowego Przekazu','','Ekologia'],
  [25,1,'Dzień Sekretarki i Asystentki','','Zawody'],
  [26,1,'Światowy Dzień Celnictwa','','Inne'],
  [26,1,'Dzień Transplantacji','','Inne'],
  [26,1,'Dzień Dialogu z Islamem','','Historia'],
  [27,1,'Międzynarodowy Dzień Pamięci o Ofiarach Holokaustu','','Historia'],
  [28,1,'Międzynarodowy Dzień Mobilizacji przeciwko Wojnie Nuklearnej','','Inne'],
  [2,2,'Światowy Dzień Obszarów Wodno-Błotnych','','Inne'],
  [2,2,'Dzień Handlowca','','Inne'],
  [2,2,'Światowy Dzień Życia Konsekrowanego','','Inne'],
  [2,2,'Ofiarowanie Pańskie (Matki Boskiej Gromnicznej)','','Rodzina'],
  [3,2,'Dzień Bezpiecznego Internetu','','Nauka'],
  [4,2,'Międzynarodowy Dzień Walki z Rakiem','','Zdrowie'],
  [9,2,'Międzynarodowy Dzień Pizzy','','Inne'],
  [11,2,'Światowy Dzień Chorych','','Zdrowie'],
  [11,2,'Europejski Dzień Numeru 112','','Inne'],
  [12,2,'Tłusty czwartek','','Inne'],
  [12,2,'Dzień Darwina','','Jedzenie'],
  [14,2,'Ostatnia sobota karnawału','','Inne'],
  [14,2,'Dzień Zakochanych (Walentynki)','','Rodzina'],
  [15,2,'Światowy Dzień Młodzieży Prawosławnej','','Inne'],
  [17,2,'Ostatki','','Inne'],
  [17,2,'Dzień Kota','','Zwierzęta'],
  [17,2,'Dzień Służby Cywilnej','','Inne'],
  [18,2,'Popielec','','Inne'],
  [19,2,'Dzień Nauki Polskiej','','Nauka'],
  [20,2,'Światowy Dzień Sprawiedliwości Społecznej','','Inne'],
  [20,2,'Międzynarodowy Dzień Palących Fajkę','','Inne'],
  [21,2,'Międzynarodowy Dzień Języka Ojczystego','','Inne'],
  [22,2,'I Niedziela Wielkiego Postu','','Inne'],
  [22,2,'Dzień Ofiar Przestępstw','','Historia'],
  [23,2,'Ogólnopolski Dzień Walki z Depresją','','Zdrowie'],
  [28,2,'Dzień Chorób Rzadkich','','Inne'],
  [1,3,'Narodowy Dzień Pamięci Żołnierzy Wyklętych','','Zawody'],
  [1,3,'II Niedziela Wielkiego Postu','','Inne'],
  [1,3,'Międzynarodowy Dzień Walki Przeciw Zbrojeniom Atomowym','','Inne'],
  [1,3,'Międzynarodowy Dzień Obrony Cywilnej','','Inne'],
  [1,3,'Światowy Dzień Świadomości Autoagresji','','Inne'],
  [3,3,'Międzynarodowy Dzień Pisarzy','','Inne'],
  [4,3,'Światowy Dzień Inżyniera','','Inne'],
  [5,3,'Dzień Teściowej','','Inne'],
  [5,3,'Dzień Geodety Europejskiego i Geoinformacji','','Inne'],
  [6,3,'Europejski Dzień Logopedy','','Inne'],
  [8,3,'III Niedziela Wielkiego Postu','','Inne'],
  [8,3,'Międzynarodowy Dzień Kobiet','','Rodzina'],
  [9,3,'Dzień Statystyki Polskiej','','Inne'],
  [10,3,'Dzień Mężczyzn','','Rodzina'],
  [12,3,'Światowy Dzień Drzemki w Pracy','','Zawody'],
  [14,3,'Światowy Dzień Liczby Pi','','Inne'],
  [15,3,'IV Niedziela Wielkiego Postu','','Inne'],
  [15,3,'Międzynarodowy Dzień (Praw) Konsumenta','','Inne'],
  [15,3,'Dzień Piekarzy i Cukierników','','Jedzenie'],
  [19,3,'Uroczystość św. Józefa','','Inne'],
  [19,3,'Dzień Jedności Kaszubów','','Inne'],
  [20,3,'Międzynarodowy Dzień Szczęścia','','Inne'],
  [20,3,'Początek astronomicznej wiosny','','Nauka'],
  [20,3,'Światowy Dzień Zdrowia Jamy Ustnej','','Zdrowie'],
  [21,3,'Międzynarodowy Dzień Walki z Dyskryminacją Rasową','','Zdrowie'],
  [21,3,'Międzynarodowy Dzień Poezji','','Inne'],
  [21,3,'Dzień Wagarowicza','','Inne'],
  [21,3,'Międzynarodowy Dzień Lasów','','Inne'],
  [22,3,'V Niedziela Wielkiego Postu','','Inne'],
  [22,3,'Światowy Dzień Wody','','Inne'],
  [22,3,'Dzień Ochrony Bałtyku','','Inne'],
  [23,3,'Międzynarodowy Dzień Meteorologii','','Inne'],
  [23,3,'Dzień Przyjaźni Polsko-Węgierskiej','','Rodzina'],
  [24,3,'Światowy Dzień Walki z Gruźlicą','','Zdrowie'],
  [24,3,'Narodowy Dzień Życia','','Inne'],
  [25,3,'Zwiastowanie Pańskie (Dzień Świętości Życia)','','Inne'],
  [27,3,'Międzynarodowy Dzień Teatru','','Kultura'],
  [29,3,'Niedziela Palmowa','','Inne'],
  [29,3,'Zmiana czasu z zimowego na letni','','Inne'],
  [30,3,'Wielki Poniedziałek','','Inne'],
  [30,3,'Ogólnopolski Dzień Trzeźwości','','Inne'],
  [31,3,'Wielki Wtorek','','Inne'],
  [1,4,'Wielka Środa','','Inne'],
  [1,4,'Prima Aprilis','','Inne'],
  [1,4,'Międzynarodowy Dzień Ptaków','','Zwierzęta'],
  [2,4,'Wielki Czwartek','','Inne'],
  [2,4,'Międzynarodowy Dzień Książki Dla Dzieci','','Kultura'],
  [2,4,'Światowy Dzień Autyzmu','','Inne'],
  [3,4,'Wielki Piątek','','Inne'],
  [4,4,'Wielka Sobota','','Inne'],
  [4,4,'Święto Wojskowej Służby Zdrowia','','Zdrowie'],
  [4,4,'Międzynarodowy Dzień Wiedzy o Minach i Działań Zapobiegających Minom','','Inne'],
  [5,4,'Dzień Leśnika i Drzewiarza (Polska)','','Inne'],
  [5,4,'Wielkanoc','','Inne'],
  [6,4,'Międzynarodowy Dzień Sportu na rzecz Rozwoju i Pokoju','','Sport'],
  [6,4,'Poniedziałek Wielkanocny','','Inne'],
  [7,4,'Wtorek Wielkanocny','','Inne'],
  [7,4,'Światowy Dzień Zdrowia','','Zdrowie'],
  [8,4,'Środa Oktawy Wielkanocnej','','Inne'],
  [8,4,'Międzynarodowy Dzień Romów','','Inne'],
  [9,4,'Czwartek Oktawy Wielkanocnej','','Inne'],
  [10,4,'Piątek Oktawy Wielkanocnej','','Inne'],
  [11,4,'Dzień Radia','','Inne'],
  [11,4,'Sobota Oktawy Wielkanocnej','','Inne'],
  [11,4,'Ogólnopolski Dzień Walki z Bezrobociem','','Zdrowie'],
  [11,4,'Światowy Dzień Osób z Chorobą Parkinsona','','Inne'],
  [12,4,'Święto Bożego Miłosierdzia','','Inne'],
  [12,4,'II Niedziela Wielkanocna','','Inne'],
  [12,4,'Międzynarodowy Dzień Lotnictwa i Kosmonautyki','','Inne'],
  [13,4,'Dzień Pamięci Ofiar Zbrodni Katyńskiej','','Historia'],
  [14,4,'Święto Chrztu Polski','','Inne'],
  [14,4,'Dzień Ludzi Bezdomnych (Polska)','','Inne'],
  [15,4,'Międzynarodowy Dzień Kombatanta','','Inne'],
  [16,4,'Dzień Sapera','','Inne'],
  [17,4,'Światowy Dzień Chorych na Hemofilię','','Zdrowie'],
  [18,4,'Międzynarodowy Dzień Ochrony Zabytków','','Inne'],
  [18,4,'Dzień Pacjenta w Śpiączce','','Inne'],
  [19,4,'III Niedziela Wielkanocna','','Inne'],
  [19,4,'Dzień Pamięci Ofiar Holocaustu i Powstania w Getcie Warszawskim','','Historia'],
  [20,4,'Międzynarodowy Dzień Wolnej Prasy','','Inne'],
  [22,4,'Międzynarodowy Dzień Ziemi','','Ekologia'],
  [23,4,'Światowy Dzień Książki i Praw Autorskich','','Kultura'],
  [24,4,'Międzynarodowy Dzień Solidarności Młodzieży','','Historia'],
  [24,4,'Dzień Zwierząt Laboratoryjnych','','Zwierzęta'],
  [25,4,'Światowy Dzień Malarii','','Kultura'],
  [25,4,'Międzynarodowy Dzień Sekretarki','','Zawody'],
  [25,4,'Międzynarodowy Dzień Świadomości Zagrożenia Hałasem','','Inne'],
  [25,4,'Międzynarodowy Dzień DNA','','Inne'],
  [26,4,'Dzień Drogowca i Transportowca (Polska)','','Inne'],
  [26,4,'Niedziela Dobrego Pasterza','','Inne'],
  [26,4,'Dzień Psa Poszukiwawczo-Ratowniczego','','Zdrowie'],
  [26,4,'Światowy Dzień Własności Intelektualnej','','Inne'],
  [27,4,'Światowy Dzień Grafika','','Inne'],
  [28,4,'Światowy Dzień Bezpieczeństwa i Ochrony Zdrowia w Pracy','','Zdrowie'],
  [29,4,'Międzynarodowy Dzień Tańca','','Kultura'],
  [29,4,'Dzień Męczeństwa Duchowieństwa Polskiego','','Inne'],
  [30,4,'Międzynarodowy Dzień Jazzu','','Inne'],
  [1,5,'Międzynarodowe Święto Pracy','','Zawody'],
  [2,5,'Dzień Flagi Rzeczypospolitej Polskiej','','Inne'],
  [2,5,'Dzień Polonii i Polaków za Granicą','','Inne'],
  [3,5,'Światowy Dzień Wolności Prasy','','Historia'],
  [3,5,'Międzynarodowy Dzień Astmy i Alergii','','Inne'],
  [3,5,'NMP Królowej Polski','','Inne'],
  [3,5,'Święto Konstytucji 3 Maja','','Inne'],
  [3,5,'V Niedziela Wielkanocna','','Inne'],
  [4,5,'Dzień Strażaka','','Zawody'],
  [4,5,'Dzień Hutnika','','Inne'],
  [5,5,'Praw Człowieka i Integracji Europejskiej','','Historia'],
  [5,5,'Dzień Tolerancji','','Historia'],
  [5,5,'Dzień Godności Osoby z Niepełnosprawnością Intelektualną','','Inne'],
  [6,5,'Europejski Dzień Bezpieczeństwa Ruchu Drogowego','','Inne'],
  [8,5,'Światowy Dzień Czerwonego Krzyża i Czerwonego Półksiężyca','','Inne'],
  [8,5,'Dzień Bibliotekarza i Bibliotek','','Inne'],
  [8,5,'Dzień Zwycięstwa','','Inne'],
  [9,5,'Dzień Europy (Święto Unii Europejskiej)','','Inne'],
  [11,5,'Dzień bez Śmiecenia','','Inne'],
  [12,5,'Zimnych ogrodników (Pankracego)','','Inne'],
  [12,5,'Międzynarodowy Dzień Pielęgniarek i Położnych','','Zdrowie'],
  [12,5,'Światowy Dzień Ptaków Wędrownych','','Zwierzęta'],
  [13,5,'Zimnych ogrodników (Serwacego)','','Inne'],
  [13,5,'Matki Bożej Fatimskiej','','Rodzina'],
  [14,5,'Zimnych ogrodników (Bonifacego)','','Inne'],
  [14,5,'Dzień Farmaceuty','','Inne'],
  [15,5,'Międzynarodowy Dzień Rodziny','','Rodzina'],
  [15,5,'Święto Polskiej Muzyki i Plastyki','','Kultura'],
  [15,5,'Dzień Polskiej Niezapominajki','','Inne'],
  [16,5,'Święto Straży Granicznej','','Inne'],
  [17,5,'Wniebowstąpienie','','Inne'],
  [17,5,'Światowy Dzień Telekomunikacji','','Inne'],
  [17,5,'Międzynarodowy Dzień Pamięci ofiar AIDS','','Zdrowie'],
  [18,5,'Międzynarodowy Dzień Muzeów','','Inne'],
  [18,5,'Dzień Mostowca','','Inne'],
  [19,5,'Dzień Dobrych Uczynków','','Inne'],
  [20,5,'Międzynarodowy Dzień Pszczół','','Inne'],
  [21,5,'Światowy Dzień Kosmosu','','Nauka'],
  [21,5,'Światowy Dzień Różnorodności Kulturowej','','Inne'],
  [21,5,'Dzień Kadeta','','Inne'],
  [22,5,'Dzień Praw Zwierząt','','Zwierzęta'],
  [22,5,'Międzynarodowy Dzień Różnorodności Biologicznej','','Inne'],
  [23,5,'Światowy Dzień Żółwia','','Zwierzęta'],
  [23,5,'Dzień Wymiaru Sprawiedliwości','','Inne'],
  [24,5,'Święto Wojsk Specjalnych','','Inne'],
  [24,5,'Europejski Dzień Parków Narodowych','','Inne'],
  [24,5,'Zesłanie Ducha Świętego (Zielone Świątki)','','Inne'],
  [25,5,'Najświętszej Maryi Panny','','Inne'],
  [25,5,'Matki Kościoła','','Rodzina'],
  [25,5,'Dzień Piwowara','','Inne'],
  [25,5,'Międzynarodowy Dzień Dzieci Zaginionych','','Inne'],
  [26,5,'Dzień Matki','','Rodzina'],
  [27,5,'Dzień Samorządu Terytorialnego','','Inne'],
  [28,5,'Najwyższego i Wiecznego Kapłana','','Inne'],
  [28,5,'Święto Jezusa Chrystusa','','Inne'],
  [29,5,'Międzynarodowy Dzień Uczestników Misji Pokojowych ONZ','','Inne'],
  [29,5,'Dzień Weterana Działań poza Granicami Państwa','','Inne'],
  [29,5,'Dzień Działacza Kultury i Drukarza','','Inne'],
  [30,5,'Dzień Rodzicielstwa Zastępczego','','Inne'],
  [31,5,'Uroczystość Trójcy Przenajświętszej','','Inne'],
  [31,5,'Światowy Dzień Bez Papierosa','','Inne'],
  [31,5,'Dzień Bociana Białego','','Inne'],
  [1,6,'Międzynarodowy Dzień Dziecka','','Rodzina'],
  [1,6,'Światowy Dzień Mleka','','Jedzenie'],
  [1,6,'Dzień bez Alkoholu','','Inne'],
  [3,6,'Światowy Dzień Roweru','','Sport'],
  [4,6,'Dzień Wolności i Praw Obywatelskich','','Historia'],
  [4,6,'Międzynarodowy Dzień Dzieci Będących Ofiarami Agresji','','Historia'],
  [4,6,'Boże Ciało','','Inne'],
  [5,6,'Światowy Dzień Ochrony Środowiska Naturalnego','','Inne'],
  [8,6,'Światowy Dzień Oceanów','','Ekologia'],
  [9,6,'Międzynarodowy Dzień Archiwów','','Inne'],
  [12,6,'Światowy Dzień Sprzeciwu wobec Pracy Dzieci','','Zawody'],
  [12,6,'Święto BOR','','Inne'],
  [13,6,'Święto Niepokalanego Serca Maryi','','Zdrowie'],
  [13,6,'Święto Żandarmerii Wojskowej','','Inne'],
  [14,6,'Światowy Dzień Krwiodawcy','','Inne'],
  [14,6,'Narodowy Dzień Pamięci Ofiar Niemieckich Nazistowskich Obozów Koncentracyjnych i Obozów Zagłady','','Historia'],
  [15,6,'Światowy Dzień Wiatru','','Inne'],
  [15,6,'Ogólnopolski Dzień Dogoterapii','','Inne'],
  [16,6,'Międzynarodowy Dzień Pomocy Dzieciom Afrykańskim','','Inne'],
  [17,6,'Światowy Dzień Walki z Pustynnieniem i Suszą','','Zdrowie'],
  [17,6,'Święto Wojsk Pancernych i Zmechanizowanych – Dzień Czołgisty','','Inne'],
  [20,6,'Światowy Dzień Uchodźcy','','Inne'],
  [20,6,'Narodowy Dzień Powstań Śląskich','','Inne'],
  [21,6,'Święto Muzyki','','Kultura'],
  [21,6,'Dzień Przedsiębiorcy','','Inne'],
  [21,6,'Pierwszy Dzień Lata - najdłuższy dzień roku','','Inne'],
  [21,6,'Międzynarodowy Dzień Jogi','','Inne'],
  [23,6,'Dzień Ojca','','Rodzina'],
  [23,6,'Noc Świętojańska','','Inne'],
  [23,6,'Dzień Służby Publicznej','','Inne'],
  [24,6,'Światowy Dzień Chorych na Osteoporozę','','Zdrowie'],
  [25,6,'Dzień Marynarza','','Inne'],
  [26,6,'Międzynarodowy Dzień Walki z Narkomanią','','Zdrowie'],
  [26,6,'Międzynarodowy Dzień Pomocy Ofiarom Tortur','','Historia'],
  [26,6,'Koniec zajęć w szkołach','','Inne'],
  [27,6,'Światowy Dzień Rybołówstwa','','Inne'],
  [28,6,'Narodowy Dzień Pamięci Poznańskiego Czerwca 1956','','Historia'],
  [29,6,'Dzień Ratownika WOPR','','Zdrowie'],
  [29,6,'Uroczystość św. Piotra i Pawła','','Inne'],
  [29,6,'Święto Służby Więziennej','','Inne'],
  [30,6,'Dzień Walki z Przewlekłą Niewydolnością Żylną','','Zdrowie'],
  [30,6,'Międzynarodowy Dzień Planetoid','','Inne'],
  [1,7,'Światowy Dzień Architektury','','Inne'],
  [1,7,'Dzień Spółdzielczości','','Inne'],
  [2,7,'Dzień Dziennikarza','','Inne'],
  [6,7,'Międzynarodowy Dzień Pocałunku','','Inne'],
  [11,7,'Światowy Dzień Ludności','','Inne'],
  [11,7,'Narodowy Dzień Pamięci Ofiar Ludobójstwa dokonanego przez ukraińskich nacjonalistów na obywatelach II Rzeczypospolitej Polskiej','','Historia'],
  [12,7,'Dzień Walki i Męczeństwa Wsi Polskiej','','Inne'],
  [18,7,'Międzynarodowy Dzień Nelsona Mandeli','','Inne'],
  [20,7,'Międzynarodowy Dzień Szachów','','Inne'],
  [24,7,'Święto Policji','','Inne'],
  [25,7,'Dzień Bezpiecznego Kierowcy','','Inne'],
  [30,7,'Międzynarodowy Dzień Przyjaźni','','Rodzina'],
  [31,7,'Dzień Skarbowości','','Inne'],
  [1,8,'Narodowy Dzień Pamięci Powstania Warszawskiego','','Historia'],
  [2,8,'Światowy Dzień Pamięci o Zagładzie Romów','','Historia'],
  [6,8,'Przemienienie Pańskie','','Inne'],
  [10,8,'Dzień Przewodników i Ratowników Górskich','','Zdrowie'],
  [12,8,'Międzynarodowy Dzień Młodzieży','','Inne'],
  [13,8,'Międzynarodowy Dzień Osób Leworęcznych','','Inne'],
  [14,8,'Dzień Energetyka','','Inne'],
  [15,8,'Wniebowzięcie Najświętszej Maryi Panny','','Inne'],
  [15,8,'Święto Wojska Polskiego','','Inne'],
  [19,8,'Światowy Dzień Pomocy Humanitarnej','','Inne'],
  [22,8,'Najświętsza Maryja Panna Królowa','','Inne'],
  [22,8,'Międzynarodowy Dzień Upamiętniający Ofiary Aktów Przemocy ze względu na Religię lub Wyznanie','','Historia'],
  [23,8,'Święto Lotnictwa','','Inne'],
  [23,8,'Europejski Dzień Pamięci Ofiar Stalinizmu i Nazizmu','','Historia'],
  [23,8,'Międzynarodowy Dzień Pamięci o Handlu Niewolnikami i jego Zniesieniu','','Historia'],
  [25,8,'Dzień polskiej żywności','','Inne'],
  [26,8,'Międzynarodowy Dzień Psa','','Inne'],
  [28,8,'Święto Lotnictwa Polskiego','','Inne'],
  [29,8,'Międzynarodowy Dzień Sprzeciwu wobec Prób Jądrowych','','Inne'],
  [29,8,'Dzień Straży Gminnej','','Inne'],
  [30,8,'Międzynarodowy Dzień Pamięci Osób Zaginionych','','Historia'],
  [31,8,'Dzień Solidarności i Wolności','','Historia'],
  [1,9,'Rocznica Wybuchu II Wojny Światowej','','Inne'],
  [1,9,'Dzień Weterana Walk o Niepodległość Rzeczypospolitej Polskiej','','Historia'],
  [1,9,'Początek zajęć w szkołach','','Inne'],
  [8,9,'Międzynarodowy Dzień Piśmiennictwa','','Inne'],
  [8,9,'Międzynarodowy Dzień Walki z Analfabetyzmem','','Zdrowie'],
  [8,9,'Dzień Ratownika Medycznego','','Zdrowie'],
  [8,9,'Dzień Dobrej Wiadomości','','Inne'],
  [9,9,'Międzynarodowy Dzień Urody','','Inne'],
  [10,9,'Dzień Solidarności z Osobami Chorymi na Schizofrenię','','Historia'],
  [10,9,'Światowy Dzień Przeciwdziałania Samobójstwom','','Inne'],
  [12,9,'Święto Wojsk Lądowych','','Inne'],
  [12,9,'Światowy Dzień Pierwszej Pomocy','','Inne'],
  [13,9,'Dzień Programisty','','Nauka'],
  [15,9,'Europejski Dzień Prostaty','','Inne'],
  [15,9,'Międzynarodowy Dzień Demokracji','','Historia'],
  [16,9,'Międzynarodowy Dzień Ochrony Warstwy Ozonowej','','Inne'],
  [17,9,'Dzień Sybiraka','','Zdrowie'],
  [18,9,'Dzień Geologii','','Inne'],
  [19,9,'Fauny i Naturalnych Siedlisk','','Inne'],
  [19,9,'Dzień Dzikiej Flory','','Inne'],
  [21,9,'Międzynarodowy Dzień Pokoju','','Historia'],
  [21,9,'Dzień Służby Celnej','','Inne'],
  [21,9,'Światowy Dzień Osób z Chorobą Alzheimera','','Inne'],
  [22,9,'Międzynarodowy Dzień bez Samochodu','','Inne'],
  [23,9,'Międzynarodowy Dzień Języków Migowych','','Inne'],
  [23,9,'Początek Astronomicznej Jesieni','','Nauka'],
  [26,9,'Dzień Aptekarza','','Zdrowie'],
  [27,9,'Światowy Dzień Serca','','Zdrowie'],
  [27,9,'Międzynarodowy Dzień Głuchych','','Inne'],
  [27,9,'Dzień Polskiego Państwa Podziemnego','','Inne'],
  [27,9,'Światowy Dzień Turystyki','','Inne'],
  [28,9,'Światowy Dzień Walki z Wścieklizną','','Zdrowie'],
  [30,9,'Dzień Chłopaka','','Inne'],
  [30,9,'Międzynarodowy Dzień Tłumacza','','Inne'],
  [1,10,'Międzynarodowy Dzień Lekarza','','Inne'],
  [1,10,'Międzynarodowy Dzień Muzyki','','Kultura'],
  [1,10,'Międzynarodowy Dzień Ludzi Starszych','','Inne'],
  [1,10,'Europejski Dzień Ptaków','','Zwierzęta'],
  [1,10,'Światowy Dzień Wegetarianizmu','','Ekologia'],
  [2,10,'Międzynarodowy Dzień Bez Przemocy','','Inne'],
  [2,10,'Światowy Dzień Zwierząt Hodowlanych','','Zwierzęta'],
  [4,10,'Światowy Dzień Zwierząt','','Zwierzęta'],
  [5,10,'Światowy Dzień Nauczyciela','','Zawody'],
  [5,10,'Światowy Dzień Mieszkalnictwa','','Inne'],
  [6,10,'Światowy Dzień Mózgowego Porażenia Dziecięcego','','Inne'],
  [6,10,'Święto Inspektoratu Wsparcia Sił Zbrojnych','','Inne'],
  [9,10,'Światowy Dzień Poczty','','Inne'],
  [9,10,'Dzień Znaczka Pocztowego','','Inne'],
  [10,10,'Światowy Dzień Zdrowia Psychicznego','','Zdrowie'],
  [10,10,'Dzień Drzewa','','Inne'],
  [11,10,'Międzynarodowy Dzień Dziewczynek','','Inne'],
  [12,10,'Światowy Dzień Chorób Reumatycznych','','Inne'],
  [12,10,'Dzień Bezpiecznego Komputera','','Nauka'],
  [13,10,'Dzień Ratownictwa Medycznego','','Zdrowie'],
  [13,10,'Dzień Dawcy Szpiku','','Inne'],
  [13,10,'Międzynarodowy Dzień Ograniczania Skutków Katastrof','','Inne'],
  [14,10,'Dzień Nauczyciela (Dzień Edukacji Narodowej)','','Zawody'],
  [14,10,'Światowy Dzień Normalizacji','','Inne'],
  [15,10,'Dzień Dziecka Utraconego','','Rodzina'],
  [15,10,'Międzynarodowy Dzień Kobiet Wiejskich','','Rodzina'],
  [15,10,'Światowy Dzień Mycia Rąk','','Inne'],
  [16,10,'Dzień Papieża Jana Pawła II','','Inne'],
  [16,10,'Światowy Dzień Żywności','','Inne'],
  [17,10,'Międzynarodowy Dzień Walki z Ubóstwem','','Zdrowie'],
  [18,10,'Dzień Łączności','','Inne'],
  [18,10,'Dzień Poczty Polskiej','','Inne'],
  [18,10,'Światowy Dzień Menopauzy i Andropauzy','','Inne'],
  [18,10,'Dzień Pracownika Służby Zdrowia','','Zdrowie'],
  [18,10,'Światowy Dzień Monitorowania Wody','','Inne'],
  [19,10,'Narodowy Dzień Pamięci Duchownych Niezłomnych','','Historia'],
  [20,10,'Światowy Dzień Osteoporozy','','Inne'],
  [20,10,'Światowy Dzień Statystyki','','Inne'],
  [22,10,'Międzynarodowy Dzień Świadomości Jąkania','','Inne'],
  [24,10,'Dzień Organizacji Narodów Zjednoczonych','','Inne'],
  [24,10,'Światowy Dzień Informacji Na Temat Rozwoju','','Inne'],
  [25,10,'Dzień Ustawy o Ochronie Zwierząt','','Zwierzęta'],
  [25,10,'Zmiana czasu z letniego na zimowy','','Inne'],
  [27,10,'Światowy Dzień Modlitwy o Pokój','','Inne'],
  [27,10,'Światowy Dzień Dziedzictwa Audiowizualnego','','Inne'],
  [29,10,'Światowy Dzień Chorych na Łuszczycę','','Zdrowie'],
  [31,10,'Halloween','','Inne'],
  [31,10,'Światowy Dzień Oszczędności','','Inne'],
  [1,11,'Wszystkich Świętych','','Inne'],
  [2,11,'Dzień zaduszny','','Inne'],
  [3,11,'Święto Myśliwych (Dzień Św. Huberta)','','Inne'],
  [6,11,'Międzynarodowy Dzień Zapobiegania Wyzyskowi Środowiska Naturalnego podczas Wojen i Konfliktów Zbrojnych','','Inne'],
  [9,11,'Międzynarodowy Dzień Walki z Faszyzmem i Antysemityzmem','','Zdrowie'],
  [9,11,'Światowy Dzień Jakości','','Inne'],
  [10,11,'Światowy Dzień Nauki dla Pokoju i Rozwoju','','Nauka'],
  [11,11,'Narodowe Święto Niepodległości','','Historia'],
  [13,11,'Międzynarodowy Dzień Niewidomych','','Inne'],
  [14,11,'Światowy Dzień Chorych na Cukrzycę','','Zdrowie'],
  [15,11,'Międzynarodowy Dzień Pamięci Ofiar Wypadków Drogowych','','Historia'],
  [16,11,'Międzynarodowy Dzień Tolerancji','','Historia'],
  [17,11,'Ogólnopolski Dzień bez Długów','','Inne'],
  [17,11,'Międzynarodowy Dzień Studenta','','Inne'],
  [19,11,'Światowy Dzień Rzucania Palenia','','Inne'],
  [19,11,'Światowy Dzień Przewlekłej Obturacyjnej Choroby Płuc','','Inne'],
  [20,11,'Dzień Uprzemysłowienia Afryki','','Inne'],
  [21,11,'Światowy Dzień Telewizji','','Inne'],
  [21,11,'Dzień Życzliwości','','Inne'],
  [21,11,'Dzień Pracownika Socjalnego','','Zawody'],
  [22,11,'Króla Wszechświata','','Inne'],
  [22,11,'Uroczystość Jezusa Chrystusa','','Inne'],
  [22,11,'22-26 listopada Dni Honorowego Krwiodawstwa Polskiego Czerwonego Krzyża','','Inne'],
  [23,11,'22-26 listopada Dni Honorowego Krwiodawstwa Polskiego Czerwonego Krzyża','','Inne'],
  [24,11,'22-26 listopada Dni Honorowego Krwiodawstwa Polskiego Czerwonego Krzyża','','Inne'],
  [25,11,'Międzynarodowy Dzień Eliminacji Przemocy wobec Kobiet','','Rodzina'],
  [25,11,'Dzień Kolejarza','','Inne'],
  [25,11,'22-26 listopada Dni Honorowego Krwiodawstwa Polskiego Czerwonego Krzyża','','Inne'],
  [25,11,'Światowy Dzień Pluszowego Misia','','Inne'],
  [25,11,'Światowy Dzień bez Futra','','Inne'],
  [26,11,'22-26 listopada Dni Honorowego Krwiodawstwa Polskiego Czerwonego Krzyża','','Inne'],
  [29,11,'Dzień podchorążego','','Inne'],
  [29,11,'I niedziela Adwentu','','Inne'],
  [29,11,'Międzynarodowy Dzień Solidarności z Narodem Palestyńskim','','Historia'],
  [29,11,'Andrzejki (w nocy z 29 na 30)','','Inne'],
  [1,12,'Światowy Dzień Walki z AIDS','','Zdrowie'],
  [2,12,'Międzynarodowy Dzień Upamiętniający Zniesienie Niewolnictwa','','Inne'],
  [3,12,'Międzynarodowy Dzień Niepełnosprawnych','','Inne'],
  [4,12,'Naftowca i Gazownika)','','Inne'],
  [4,12,'Barbórka (Dzień Górnika','','Zawody'],
  [5,12,'Międzynarodowy Dzień Wolontariusza','','Rodzina'],
  [5,12,'Światowy Dzień Gleby','','Inne'],
  [6,12,'II niedziela Adwentu','','Inne'],
  [6,12,'Dzień św. Mikołaja','','Inne'],
  [7,12,'Międzynarodowy Dzień Lotnictwa Cywilnego','','Inne'],
  [8,12,'Uroczystość Niepokalanego Poczęcia Najświętszej Maryi Panny','','Inne'],
  [9,12,'Międzynarodowy Dzień Przeciwdziałania Korupcji','','Inne'],
  [10,12,'Międzynarodowy Dzień Praw Człowieka','','Historia'],
  [10,12,'Dzień Ochrony Praw Dziecka','','Rodzina'],
  [10,12,'Dzień Odlewnika','','Inne'],
  [11,12,'Międzynarodowy Dzień Terenów Górskich','','Inne'],
  [13,12,'Dzień Księgarza','','Inne'],
  [13,12,'III niedziela Adwentu','','Inne'],
  [13,12,'Światowy Dzień Telewizji dla Dzieci','','Inne'],
  [13,12,'Dzień Pamięci Ofiar Stanu Wojennego','','Historia'],
  [17,12,'Dzień bez Przekleństw','','Ekologia'],
  [18,12,'Międzynarodowy Dzień Emigrantów','','Inne'],
  [19,12,'Dzień Narodów Zjednoczonych dla Współpracy Południe - Południe','','Zawody'],
  [20,12,'IV niedziela Adwentu','','Inne'],
  [20,12,'Międzynarodowy Dzień Solidarności','','Historia'],
  [20,12,'Dzień Ryby','','Inne'],
  [21,12,'Początek astronomicznej zimy - najkrótszy dzień roku','','Nauka'],
  [24,12,'Wigilia Bożego Narodzenia','','Inne'],
  [25,12,'Boże Narodzenie (pierwszy dzień)','','Inne'],
  [26,12,'Boże Narodzenie (drugi dzień)','','Inne'],
  [27,12,'Święto Świętej Rodziny','','Rodzina'],
  [27,12,'Narodowy Dzień Zwycięskiego Powstania Wielkopolskiego','','Inne'],
  [31,12,'Sylwester','','Inne']