const PROVERBS = {
  1: [
    { d:1,   names:'Mieczysławy, Seweryna',                  p:['Jak styczeń mroźny, rok będzie płodny.','Nowy Rok — nowe szczęście, stara bieda się polepsza.','Jaki Nowy Rok, taki cały rok.'] },
    { d:2,   names:'Bazylego, Grzegorza',                    p:['Styczeń ciepły — marzec mroźny.','Gdy styczeń wilgotny, lato suche.'] },
    { d:3,   names:'Genowefy, Daniela',                      p:['Mróz w styczeń — pszenica w spiżarni.','Styczeń bez śniegu — zły rok dla rolnika.'] },
    { d:4,   names:'Tytusa, Anieli',                         p:['Zimny styczeń — ciepły maj.','Gdy w styczeń mróz trzaska, lato złotem błyska.'] },
    { d:5,   names:'Edwarda, Szymona',                       p:['Styczeń odwilżą znaczony — kwiecień mroźny.','Przed Trzech Króli dni jasne — rok urodzajny.'] },
    { d:6,   names:'Kacpra, Melchiora, Baltazara',           p:['Na Trzech Króli zima w pełni.','Gdy na Trzech Króli mróz — do marca będzie ostry kłos.','Trzej Królowie z gwiazdą — zima do wiosny nie odpada.'] },
    { d:7,   names:'Juliana, Rajmunda',                      p:['Po Trzech Królach styczeń strzela mrozem.','Styczeń pełen śniegu — dobry rok dla stodoły.'] },
    { d:8,   names:'Seweryna, Marii',                        p:['Ile śniegu w styczeń pada, tyle deszczu w maju pada.','Styczeń mglisty — marzec deszczowy.'] },
    { d:9,   names:'Marceliny, Adama',                       p:['Mroźny styczeń — ciepły kwiecień.','Styczeń słoneczny — ale zimny.'] },
    { d:10,  names:'Wilhelma, Danuty',                       p:['Gdy w połowie zimy śnieg leży — zboże w stodole się jeży.','Styczeń śniegiem pokryty — w lecie pola obfite.'] },
    { d:11,  names:'Honoraty, Ernesta',                      p:['Im więcej śniegu w styczeń pada, tym wiosna wcześniej nastaje.','Śnieg w styczeń to złoto dla pól.'] },
    { d:12,  names:'Benedykta, Tatiany',                     p:['Styczeń ciepły — wiosna ostra.','Gdy w styczeń woda, w marcu loda.'] },
    { d:13,  names:'Bogumyły, Weroniki',                     p:['Styczeń deszczem się zaznajomi — marzec śniegiem się przypomni.','Styczeń bez mrozu — zły znak dla chłopa.'] },
    { d:14,  names:'Feliksa, Niny',                          p:['Mrozy stajenne w styczeń — dobry rok dla koni.','Kiedy styczeń najmroźniejszy, wtedy roczek najpłodniejszy.'] },
    { d:15,  names:'Pawła, Arnolda',                         p:['Styczeń mroźny bez śniegu — wiosna bez deszczu.','Gdyby styczeń miał lato, wrzesień miałby mróz za to.'] },
    { d:16,  names:'Marcelego, Waldemara',                   p:['Na Marcelego zima się zaostrza lub odpuszcza.','Marceli — jeśli mroźny, rok korzystny.'] },
    { d:17,  names:'Antoniego',                              p:['Na świętego Antoniego mróz piszczy na błoniu.','Antoni surowy — luty spokojny.'] },
    { d:18,  names:'Małgorzaty, Piotra',                     p:['Środek zimy — mróz się pości lub odpuszcza.','Styczeń bez wichru — dobry rok dla ogrodnika.'] },
    { d:19,  names:'Henryka, Mariusza',                      p:['Gdy styczeń mgłami przykryty — lato suche.','Po świętym Henryku wiosna za trzy tygodnie.'] },
    { d:20,  names:'Fabiana, Sebastiana',                    p:['Na świętego Sebastiana zima jest panią.','Gdy na Fabiana słońce zaświeci, piękne lato się wróży.','Sebastian mroźny — rżysko obfite.'] },
    { d:21,  names:'Agnieszki',                              p:['Agnieszka mroźna — wiosna wczesna.','Na świętą Agnieszkę śnieg na polach gęsto leży.'] },
    { d:22,  names:'Anastazego, Wincentego',                 p:['Na Wincentego słońce zaświeci — zima się skróci.','Wincenty mroźny — kwiecień bezbłędny.'] },
    { d:23,  names:'Ildefonsa, Rajmunda',                    p:['Rajmund śniegiem obsypany — marzec umiarkowany.','Koniec trzeciej dekady stycznia — zima odpuszcza lub się zaostrza.'] },
    { d:24,  names:'Felicji, Tymoteusza',                    p:['Tymoteusz mroźny — rok wczesny.','Na Tymoteusza dzień dłuższy o chwilę.'] },
    { d:25,  names:'Pawła, Delfiny',                         p:['Na nawrócenie Pawła dobra pogoda — rok będzie miał uroda.','Jeśli w dzień świętego Pawła słońce świeci, rok zboże zasięci.','Paweł z mrozem — lipiec z żarem.'] },
    { d:26,  names:'Tymoteusza, Tytusa',                     p:['Po świętym Pawle dni wyraźnie przyrastają.','Styczeń u końca — zima w pół drogi.'] },
    { d:27,  names:'Anieli, Hieronima',                      p:['Aniela mroźna — lato chłodne.','Na koniec stycznia zima liczy dni.'] },
    { d:28,  names:'Tomasza z Akwinu, Walerego',             p:['Wróżba na wigilię lutego: ile śniegu, tyle deszczu w maju.','Ostatnie dni stycznia srogie — luty łagodne.'] },
    { d:29,  names:'Franciszka Salezego, Zdzisławy',         p:['Franciszek na śniegu chodzi — luty za nim przychodzi.','Koniec miesiąca bez mrozu — wróży rok urodzaju.'] },
    { d:30,  names:'Martyny, Macieja',                       p:['Martyna w mrozie — wiosna skora.','Przed lutym zima jeszcze zębami kłapie.'] },
    { d:31,  names:'Marceli, Jana Bosco',                    p:['Ostatni dzień zimy pierwszej — lutowy mróz już czeka.','Styczeń za sobą zostawia ślady na śniegu.'] },
  ],
  2: [
    { d:1,   names:'Brygidy, Ignacego',                      p:['Luty krótki, ale bardzo czuły.','Luty — tydzień mroźny, tydzień odwilżowy.'] },
    { d:2,   names:'Marii, Ofiarowania Pańskiego',           p:['Na Gromniczną połowa zimy minioną.','Gdy na Gromniczną słońce zaświeci, niedźwiedź w dziurze jeszcze poleci.','Gromniczna słoneczna — sześć tygodni do wiosny daleko.'] },
    { d:3,   names:'Błażeja, Oskara',                        p:['Na świętego Błażeja zima do ucieczki się poddaje.','Błażej gardło leczy — mrozy też ustępują.'] },
    { d:4,   names:'Weroniki, Andrzeja',                     p:['Luty zmienny jak kameleon — raz mróz, raz odwilż.','Gdy luty z deszczem — marzec ze śniegiem.'] },
    { d:5,   names:'Agaty, Adelajdy',                        p:['Na świętą Agatę zima traci szatę.','Agata słoneczna — wiosna wczesna.'] },
    { d:6,   names:'Doroty, Pawła',                          p:['Dorotka kwiatki niesie — ale mróz je przyniesie.','Gdy Dorota z burzą — wiosna będzie burzliwa.'] },
    { d:7,   names:'Ryszarda, Romualda',                     p:['Luty pełen śniegu — marzec pełen wody.','Śnieg w lutym — złoto na polu w lecie.'] },
    { d:8,   names:'Hieronima, Jana',                        p:['Luty deszczowy — marzec mroźny.','Gdy w lutym odwilż — mróz w marcu powróci.'] },
    { d:9,   names:'Apolonii, Cyryla',                       p:['Luty bez mrozu — zły rok dla zbóż.','Apolonia z mrozem — zęby bolą, ale zima zdrowa.'] },
    { d:10,  names:'Scholastyki, Wilhelma',                  p:['Scholastyka w śniegu — lato w chłodzie.','Środek lutego — zima zaczyna tracić siły.'] },
    { d:11,  names:'Marii z Lourdes, Lucjana',               p:['Na Matkę Boską Gromniczną albo mrozy, albo odwilż.','Luty lubi zaskoczyć.'] },
    { d:12,  names:'Eulalii, Damiana',                       p:['Luty na odwilż — marzec na ziąb.','Gdy w połowie lutym ciepło — biada ogrodniku.'] },
    { d:13,  names:'Grzegorza, Agnieszki',                   p:['Przed Walentym ptaki się już budzą.','Luty zmienny, rok niezmienny.'] },
    { d:14,  names:'Walentego, Cyryla',                      p:['Na świętego Walentego ptaki się kojarzą, ludzie miłością darzą.','Walenty mrozem straszy, ale zimy nie przedłuży.','Gdy Walenty słoneczny — miłość i urodzaj.'] },
    { d:15,  names:'Faustyny, Jowity',                       p:['Po Walentym dzień coraz wyraźniej dłuższy.','Faustyna słoneczna — wiosna blisko.'] },
    { d:16,  names:'Julianny, Danuty',                       p:['Luty ma krótko — ale kłuje mocno.','Juliana mroźna — marzec łagodny.'] },
    { d:17,  names:'Aleksego, Donata',                       p:['Na Aleksego pola jeszcze we śnie leżą.','Luty ku końcowi — zima się chwieje.'] },
    { d:18,  names:'Szymona, Konstancji',                    p:['Szymon w lutym — wiosna za miesiąc.','Luty ostatnią kartę ze śniegu przerzuca.'] },
    { d:19,  names:'Arnolda, Konrada',                       p:['Luty odwilżowy — marzec śnieżny.','Przed końcem lutego — obserwuj niebo.'] },
    { d:20,  names:'Leona, Ludomiry',                        p:['Leon mroźny — kwiecień słoneczny.','Luty z mrozem — wiosna w sile.'] },
    { d:21,  names:'Eleonory, Anny',                         p:['Luty ostatnią bitwę z zimą stacza.','Gdy w lutym grzmi — wiosna bez zwłoki.'] },
    { d:22,  names:'Marty, Piotra',                          p:['Na Piotrowym Stolcu pola śniegiem okute.','Luty — zima się spieszy.'] },
    { d:23,  names:'Romany, Damiana',                        p:['Przedostatni tydzień lutowy — wiosna w bramie.','Gdy luty bez śniegu — lato bez deszczu.'] },
    { d:24,  names:'Macieja, Bogusława',                     p:['Święty Maciej lód łamie, a jak nie — to zamraża.','Na Maciejowy dzień zima bierze w lód albo pierzyna w błoto wpada.','Maciej z lodem — bociany za rok.'] },
    { d:25,  names:'Wiktora, Cezarego',                      p:['Wiktor z odwilżą — marzec ze śniegiem.','Luty ku końcowi — pole coraz głośniej woła.'] },
    { d:26,  names:'Aleksandra, Mirosławy',                  p:['Aleksander na przełomie — zima lub wiosna.','Ostatni tydzień lutowy liczy mrozy.'] },
    { d:27,  names:'Gabriela, Leandra',                      p:['Gabriel z ciepłem — marzec zaskakuje.','Luty ciepły — marzec zdradliwy.'] },
    { d:28,  names:'Romana, Makarego',                       p:['Ostatni dzień lutego — zima pożegnać się nie spieszy.','Luty krótki — ale pamiętany.'] },
  ],
  3: [
    { d:1,   names:'Albina, Antoniny',                       p:['Marzec jak zając — ucieka i wraca.','Pierwszy marzec ciepły — kwiecień mroźny.'] },
    { d:2,   names:'Heleny, Karola',                         p:['Marzec deszczowy — maj słoneczny.','Gdy marzec z deszczem — zboże radosne.'] },
    { d:3,   names:'Kingi, Kunegundy',                       p:['Suchy marzec, kwiecień mokry, maj przechłodny — nie będzie rok głodny.','Kunegunda z mrozem — Kazimierz z odwilżą.'] },
    { d:4,   names:'Kazimierza',                             p:['Święty Kazimierz śnieg przywozi lub odpędza.','Na Kazimierza wiosnę za kołnierz ciepło wpuszcza.','Kazimierz mroźny — rok zbożny.'] },
    { d:5,   names:'Fryderyka, Adriana',                     p:['Po świętym Kazimierzu rzeki zaczynają topnieć.','Marzec zmienny — rolnik czujny.'] },
    { d:6,   names:'Róży, Wiktora',                          p:['Marzec z mrozem po Kazimierzu — krótko postoi.','Gdy w marcu burza — maj gorący.'] },
    { d:7,   names:'Tomasza, Felicyty',                      p:['Marzec z piorunem — lato z grzmotem.','Siedem dni marca — zima lub wiosna.'] },
    { d:8,   names:'Marii, Jana',                            p:['Na Marię w marcu kwiaty w śniegu.','Gdy marzec mokry — polska trawa tłusta.'] },
    { d:9,   names:'Franciszki, Dominika',                   p:['Co marzec wypiecze, to kwiecień wysiecze.','Franciszka w słońcu — wiosna za tydzień.'] },
    { d:10,  names:'Aleksandra, Maksa',                      p:['Marzec deszczowy i zimny — czerwiec gorący.','Gdy marzec szumi — bociany rychło lecą.'] },
    { d:11,  names:'Benedykta, Rozalii',                     p:['Benedykt przychodzi z wiosną na plecach.','Na Benedykta słońce — dobre zboże w polu.'] },
    { d:12,  names:'Grzegorza',                              p:['Na świętego Grzegorza idzie zima do morza.','Gdy Grzegorz przyszedł, bociany za nim przyszły.','Grzegorz słoneczny — wiosna pewna.'] },
    { d:13,  names:'Bożeny, Krystyny',                       p:['Po Grzegorzu bocian przyleciał — zima odfrunęła.','W marcu, gdy są grzmoty, urośnie zboże ponad płoty.'] },
    { d:14,  names:'Leontyny, Matyldy',                      p:['Matylda wiosenna — lato ciepłe.','Marzec z wichrem — kwiecień spokojny.'] },
    { d:15,  names:'Klemensa, Longina',                      p:['Połowa marca — zima lub wiosna.','Gdy marzec z mrozem w połowie — nie siać przed końcem marca.'] },
    { d:16,  names:'Izabeli, Bonifacego',                    p:['Izabela w słońcu — sady obiecują.','Marzec ciepły w połowie — kwiecień mokry.'] },
    { d:17,  names:'Patryka, Zbigniewa',                     p:['Na Patryka wiosna za progiem stoi.','Patryk z ciepłem — chmiel w górę rośnie.'] },
    { d:18,  names:'Cyryla, Edwarda',                        p:['Cyryl wiosenny — ogród radosny.','Przed Józefem obejrzyj sad i ogród.'] },
    { d:19,  names:'Józefa',                                 p:['Święty Józef ciepło do chaty niesie.','Na świętego Józefa sadzonki w ziemię wkładaj, bo dobry owoc w sadzie będziesz miał.','Józef słoneczny — rok w owoce bogaty.'] },
    { d:20,  names:'Aleksandra, Klaudii',                    p:['Równonoc wiosenna — dzień z nocą w parze.','Na równonoc wiosenną przyroda się budzi.'] },
    { d:21,  names:'Benedykta, Nikifora',                    p:['Pierwszy dzień wiosny w kalendarzu — ale natura decyduje.','Jedna jaskółka nie przynosi wiosny.'] },
    { d:22,  names:'Kazimiry, Eugenii',                      p:['Po równonocy dzień przeważa nad nocą.','Marzec ciepły po dwudziestym — kwiecień pogodny.'] },
    { d:23,  names:'Pelagii, Feliksa',                       p:['Na koniec marca ziemia pragnie nasion.','Marzec z burzą — rok urodzajny.'] },
    { d:24,  names:'Marka, Gabriela',                        p:['Gabriel wiosenny — dobra nowina dla pól.','Przed Zwiastowaniem bocian ląduje.'] },
    { d:25,  names:'Marii, Zwiastowania',                    p:['Na Zwiastowanie bocian do domu wita — wiosna jak złoto.','Na Zwiastowanie kto nie sieje, przez lato popłakuje.','Zwiastowanie słoneczne — rok dostatni.'] },
    { d:26,  names:'Larysy, Emanueli',                       p:['Po Zwiastowaniu zima powrotu nie ma.','Marzec ku końcowi — siewnik gotuj.'] },
    { d:27,  names:'Ernesta, Jana',                          p:['Ostatnia dekada marca — czas siewu.','Gdy marzec ciepły na końcu — kwiecień będzie trudny.'] },
    { d:28,  names:'Anieli, Sykstusa',                       p:['Aniela wiosenna — kwiaty za tydzień.','Marzec odchodzi — kwiecień nadchodzi.'] },
    { d:29,  names:'Wiktoryna, Helmuta',                     p:['Przedostatni marzec — siej owies z ufnością.','Marzec z wiatrem — kwiecień z deszczem.'] },
    { d:30,  names:'Amelii, Leonarda',                       p:['Na koniec marca — żywot się budzi.','Amelia wiosenna — sad rozkwita.'] },
    { d:31,  names:'Beniamina, Guida',                       p:['Ostatni marzec — wiosna rządzi.','Gdy koniec marca ciepły — maj pracowitych nagradza.'] },
  ],
  4: [
    { d:1,   names:'Hugona, Ireny',                          p:['Kwiecień plecień — bo przeplata trochę zimy, trochę lata.','Kwiecień mokry — w stodole pełne wiadra.','Prima Aprilis — żart kwiatami okryty.'] },
    { d:2,   names:'Franciszka, Urszuli',                    p:['Kwiecień deszczowy — trawnik zielony.','Gdy drugi kwiecień z deszczem — maj słoneczny.'] },
    { d:3,   names:'Ryszarda, Ireny',                        p:['Przyjdzie kwiecień, ostatki z gumna wymieciem.','Mróz w kwiecień — owoc w lipcu.'] },
    { d:4,   names:'Izydora, Benedykta',                     p:['Na Izydora pola się śmieją.','Suchy marzec, maj nie chłodny, kwiecień mokry, rok nie głodny.'] },
    { d:5,   names:'Ireny, Wincentego',                      p:['Kwiecień z wichrem — marzec pamiętany.','Gdy w kwiecień liście rozwijają — lato pełne obiecują.'] },
    { d:6,   names:'Celestyna, Wilhelma',                    p:['Celestyn wiosenny — ogrodnicy radośni.','Deszcze częste w kwietniu wróżą, że owoców będzie dużo.'] },
    { d:7,   names:'Jana, Rufina',                           p:['Kwiecień z burzą — rok w zboże bogaty.','Gdy w kwiecień grzmoty — sierpień z dostatkiem.'] },
    { d:8,   names:'Cezarego, Dionizego',                    p:['Kwiecień mokry na początku — koniec suchy.','Dionizy z deszczem — winogrona kwaśne.'] },
    { d:9,   names:'Marii, Waltruda',                        p:['Na początku kwiet kwiaty ziemia wydaje.','Kwiecień deszczowy to złoto w stodole.'] },
    { d:10,  names:'Michała, Makarego',                      p:['Michał wiosenny — pola głośno wołają.','Gdyby w kwietniu nie padało, to owoców będzie mało.'] },
    { d:11,  names:'Leona, Filipa',                          p:['Kwiecień z słońcem — ziemia wysycha.','Gdy kwiecień słoneczny — maj suchy.'] },
    { d:12,  names:'Juliusza, Zenona',                       p:['Kwiecień daje i odbiera — tak chce natura.','Juliusz wiosenny — wróżba lata.'] },
    { d:13,  names:'Przemysława, Hermenegilda',              p:['Kwiecień co deszczem rosi, wiele owoców przynosi.','Gdy w kwiecień mróz — majowi pomóż.'] },
    { d:14,  names:'Waleriana, Justyny',                     p:['Walerian wiosenny — zioła rosną.','Jak przygrzeje słonko, przejdzie kwiecień łąką.'] },
    { d:15,  names:'Anastazji, Wacława',                     p:['Połowa kwiet — wiosna w pełni.','Wacław wiosenny — ogrody radosne.'] },
    { d:16,  names:'Benedykta, Bernadety',                   p:['Bernadeta kwiat ma w ręku — wiosna na wsi.','Choć i w kwietniu słonko grzeje, nieraz pole śnieg zawieje.'] },
    { d:17,  names:'Roberta, Rudolfa',                       p:['Robert wiosenny — jeziora pełne.','Jeśli w kwietniu pszczoły latają, to długie chłody się zapowiadają.'] },
    { d:18,  names:'Bogumiły, Apoloniusza',                  p:['Bogumił w wiośnie — dusze szczęśliwe.','Kwiecień ciepły w połowie — maj kapryśny.'] },
    { d:19,  names:'Tymona, Adolfa',                         p:['Kwiecień z mroźnymi nocami — majowe przymrozki pamiętaj.','Timon wiosenny — ryby w rzece.'] },
    { d:20,  names:'Agnieszki, Czesława',                    p:['Agnieszka wiosenna — zioła kwitnące.','Pogody kwietniowe — słoty majowe.'] },
    { d:21,  names:'Anzelma, Feliksa',                       p:['Kwiecień z ciepłem po dwudziestym — maj pracowity.','Anzelm z deszczem — maj zielony.'] },
    { d:22,  names:'Łukasza, Kai',                           p:['Ziemia Matka w kwiecień budzi — rolnik pracuje.','Na Dzień Ziemi natura mówi.'] },
    { d:23,  names:'Wojciecha',                              p:['Na świętego Wojciecha bociany budzą z kochanki nieba.','Gdy Wojciech mroźny, owoc tego roku będzie kosztowny.','Wojciech z słońcem — żyto się obiecuje.'] },
    { d:24,  names:'Horacego, Jerzego',                      p:['Jerzy na koniu — zima pobita.','Na świętego Jerzego wąż z dziury wychodzi.'] },
    { d:25,  names:'Marka, Jarosława',                       p:['Na Marka — słońce grzeje mocniej.','Marek wiosenny — poluj na pieczarki.'] },
    { d:26,  names:'Marzeny, Klety',                         p:['Kwiecień ku końcowi — pszczoły w kwiatach.','Marzenka w słońcu — winogrona obiecuje.'] },
    { d:27,  names:'Zyty, Teofila',                          p:['Zyta z kwiatami — stodoła pełna.','Kwiecień na końcu — sprawdź drzewa owocowe.'] },
    { d:28,  names:'Witalisa, Piotra',                       p:['Witalis z deszczem — ogród kwitnie.','Kwiecień ostatni — siej co możesz.'] },
    { d:29,  names:'Katarzyny ze Sieny, Roberty',            p:['Katarzyna wiosenna — zioła zbieraj.','Przed majem kwiecień ostatnią szansę daje.'] },
    { d:30,  names:'Katarzyny, Mariana',                     p:['Kwiecień bez deszczu — w stodole cicho.','Kwiecień z piorunami — lato jak marzenie.','Ostatni kwiecień — maj za drzwiami.'] },
  ],
  5: [
    { d:1,   names:'Józefa Robotnika, Filipa',               p:['Maj chłodny i deszczowy — rok urodzajny.','Kto w maju nie pracuje, ten przez zimę gościuje.','Majowe deszcze — złoto dla pól.'] },
    { d:2,   names:'Zygmunta, Atanazego',                    p:['Chłodny maj, dobry urodzaj.','Gdy maj z deszczem na początku — sierpień obfity.'] },
    { d:3,   names:'Marii, Antoniny',                        p:['Na Konstytucję Trzeciego Maja — wiosna pełna.','Maj trzeci z kwiatami — rok dostatni.'] },
    { d:4,   names:'Floriana, Moniki',                       p:['Florian ognie gasi — deszcze przywołuje.','Na Floriana deszcz pada — pożary nie grożą.'] },
    { d:5,   names:'Ireny, Waldemara',                       p:['Deszcz majowy, chleb gotowy.','Irena w słońcu — dobre lato obiecuje.'] },
    { d:6,   names:'Jana, Judyty',                           p:['Kiedy mokry maj, będzie żyto jako gaj.','Gdy w maju mgły poranne — upał w południe.'] },
    { d:7,   names:'Stanisława, Gizeli',                     p:['Na świętego Stanisława lato się przedstawia.','Stanisław z deszczem — żyto radosne.'] },
    { d:8,   names:'Stanisława Biskupa, Wiktora',            p:['Maj ósmy z burzą — rok w żyto bogaty.','Gdy maj grzmi — sierpień gorący.'] },
    { d:9,   names:'Grzegorza, Bożeny',                      p:['Gdy maj jest przy pogodzie, nie bywają siana w szkodzie.'] },
    { d:10,  names:'Izydora, Antoniego',                     p:['Izydor rolnik — patron dobrych zbiorów.','Na Izydora zasiewaj najpóźniej.'] },
    { d:11,  names:'Filipa, Ignacego',                       p:['Grzmot w maju nie szkodzi, sad dobrze obrodzi.'] },
    { d:12,  names:'Pankracego, Dominika',                   p:['Pankracy mróz przynosi — strzeż sadzone.','Zimni Ogrodnicy: Pankracy, Serwacy, Bonifacy — trzy mroźne dni.'] },
    { d:13,  names:'Serwacego, Natalii',                     p:['Serwacy mroźny — drzewa owocowe cierpią.','Gdy Serwacy bez mrozu — lato gorące.'] },
    { d:14,  names:'Bonifacego, Korony',                     p:['Bonifacy z lodem — ogrodnicy płaczą.','Po Bonifacym mróz nie wraca.'] },
    { d:15,  names:'Zofii, Izydora',                         p:['Zimna Zofia, Pankracy, Serwacy — trzej mroźni bracia.','Na Zofię idź boso po rosie, zdrowie do domu przyniesie.','Po Zimnej Zofii — mróz odpuszcza.'] },
    { d:16,  names:'Andrzeja Boboli, Jana',                  p:['Po zimnych ogrodnikach — ciepło pewne.','Jeśli w maju grzmot, rośnie wszystko w lot.'] },
    { d:17,  names:'Paschalisa, Sławomira',                  p:['Kiedy lipa w maju kwitnie, to w ulach miód zawiśnie.'] },
    { d:18,  names:'Eryka, Jana',                            p:['Maj osiemnasty z deszczem — czerwiec suchy.','Dużo chrabąszczy w maju, proso będzie niby w gaju.'] },
    { d:19,  names:'Piotra, Ivo',                            p:['Gdy kukułka kuka w maju, spodziewaj się urodzaju.'] },
    { d:20,  names:'Antoniny, Bernardyna',                   p:['Bernardyn z kwiatami — lato piękne.','Gdy się maj z grzmotem odezwie na wschodzie, rok sprzyja sianu i zbożu.'] },
    { d:21,  names:'Wiktora, Tymoteusza',                    p:['Wiktor w maju — w polu wesoło.','Maj ciepły po dwudziestym — dobrze wróży.'] },
    { d:22,  names:'Romy, Julii',                            p:['Rita z różą — maj pełen kwiatów.','Maj bogaty sieje kwiaty.'] },
    { d:23,  names:'Dezyderego, Iwony',                      p:['Dezydery z deszczem — staw pełny.','Maj na końcu — lato się zbliża.'] },
    { d:24,  names:'Joanny, Zuzanny',                        p:['Majowe błoto, więcej niż złoto.'] },
    { d:25,  names:'Grzegorza VII, Urbana',                  p:['Na świętego Urbana dobre wino w beczułce schowane.','Jeśli Urban z deszczem, wino kwaśne do pieśni.','Urban słoneczny — winnica obiecuje.'] },
    { d:26,  names:'Filipa Neri, Eweliny',                   p:['Filip Neri — kapłan wiosenny.','Częste w maju grzmoty rozpraszają chłopom zgryzoty.'] },
    { d:27,  names:'Augustyna, Jana',                        p:['Maj — bydłu daj, a sam za piec uciekaj.','Maj na końcu zbiera siły do lata.'] },
    { d:28,  names:'Germana, Jarosława',                     p:['Chłodny maj, dobry urodzaj.','Przedostatni tydzień maja — lato za dwa kroki.'] },
    { d:29,  names:'Maksymiliana, Magdaleny',                p:['Deszcz majowy, chleb gotowy.'] },
    { d:30,  names:'Ferdynanda, Joanny',                     p:['Kiedy mokry maj, będzie żyto jako gaj.','Maj na ostatku — każdy chwyta wolny czas.'] },
    { d:31,  names:'Anieli, Petroneli',                      p:['Ostatni maj — lato tuż tuż.','Gdy maj jest przy pogodzie, nie bywają siana w szkodzie.','Na końcu maja — liczy się żyto.'] },
  ],
  6: [
    { d:1,   names:'Justyny, Nikodema',                      p:['Czerwiec ciepły — zboże radosne.','Czerwiec deszczowy — sierpień gorący.'] },
    { d:2,   names:'Marceliny, Erazma',                      p:['Czerwiec daje dni gorące, kosa brzęczy już na łące.','Erazm z deszczem — ogród kwitnie.'] },
    { d:3,   names:'Klotyldy, Karola',                       p:['Czerwiec stały, grudzień doskonały.'] },
    { d:4,   names:'Franciszka, Kwiryna',                    p:['Gdy czerwiec chłodem i wodą szafuje, to zwykle rok cały popsuje.','Gdy czerwiec z burzą na początku — lato gorące.'] },
    { d:5,   names:'Bonifacego, Walburgi',                   p:['Czerwiec na maju zwykle się wzoruje, jego pluchy, pogody, często naśladuje.'] },
    { d:6,   names:'Norberta, Filipa',                       p:['Siej na świętego Norberta, będzie jęczmienia sterta.'] },
    { d:7,   names:'Roberta, Wiesławy',                      p:['Norbert, Robert, Medard to bracia młodzi, spodziewajcie się powodzi.'] },
    { d:8,   names:'Medarda',                                p:['Medard deszczem obdarzył — czterdzieści dni deszczem straszył.','Na Medarda jak pada — przez czterdzieści dni nie ustaje woda.','Medard suchy — czterdzieści dni bez deszczu.'] },
    { d:9,   names:'Diany, Felicjana',                       p:['Po Medardzie czterdzieści dni niezmienne.','Kiedy kwitnie w czerwcu bób, to największy wtedy głód, a kiedy mak, to już nie tak.'] },
    { d:10,  names:'Bogumiła, Małgorzaty',                   p:['Bogumił z deszczem — pszczoły w pracy.','Od czerwca dużo zależy, czy żniwa będą jak należy.'] },
    { d:11,  names:'Barnaby, Jana',                          p:['Na świętego Barnabę idź kosić trawę.'] },
    { d:12,  names:'Jana, Onufrego',                         p:['Na św. Onufry otwierajcie kufry.'] },
    { d:13,  names:'Antoniego z Padwy',                      p:['Antoni z Padwy — kto zguby szuka, znajdzie.','Na Antoniego deszcz pada — zboże pełne wody.'] },
    { d:14,  names:'Walerego, Michała',                      p:['Pełnia czerwcowa — burza gotowa.'] },
    { d:15,  names:'Wita, Modesta',                          p:['Gdy przychodzi Witus suchy, tedy wiedzie z sobą muchy.','Na świętego Wita zboże zakwita.','Na świętego Wita ze śpiewem ptaków kwita.'] },
    { d:16,  names:'Benona, Aliny',                          p:['W czerwcu grusze kwiat zrzucają, czereśnie się zapalają.','Alina z rosą — ogród radosny.'] },
    { d:17,  names:'Laury, Marcjalisa',                      p:['W czerwcu się okaże, co nam Bóg da w darze.'] },
    { d:18,  names:'Marka, Elżbiety',                        p:['Nie trzeba w czerwcu o deszcz prosić, przyjdzie jak zaczniemy kosić.'] },
    { d:19,  names:'Gerwazego, Protazego',                   p:['Gerwazy z deszczem — Paweł z słońcem.','Na świętego Gerwazego jest w ogrodzie coś pięknego.'] },
    { d:20,  names:'Bogny, Rafaela',                         p:['Grzmoty czerwca rozweselają rolnikom serca.'] },
    { d:21,  names:'Alojzego, Rudolfa',                      p:['Na Alojzego — dzień najdłuższy.','Letnie przesilenie — słońce na szczycie.'] },
    { d:22,  names:'Pauliny, Jana',                          p:['Po przesileniu dzień zaczyna wracać.','Czerwiec zimny i wilgotny, całemu roku bardzo psotny.'] },
    { d:23,  names:'Wandy, Józefa',                          p:['Gdzie sobótki palą, tam grady nie przeszkadzają.','Na Sobótkę dziewczęta kwiatami się ozdabiają.'] },
    { d:24,  names:'Jana Chrzciciela',                       p:['Na Jana Chrzciciela słońce nad ziemią miga — urodzaj nie ucieka.','Gdy na świętego Jana rzeka wzbiera — rok w polu obfity.','Na Jana kąp się w rzece, zdrowie do ciała płynie.'] },
    { d:25,  names:'Łucji, Wilhelma',                        p:['Po Janie lato chodzi inaczej.','Czerwiec gdy zagrzmi, gdzie zorze zachodzą, ryby się obficie zrodzą.'] },
    { d:26,  names:'Jana, Dawida',                           p:['W czerwcu pełnia sprowadza burze, ostatnia kwadra zaś deszcze duże.'] },
    { d:27,  names:'Cyryla, Władysława',                     p:['Władysław z burzą — deszcz do końca tygodnia.','Czerwiec się czerwieni, będzie dość w kieszeni.'] },
    { d:28,  names:'Leona, Anny',                            p:['Czerwiec daje dni gorące, kosa brzęczy już na łące.','Czerwiec ku końcowi — żniwa za miesiąc.'] },
    { d:29,  names:'Piotra i Pawła',                         p:['Na Piotra i Pawła żyto w głowę wchodzi — kto nie wierzy, na pole idzie.','Od Piotra i Pawła — żyto do kosy się kłania.','Gdy Piotr i Paweł słoneczni — zboże złote.'] },
    { d:30,  names:'Ottona, Emilii',                         p:['Ostatni czerwiec — żniwa pukają w bramę.','Czerwiec koniec — lato w sile.'] },
  ],
  7: [
    { d:1,   names:'Mariana, Haliny',                        p:['Lipiec skwarny — rok owocny.','Deszcz lipcowy rolnikowi nie drogowy.','Lipiec ciepły — pszczoły szczęśliwe.'] },
    { d:2,   names:'Marii z Góry Karmel, Ottona',            p:['Lipiec deszczowy — sierpień suchy.','Gdy lipiec mglisty — jesień piękna.'] },
    { d:3,   names:'Tomasza, Jacka',                         p:['Gdy w lipcu słońce dopieka, burza niedaleka.'] },
    { d:4,   names:'Elżbiety, Zygmunta',                     p:['Gdy się grzmot w lipcu od południa poda, drzewom się znaczy szwank i nieuroda.'] },
    { d:5,   names:'Karoliny, Antoniego',                    p:['Jeśli upały w sianokosy i żniwa, to zima ostra i dokuczliwa, a jeżeli słota, to w zimie dużo błota.'] },
    { d:6,   names:'Dominiki, Gotarda',                      p:['Kto w lipcu patrzy chłodu, nacierpi się w zimie głodu.','Gdy lipiec z burzami — sierpień spokojny.'] },
    { d:7,   names:'Klaudii, Cyryla',                        p:['Kwiat lipcowy, napój zdrowy.'] },
    { d:8,   names:'Elżbiety, Eugeniusza',                   p:['Lipcowe deszcze dla chłopa kleszcze; jak pogoda, większa swoboda.'] },
    { d:9,   names:'Weroniki, Zenona',                       p:['Gdy się pająk w lipcu przechodzi, ze sobą deszcz przywodzi, gdy swą pajęczynę psuje, bliską burzę czuje.'] },
    { d:10,  names:'Wawrzyńca, Rufiny',                      p:['Lipcowe upały, wrzesień doskonały.'] },
    { d:11,  names:'Benedykta, Olgi',                        p:['W lipcu upały, styczeń mroźny cały.'] },
    { d:12,  names:'Jana Gwalberta, Brunona',                p:['Lipiec — ostatek chleba wypiec.'] },
    { d:13,  names:'Henryka, Sary',                          p:['Miesiąc lipiec musi przypiec i ostatki mąki wypiec.'] },
    { d:14,  names:'Kamila, Bonawentury',                    p:['Upały lipcowe, mrozy styczniowe.'] },
    { d:15,  names:'Henryka, Włodzimierza',                  p:['Połowa lipca — lato w pełni.','W lipcu pszczeli rój, nie opłaci trudu znój.'] },
    { d:16,  names:'Marii z Góry Karmel, Euzebiusza',        p:['Na Karmel — ziele i kwiaty w koszu.','W lipcu gdy służą pogody, bój się wielkiej wody.'] },
    { d:17,  names:'Aleksego, Andrzeja',                     p:['Gdy lipiec z deszczem, zima będzie z wiatrem.'] },
    { d:18,  names:'Sławy, Szymona',                         p:['Jeżeli w żniwa mysz w polu gniazdo wysoko zakłada, znak to, że zima srogie śniegi zapowiada.'] },
    { d:19,  names:'Wincentego, Wiesławy',                   p:['Czego lipiec nie dowarzy, tego sierpień nie dosmaży.'] },
    { d:20,  names:'Eliasza, Czesławy',                      p:['Na Eliasza burze i pioruny — rolnicy się kłaniają.','Eliasz deszczem albo suszą rządzi.','Gdy Eliasz grzmi — lato żar wyda.'] },
    { d:21,  names:'Daniela, Wawrzyńca',                     p:['Kiedy lipiec daje deszcze, długie lato będzie jeszcze.'] },
    { d:22,  names:'Marii Magdaleny',                        p:['Maria Magdalena z deszczem — grzyby po deszczu.','Na Magdaleny deszcz pada — urodzaj wróży.'] },
    { d:23,  names:'Brygidy, Apolinarego',                   p:['Jak poranek mglisty, wieczór przezroczysty.'] },
    { d:24,  names:'Kingi, Jadwigi',                         p:['Czego lipiec i sierpień nie dowarzy, tego wrzesień nie usmaży.'] },
    { d:25,  names:'Jakuba',                                 p:['Na świętego Jakuba zbierać czas grzyba.','Gdy Jakub z deszczem — figi do wina.','Na święty Jakub chleba sobie nakup.'] },
    { d:26,  names:'Anny, Joachima',                         p:['Na Annę — babcie zbierają zioła.','Święta Anka pasie baranka.'] },
    { d:27,  names:'Natalii, Lilii',                         p:['Gdy w lipcu słońce dopieka, burza niedaleka.'] },
    { d:28,  names:'Innocentego, Wiktora',                   p:['Gdy się grzmot w lipcu od południa poda, drzewom się znaczy szwank i nieuroda.','Lipiec ku końcowi — żniwa zaczynają.'] },
    { d:29,  names:'Marty, Olgi',                            p:['Około dnia świętej Marty, ze żniwami już nie żarty.','Na Martę — gospodyni zbiera pierwsze żniwa.'] },
    { d:30,  names:'Piotra, Julity',                         p:['Jak po lipcu gorącym sierpień się ochłodzi, to później zima z wielkim śniegiem chodzi.','Lipiec trzydziesty — sprawdź sianokosy.'] },
    { d:31,  names:'Ignacego Loyoli, Fabiana',               p:['Ostatni lipiec — sierpień puka.','Jeśli upały w sianokosy i żniwa, to zima ostra i dokuczliwa, a jeżeli słota, to w zimie dużo błota.','Koniec lipca — żniwa w pełni.'] },
  ],
  8: [
    { d:1,   names:'Alfonsa, Piotra',                        p:['Sierpień z deszczem — rolnik z pieszczą.','Pierwszy sierpień mokry — całe lato mokre.','Sierpień cały — pracą napełniaj.'] },
    { d:2,   names:'Gustawa, Euzebiusza',                    p:['Na święty Gustaw kopy w polu ustaw.'] },
    { d:3,   names:'Nikodema, Lidii',                        p:['Pogoda na Nikodema — cały miesiąc deszczu nie ma.'] },
    { d:4,   names:'Jana Vianneya, Dominika',                p:['Gdy ciepło na Dominika, ostra zima nas dotyka.'] },
    { d:5,   names:'Marii, Kasjana',                         p:['Gdy w dni sierpnia spieka wszędzie, tedy długa zima będzie.','Gdy sierpień deszczowy — jesień długa.'] },
    { d:6,   names:'Jakuba, Sławy',                          p:['W Przemienienie Pańskie są burze szatańskie.'] },
    { d:7,   names:'Kajetana, Donata',                       p:['Święty Kajetanie, strzeż od deszczu sprzątanie.'] },
    { d:8,   names:'Dominika, Cyriaka',                      p:['Kiedy sierpień przychodzi, reszta zboża z pola schodzi.','Gdy sierpień pogodny — wrzesień spokojny.'] },
    { d:9,   names:'Romana, Teresy',                         p:['Czego sierpień nie dowarzy, tego wrzesień nie doparzy.'] },
    { d:10,  names:'Wawrzyńca',                              p:['Na świętego Wawrzyńca słońce pali, zboże w polu się wali.','Wawrzyniec słońcem pali — żniwa w polu się gonią.','Na Wawrzyńca — noc spadających gwiazd.'] },
    { d:11,  names:'Zuzanny, Klary',                         p:['Od świętej Klary są już ładne dary.'] },
    { d:12,  names:'Hilarii, Leszka',                        p:['Gdy w sierpniu z północy dmucha, następuje zwykle posucha.'] },
    { d:13,  names:'Hipolita, Poncjana',                     p:['Jeżeli w sierpniu gorąco będzie, to zima w śniegi długo zasiędzie.','Gdy sierpień na Hipolita suchy — wrzesień mokry.'] },
    { d:14,  names:'Maksymiliana, Eberharda',                p:['Wigilia Wniebowzięcia — kwiaty do kościoła.','Początki sierpnia pogodne, wróżą zimy łagodne.'] },
    { d:15,  names:'Wniebowzięcia NMP',                      p:['Na Wniebowzięcie Maryi zboże w stodole się leży.','Gdy na Matkę Boską Zielną deszcz pada — jesień mokra nadciąga.','Na Zielną — zioła poświęcone w ręku.'] },
    { d:16,  names:'Rocha, Stefana',                         p:['Na święty Roch w stodole groch.'] },
    { d:17,  names:'Jacka, Bertolda',                        p:['Jeśli w dniu Jacka nie pada, suchą jesień zapowiada.'] },
    { d:18,  names:'Heleny, Klary',                          p:['Żołędzie pełne i białe, przyszłe lato doskonałe.'] },
    { d:19,  names:'Jana Eudes, Magnusa',                    p:['Kiedy sierpień wrzos rozwija, jesień krótka, szybko mija.'] },
    { d:20,  names:'Bernarda, Sławy',                        p:['Jeśli na Bernarda ziemia twarda, to będzie zima harda, a jak miękka to lekka.'] },
    { d:21,  names:'Piusa X, Joanny',                        p:['Jeśli piękny sierpień, gotuj sobie chłopku kieszeń.'] },
    { d:22,  names:'Marii, Tymoteusza',                      p:['Jeśli w sierpniu dni jasne, będą stodoły ciasne.'] },
    { d:23,  names:'Róży z Limy, Filipa',                    p:['W sierpniu grzmotów wiele, mokrą zimę ściele.'] },
    { d:24,  names:'Bartłomieja',                            p:['Na świętego Bartłomieja dobre żniwa do koleja.','Bartłomiej lato zamknie — jesień nadciąga.','Bartłomiej z mgłą — zima wczesna.'] },
    { d:25,  names:'Ludwika, Józefy',                        p:['Gdy sierpień w upały zbywa, lato długie zwykle bywa.'] },
    { d:26,  names:'Marii Częstochowskiej, Irydy',           p:['Na Częstochową — plony do domu.','W sierpniu mgły w górach — mroźne Gody, kiedy mgły w dolinach — to wróżba pogody.'] },
    { d:27,  names:'Józefa Kalasancjusza, Moniki',           p:['Sierpień ku końcowi — jesień puka.','Kto latem pracuje, zimą głodu nie czuje.'] },
    { d:28,  names:'Augustyna, Wiliama',                     p:['Sierpień pogodny jest dla winogron wygodny.'] },
    { d:29,  names:'Sabiny, Jana',                           p:['Dużo grzybów sierpniowych, dużo zawiei śniegowych.','Sierpień ku końcowi — jesień za bramą.'] },
    { d:30,  names:'Róży, Feliksa',                          p:['Sierpień trzydziesty — owce tłuste.','Różany sierpień — zapach na polu.'] },
    { d:31,  names:'Rajmunda, Aidy',                         p:['Ostatni sierpień — lato żegna się.','Ostatni sierpnia zapowiada, jaka pogoda na wrzesień wypada.','Koniec lata — wspomnienie o żniwach.'] },
  ],
  9: [
    { d:1,   names:'Idziego, Bronisławy',                    p:['Święty Idzi wiedzie wrzesień, wnet nadejdzie dżdżysta jesień.'] },
    { d:2,   names:'Stefana, Ingrydy',                       p:['Wrzesień z deszczem — październik suchy.','Gdy wrzesień ciepły — październik mroźny.'] },
    { d:3,   names:'Grzegorza Wielkiego, Danuty',            p:['Wrzeszczy wrzesień, że już jesień.'] },
    { d:4,   names:'Rozalii, Irydy',                         p:['Gdy nadejdzie wrzesień, rolnik ma zawsze pełną kieszeń.'] },
    { d:5,   names:'Doroty, Wawrzyńca',                      p:['Gdy wrzesień bez deszczów będzie, w zimie wiatrów pełno wszędzie.'] },
    { d:6,   names:'Beaty, Magnusa',                         p:['Jak we wrześniu krety kopią po nizinach, będzie wietrzno, ale lekka zima.','Gdy wrzesień mglisty — zima wczesna.'] },
    { d:7,   names:'Reginy, Melchiora',                      p:['Święta Regina mgły rozpina.'] },
    { d:8,   names:'Narodzenia NMP',                         p:['Na Matkę Boską Siewną siej, kiedy czas sprzyja.','Sieje się na Siewną — wschodzi na wiosnę.','Na Siewną — zboże ozime w ziemię.'] },
    { d:9,   names:'Sergiusza, Piotra',                      p:['Gdy grzyby wielkie korzenie mają, wielką zimę zapowiadają.'] },
    { d:10,  names:'Mikołaja, Salomei',                      p:['Wrzesień chodzi po rosie, zbiera grzyby we wrzosie.'] },
    { d:11,  names:'Jacka, Prota',                           p:['Ze wszystkich świętych najlepszy Jacek, bo kto żyje dostał placek.'] },
    { d:12,  names:'Gwidona, Marii',                         p:['Jeśli wrzesień będzie ciepły i suchy, pewno październik nie oszczędzi pluchy.','Gdy wrzesień ciepły w połowie — październik chłodny.'] },
    { d:13,  names:'Jana Złotoustego, Maurycego',            p:['Czym dłużej jaskółki we wrześniu zostają, tym dłużej piękne i jasne dni bywają.'] },
    { d:14,  names:'Podwyższenia Krzyża',                    p:['Na Podwyższenie liście żółkną i w górę lecą.','Wrzesień z deszczem — październik z mrozem.','Na Podwyższenie — żegnaj lato.'] },
    { d:15,  names:'Marii Bolesnej, Nikodema',               p:['Pogoda na Nikodema — niedziel cztery deszczu nie ma.','Maria Bolesna — jesień smutna, ale piękna.'] },
    { d:16,  names:'Korneliusza, Edyty',                     p:['Im głębiej we wrześniu grzebią się robaki, tym srożej się zima da ludziom we znaki.'] },
    { d:17,  names:'Roberta, Hildegardy',                    p:['Jaką pogodę na nowiu da wrzesień, taka bywa zwykle przez całą jesień.'] },
    { d:18,  names:'Stanisławy, Ireny',                      p:['Kiedy Irena z mrozem przybywa, babie lato krótkie bywa.'] },
    { d:19,  names:'Januarego, Konstancji',                  p:['Wrzesień wrzosami strojny, lecz od pracy znojny.'] },
    { d:20,  names:'Eustachiusza, Faustyny',                 p:['Gdy we wrześniu grzybów brak, niezawodny zimy znak.'] },
    { d:21,  names:'Mateusza, Józefata',                     p:['Na świętego Mateusza dostanie kapusta kapelusza.','Na Mateusza — plony policzone.'] },
    { d:22,  names:'Tomasza, Maurycego',                     p:['Wrzesień z więdnącym liściem — zima wróżona.','Jeśli Maurycy ma jasne lice, to przyprowadzi wnet nawałnicę.'] },
    { d:23,  names:'Tekli, Linusa',                          p:['Skoro wrzesień, to już jesień, ale jabłek pełna kieszeń.','Na równonoc jesienną — noc z dniem równy.'] },
    { d:24,  names:'Marii, Gerarda',                         p:['Na Gerarda, gdy sucho, zima będzie z pluchą.'] },
    { d:25,  names:'Władysława, Aurela',                     p:['Wrześniowa słota, miarka deszczu, korzec błota.'] },
    { d:26,  names:'Kosmy i Damiana, Justyny',               p:['Kosma i Damian — obrońcy ogrodu.','We wrześniu, gdy tłuste ptaki, srogo się zima da ludziom we znaki.'] },
    { d:27,  names:'Wincentego de Paul, Floriana',           p:['Wrzesień ku końcowi — jesień rządzi.','Straszna jest wrześniowa słota - miarka deszczu, korzec błota.'] },
    { d:28,  names:'Wacława, Libuszy',                       p:['Na świętego Wacława w polu pustki, w domu sława.'] },
    { d:29,  names:'Michała Archanioła',                     p:['Na Michała gęsi do wsi nawieszają.','Gdy Michał z mrozem — zima pewna przed nozem.','Michał archanioł — jesień strzeże.'] },
    { d:30,  names:'Hieronima, Honoriusza',                  p:['Ostatni wrzesień — październik puka.','Jeśli na świętego Prota jest pogoda albo słota, to na świętego Hieronima deszczyk jest, albo go ni ma.','Koniec września — liście w złocie.'] },
  ],
  10: [
    { d:1,   names:'Teresy, Remigiusza',                     p:['Październik z deszczem — listopad suchy.','Gdy październik mroźny, to nie będzie styczeń groźny.'] },
    { d:2,   names:'Aniołów Stróżów, Teofila',               p:['Na Aniołów Stróżów — anioły pilnują.','Gdy w październiku ciepło chadza, w lutym mrozy naprowadza.'] },
    { d:3,   names:'Wincentego, Gwidona',                    p:['Październik chodzi po kraju, cichnie ptactwo w gaju.','Gdy październik ciepły — listopad mroźny.'] },
    { d:4,   names:'Franciszka z Asyżu',                     p:['Na Franciszka lecą liście jak płatki.','Październik z liściem — ogrodnik spokojny.','Franciszek z Asyżu — przyroda umiłowana.'] },
    { d:5,   names:'Placyda, Leonarda',                      p:['W październiku, gdy liść z drzewa niesporo opada, późną to wiosnę zapowiada.'] },
    { d:6,   names:'Brunona, Czcibora',                      p:['W październiku kawek gromada, słotne dni nam zapowiada.'] },
    { d:7,   names:'Marii Różańcowej, Justyny',              p:['Na różaniec październikowy — pacierze do końca roku.','Kiedy październik śnieżny i chłodny, to styczeń zwykle łagodny.'] },
    { d:8,   names:'Pelagii, Benedykta',                     p:['Ile razy przed nowiem w październiku śnieg spadnie, tyle razy wśród zimy odwilży przypadnie.'] },
    { d:9,   names:'Jana z Capestrano, Elżbiety',            p:['Gdy październik z wodami, grudzień z wiatrami.'] },
    { d:10,  names:'Franciszka, Daniela',                    p:['Październik spoczynku nie chce dać, każe orać, każe siać.'] },
    { d:11,  names:'Emilii, Aleksandra',                     p:['Gdy październik ostro trzyma, zwykle potem ostra zima.'] },
    { d:12,  names:'Maksymiliana, Sławomiry',                p:['Gdy październik mokro trzyma, zwykle potem ostra zima.','Gdy październik pogodny — zima miękka.'] },
    { d:13,  names:'Edwarda, Faustyny',                      p:['Na Edwarda jesień twarda.'] },
    { d:14,  names:'Kaliksta, Benedykta',                    p:['Liść na drzewie mocno trzyma, nie tak prędko przyjdzie zima.'] },
    { d:15,  names:'Teresy z Avila, Jadwigi',                p:['Teresa z Avila — modlitwa jesienna.','Połowa października — zima za dwa miesiące.'] },
    { d:16,  names:'Jadwigi Śląskiej, Małgorzaty',           p:['Jadwiga Śląska — Polska i Niemcy złączone.','Kto sieje na świętą Jadwigę, ten zbiera figę.'] },
    { d:17,  names:'Ignacego, Rozalii',                      p:['Październik ciepły, będzie luty skrzepły.'] },
    { d:18,  names:'Łukasza, Juliana',                       p:['Na Łukasza — słońce po jesiennemu.','Na świętego Łukasza jest w domu chleb i kasza.'] },
    { d:19,  names:'Piotra z Alcantary, Jana',               p:['Idzie jesień, a tu pusta kieszeń.'] },
    { d:20,  names:'Ireny, Wencelindy',                      p:['Kiedy w październiku mrozy i zawieje, w styczniu ciepłe słonko pewnie zajaśnieje.'] },
    { d:21,  names:'Urszuli, Celiny',                        p:['Święta Urszula perły rozsuła.'] },
    { d:22,  names:'Korduli, Filipa',                        p:['Październik z burzą — zima wczesna.','Święta Urszula i Kordula dzieci do pieca przytula.'] },
    { d:23,  names:'Jana z Kapistrano, Seweryna',            p:['W jesieni prędko gdy liść z drzewa spadnie, to wkrótce zima będzie, każdy zgadnie.','Gdy październik bez mrozu — listopad skujny.'] },
    { d:24,  names:'Rafała, Antoniego',                      p:['Jaki październik, taki marzec, doznał tego niejeden starzec.'] },
    { d:25,  names:'Darii, Kryspiany',                       p:['Październik, bo paździerze baba z lnu cierlicą bierze.'] },
    { d:26,  names:'Ewarysta, Lucjana',                      p:['Październik ku końcowi — ziemia śpi.','Pierwszy śnieg w październiku, gdy na błoto pada, łagodną zimę zapowiada.'] },
    { d:27,  names:'Sabiny, Wincentego',                     p:['Jesień bezdeszczowa to zima wiatrowa.'] },
    { d:28,  names:'Szymona i Judy',                         p:['Na Szymona i Judy zima za drzwiami budzi.','Gdy Szymon mroźny — grudzień śnieżny.','Szymon i Juda — koniec jesieni wróżą.'] },
    { d:29,  names:'Zenobiusza, Felicji',                    p:['Gdy jesień zamglona, zima zaśnieżona.','Gdy październik ciepły na końcu — listopad mroźny.'] },
    { d:30,  names:'Alfonsa, Edmunda',                       p:['Październik trzydziesty — pola orać czas.','Miesiąc październy, marca obraz wierny.'] },
    { d:31,  names:'Wolfganga, Urbana',                      p:['Ostatni październik — Wszystkich Świętych za rogiem.','Halloween — noc czarownic i duchów.','Koniec października — zima coraz bliżej.'] },
  ],
  11: [
    { d:1,   names:'Wszystkich Świętych',                    p:['Na Wszystkich Świętych jeśli ciepło — listopad będzie długo siedzieć.','Wszystkich Świętych bez mrozu — Mikołaj z wiatrem do domu.','Na cmentarzu znicze płoną — pamięć trwa.'] },
    { d:2,   names:'Zaduszki, Tobiasza',                     p:['W Zaduszki dusze wracają — daj im ciepłe jedzenie.','Kiedy chmurny dzień Zaduszek — zima srogie niesie mrozki.'] },
    { d:3,   names:'Sylwii, Huberta',                        p:['Kiedy swego czasu goły las nastaje, święty Hubert z lasu cały obiad daje.'] },
    { d:4,   names:'Karola Boromeusza, Witosławy',           p:['Deszcze listopadowe budzą wiatry zimowe.'] },
    { d:5,   names:'Elżbiety, Zachariasza',                  p:['Gdy w listopadzie liść na szczytach drzew się trzyma, to w maju na nowe liście spadnie jeszcze zima.'] },
    { d:6,   names:'Leonarda, Feliksa',                      p:['W listopadzie kapusty pełne kadzie.'] },
    { d:7,   names:'Ernesta, Rufiny',                        p:['Jaka pogoda listopadowa, taka i marcowa.'] },
    { d:8,   names:'Seweryna, Klaudiusza',                   p:['Gdy łagodna jesień trzyma, będzie krótka, ostra zima.'] },
    { d:9,   names:'Teodora, Engelbertu',                    p:['W listopadzie goło w sadzie.'] },
    { d:10,  names:'Leona, Ludomiry',                        p:['Gdy w listopadzie wody się podniosą, to snadź w zimie deszcze roszą.'] },
    { d:11,  names:'Marcina',                                p:['Na świętego Marcina zima się zaczyna.','Gdy gęś na Marcina po lodzie chodzi — zima długo nie odchodzi.','Święty Marcin na białym koniu jedzie — zima za nim.'] },
    { d:12,  names:'Macieja, Niny',                          p:['Po Marcinie zima się zaostrza.','Jaka pogoda w listopadzie służy, taka na marzec się wróży.'] },
    { d:13,  names:'Stanisława Kostki, Dydaka',              p:['Na Stanisława Kostkę ujrzysz śniegu drobnostkę, a na Ofiarowanie przydadzą się sanie.'] },
    { d:14,  names:'Wawrzyńca, Emila',                       p:['Jeśli kret w listopadzie jeszcze późno ryje, na Nowy Rok komar wpadnie w bryję.'] },
    { d:15,  names:'Leopolda, Elżbiety',                     p:['Deszcz w połowie listopada, tęgi mróz w połowie stycznia zapowiada.','Połowa listopada — zima pewna.'] },
    { d:16,  names:'Edmunda, Małgorzaty',                    p:['Grzmot listopada dużo zboża zapowiada.'] },
    { d:17,  names:'Elżbiety Węgierskiej, Grzegorza',        p:['Elżbieta węgierska — charytatywna zima.','W połowie listopada deszczy, w połowie stycznia trzeszczy.'] },
    { d:18,  names:'Romana, Ody',                            p:['Gdy listopad z deszczami, grudzień zwykle z wiatrami.'] },
    { d:19,  names:'Elżbiety, Seweryna',                     p:['Na świętą Elżbietę bywa śnieg nad piętę.'] },
    { d:20,  names:'Feliksa, Rafaela',                       p:['W listopadzie mróz, szykuj w marcu wóz.'] },
    { d:21,  names:'Ofiarowania NMP, Janusza',               p:['Ofiarowanie Maryi — zima ofiarowuje mróz.','Gdy pogoda w Ofiarowanie, ostra zima nastanie.'] },
    { d:22,  names:'Cecylii, Marka',                         p:['Kiedy na świętą Cecylię grzmi, rolnik o dobry roku śni.'] },
    { d:23,  names:'Klemensa, Felicyty',                     p:['Święty Klemens zimę zaczyna, święty Piotr ją kończy.'] },
    { d:24,  names:'Jana od Krzyża, Flory',                  p:['Jan od Krzyża — zimowe ciemności.','Kwitną drzewa w listopadzie wszędzie, zima aż do maja będzie.'] },
    { d:25,  names:'Katarzyny Aleksandryjskiej, Piotra',     p:['Na Katarzynę — koła się kręcą.','Katarzyna Aleksandryjska — mądrość w zimie.'] },
    { d:26,  names:'Sylwestra, Konrada',                     p:['Jaki listopad, taki będzie marzec, prorokuje stuletni starzec.'] },
    { d:27,  names:'Waleriana, Wirgiliusza',                 p:['Gdy zbyt długo złota jesień trzyma, nagle przyjdzie zima.','Listopad ku końcowi — grudzień puka.'] },
    { d:28,  names:'Jakuba, Stefana',                        p:['Słońce listopada mrozy zapowiada.'] },
    { d:29,  names:'Saturnina, Błażeja',                     p:['Przedostatni listopad — grudzień za chwilę.','Deszcz w początku listopada, mrozy w styczniu zapowiada.'] },
    { d:30,  names:'Andrzeja',                               p:['Na świętego Andrzeja z zimą się rozmieja.','Andrzejki — wróżby miłosne i zimowe.','Lej wosk na Andrzeja — los odczytaj.'] },
  ],
  12: [
    { d:1,   names:'Eligiusza, Blanki',                      p:['Jaki pierwszy dzień miesiąca, taki będzie aż do końca.','Jak się grudzień zaczyna, taka ma być cała zima.'] },
    { d:2,   names:'Balbiny, Bibiany',                       p:['W pierwszym tygodniu grudnia pogoda stała, będzie zima długa, biała.','Gdy grudzień ciepły — styczeń mroźny.'] },
    { d:3,   names:'Franciszka Ksawerego, Luizy',            p:['Grudzień jak łagodny wszędzie, cała zima dzieckiem będzie.','Suchy grudzień stoi za to, że sucha będzie wiosna i suche lato.'] },
    { d:4,   names:'Barbary',                                p:['Święta Barbara po lodzie, Boże Narodzenie po wodzie.','Gdy Barbara z deszczem — Boże Narodzenie ze śniegiem.','Na Barbarę — mróz lub odwilż na Boże Narodzenie.'] },
    { d:5,   names:'Saby, Kryspiny',                         p:['Piąty grudzień stycznia czyni znaki.','Pogoda grudniowa — wody połowa, lodu połowa.'] },
    { d:6,   names:'Mikołaja',                               p:['Mikołaj mroźny — cały rok śnieżny.','Na Mikołaja dzieci na prezenty czekają.','Gdy Mikołaj z deszczem — Boże Narodzenie bez śniegu.'] },
    { d:7,   names:'Ambrożego, Teodory',                     p:['Święty Ambroży zimy przysporzy.','Na święty Ambroży poprawią się mrozy.'] },
    { d:8,   names:'Niepokalanego Poczęcia NMP',             p:['Na Niepokalane Poczęcie — zima w szacie białej.','Po suchym grudniu sucha wiosna bywa i pogoda we żniwa.'] },
    { d:9,   names:'Leokadii, Wiesławy',                     p:['Grudzień to miesiąc zawiły, czasem srogi, czasem miły.','Silne i częste wiatry w grudniu są wróżbą wielkich deszczów w marcu i kwietniu.'] },
    { d:10,  names:'Julii, Edwarda',                         p:['Gdy ptaki o północy latają, mroźną zimę przepowiadają.','Pogoda grudniowa — wody połowa, lodu połowa.'] },
    { d:11,  names:'Damazego, Biny',                         p:['Suchy grudzień stoi za to, że sucha będzie wiosna i suche lato.','Pogoda grudniowa — lodu połowa, wody połowa.'] },
    { d:12,  names:'Otylii, Aleksandra',                     p:['W zimie odkryte ucho, to w lecie sucho.','Dłużej świat zima ziębi, niż lato zagrzewa.'] },
    { d:13,  names:'Łucji',                                  p:['Łucja dnia przyczyni czy nocy — ciemności nie zmniejszy.','Na świętą Łucję dzień się o krok przybliży.','Po świętej Łucji dzień trwa najkrócej.'] },
    { d:14,  names:'Jana od Krzyża, Izydora',                p:['Jan od Krzyża w grudniu — mistyczna noc.','Taką pogodę Nowy Rok przynosi, jaka na Jana od Krzyża się głosi.'] },
    { d:15,  names:'Niny, Celiny',                           p:['Jak w zimie piecze, to w lecie ciecze.','Czym w grudniu większy mróz, tym do worka zboże bardziej włóż.'] },
    { d:16,  names:'Albiny, Seweryna',                       p:['Grudzień zimny, śniegiem przykryty, daje rok w zboże obfity.','Gdyby kiedy w grudniu grzmiało, wiatrów byłoby niemało.'] },
    { d:17,  names:'Łazarza, Olimpii',                       p:['W grudniu rzeki kryją lody, a lud cieszy się na Gody.','Grudzień ostro mrozi drogi, wieprze bije, drwa znosi dla zimowej trwogi.'] },
    { d:18,  names:'Bogusławy, Gracjana',                    p:['Mroźny grudzień, wiele śniegu, żyzny roczek będzie w biegu.','Gdy w grudniu śnieg pada, drugi rok taki sam zapowiada.'] },
    { d:19,  names:'Dariusza, Urbana',                       p:['Grudzień z grzmotami, rok z wiatrami.','Pogoda na Urbana, to wielka wygrana.'] },
    { d:20,  names:'Filibertu, Dominiki',                    p:['Gdy ciepło na Dominika, ostra zima nas dotyka.','Na świętego Dominika głucho wszędzie, śpiew ptactwa zanika.'] },
    { d:21,  names:'Tomasza, Honoriusza',                    p:['Na Tomasza — przesilenie zimowe.','Najkrótszy dzień roku — słońce zawraca.','Na Tomasza najdłuższa noc nasza.'] },
    { d:22,  names:'Zenona, Demetriusza',                    p:['Po przesileniu dzień przybywa.','Gdy łagodna jesień trzyma, będzie krótka, ostra zima.'] },
    { d:23,  names:'Jana Kęty, Wiktorii',                    p:['Jan Kęty grudniowy — mądrość na Boże Narodzenie.','Im więcej zimą wody, tym więcej wiosną pogody.'] },
    { d:24,  names:'Ewy, Adama',                             p:['Wigilia gwiazdkowa — gwiazda na niebie.','Gdy na Wigilię gwiazda wyraźna — rok dobry.','Na Wigilię — pierwsza gwiazda na stole.'] },
    { d:25,  names:'Narodzenia Pańskiego',                   p:['Boże Narodzenie ze śniegiem — Wielkanoc z kwieciem.','Gdy Boże Narodzenie zielone — Wielkanoc biała.','Na Boże Narodzenie słońce zaświeci — urodzajny rok.'] },
    { d:26,  names:'Szczepana, Dionizego',                   p:['Na Szczepana — zima potrząsa śniegiem.','Na świętego Szczepana bywa błoto po kolana.','Gdy na Szczepana mróz — do wiosny daleko.'] },
    { d:27,  names:'Jana, Fabioli',                          p:['Jak Jan Apostoł ośnieżony, św. Józef już zielony.','Jak Apostoł pokazuje, taki luty następuje.'] },
    { d:28,  names:'Młodzianków, Antoniny',                  p:['Na Młodzianki — błogosław dziatwy.','Niewiniątek dzień pokaże, jaka pogoda w marcu się okaże.'] },
    { d:29,  names:'Tomasza Becketa, Dawida',                p:['Zima starym dokucza, a młodych naucza.','Zima nie pyta, gdzie się lato podziało.'] },
    { d:30,  names:'Dawida, Rogera',                         p:['Kiedy grzmi na lód, będzie głód.','Grudzień trzydziesty — Sylwester jutro.'] },
    { d:31,  names:'Sylwestra',                              p:['Jak Sylwester — taki cały rok nowy.','Sylwestrowa noc jasna i gwiaździsta — rok obfity.','Na Sylwestra hałasuj — złe duchy przepędź.'] },
  ],
};
