const PROVERBS = {
  1: [
    { d:1,   names:'Mieczysławy, Seweryna',                  p:['Jak styczeń mroźny, rok będzie płodny.','Jak Nowy Rok, tak cały rok.','Jaki Nowy Rok, taki cały rok.'] },
    { d:2,   names:'Bazylego, Grzegorza',                    p:['Gdy Makary pogodny, cały styczeń chłodny.','Gdy w styczniu woda huczy, to na wiosnę mróz dokuczy.'] },
    { d:3,   names:'Genowefy, Daniela',                      p:['Gdy w styczniu mrozy i śniegi, będą stodoły po brzegi, gdy styczeń mrozów nie daje, prowadzi nieurodzaje.','Od Genowefy listopad swój bierze początek.'] },
    { d:4,   names:'Tytusa, Anieli',                         p:['Gdy w Eugeniego lód albo woda, taka i lipcowa pokaże się pogoda.','Kiedy styczeń najmroźniejszy, wtedy roczek najpłodniejszy.'] },
    { d:5,   names:'Edwarda, Szymona',                       p:['Gdy styczeń burzliwy z śniegami, lato burzliwe z deszczami.','Gdy styczeń zamglony, marzec zaśnieżony.'] },
    { d:6,   names:'Kacpra, Melchiora, Baltazara',           p:['Na Trzech Króli zima w pełni.','Gdy w Trzech Króli mrozem trzyma, będzie jeszcze długa zima.','Na Trzech Króli słońce świeci, wiosna do nas pędem leci.'] },
    { d:7,   names:'Juliana, Rajmunda',                      p:['Gdy Trzech Króli mrozem trzyma, będzie jeszcze długa zima.','Gdy w styczniu mrozy i śniegi, będą stodoły po brzegi.'] },
    { d:8,   names:'Seweryna, Marii',                        p:['Jeżeli pszczoła w styczniu z ula wylatuje, rzadko pomyślny rok nam obiecuje.','Gdy styczeń zamglony, marzec zaśnieżony.'] },
    { d:9,   names:'Marceliny, Adama',                       p:['Styczeń, styczeń, wszystko studzi — ziemię, bydło i ludzi.','Gdy styczeń jasny i biały, w lecie bywają upały.'] },
    { d:10,  names:'Wilhelma, Danuty',                       p:['Gdy w styczniu deszcz leje, złe robi nadzieje.','Gdy słońce przygrzewa na Jana Dobrego, spodziewać się można lata pogodnego.'] },
    { d:11,  names:'Honoraty, Ernesta',                      p:['Jak styczeń zachlapany, to lipiec zapłakany.','Gdy w stycznia woda huczy, to na wiosnę mróz dokuczy.'] },
    { d:12,  names:'Benedykta, Tatiany',                     p:['Kiedy w styczniu rosną trawy, lipiec dla nas niełaskawy.','Kiedy styczeń mokry trzyma, zwykle bywa długa zima.'] },
    { d:13,  names:'Bogumyły, Weroniki',                     p:['Kiedy w styczniu rośnie trawa, licha w lecie jest potrawa.','Weronika chustkę zrzuci, wiosna od nas się odwróci.'] },
    { d:14,  names:'Feliksa, Niny',                          p:['Kiedy w styczniu lato, w lecie zima za to.','Kiedy styczeń najmroźniejszy, wtedy roczek najpłodniejszy.'] },
    { d:15,  names:'Pawła, Arnolda',                         p:['Gdy w zimie nie było śniegu, to go wiele spadnie w kwietniu.','Kiedy w styczniu lato, w lecie zima za to.'] },
    { d:16,  names:'Marcelego, Waldemara',                   p:['Gdy styczeń jasny i biały, w lecie bywają upały.','Styczeń mrozem trzeszczeć musi, wtedy chłopa plon przydusi.'] },
    { d:17,  names:'Antoniego',                              p:['Jak styczeń zachlapany, to lipiec zapłakany.','Styczeń mrozem trzeszczeć musi, wtedy chłopa plon przydusi.'] },
    { d:18,  names:'Małgorzaty, Piotra',                     p:['Styczeń bywa łagodny, gdy październik śnieżny i chłodny.','Gdy na Małgorzaty mróz, jeszcze długo nie pojedzie wóz.'] },
    { d:19,  names:'Henryka, Mariusza',                      p:['Gdy styczeń z zimnem nie chodzi, marzec, kwiecień wychłodzi.','W styczniu mróz i śnieg, to lato da nam bieg.'] },
    { d:20,  names:'Fabiana, Sebastiana',                    p:['Fabian i Sebastian, gdy mróz dadzą, srogą zimę przyprowadzą.','Fabian i Sebastian pierwsi drzewa budzą, ale radzi często łudzą.','Styczniowy mróz, to zdrowia woź.'] },
    { d:21,  names:'Agnieszki',                              p:['Święta Agnieszka wypuszcza skowronka z mieszka.','Święta Agnieszka wypuszcza skowronka z mieszka.'] },
    { d:22,  names:'Anastazego, Wincentego',                 p:['Kiedy Wincenty posypie pierze, to nie ustanie aż do Gromnicznej w pierwsze pacierze.','Chociaż święty Wincenty, jednak szczypie mróz w pięty.'] },
    { d:23,  names:'Ildefonsa, Rajmunda',                    p:['W styczniu łów łatwy na kuropatwy.','Styczeń rok stary z nowym styka, czasem zimnem do kości przenika, czasem w błocie utyka.'] },
    { d:24,  names:'Felicji, Tymoteusza',                    p:['Kiedy styczeń najmroźniejszy, wtedy roczek najpłodniejszy.','Na świętego Tymoteusza trzeba ci czapki, nie kapelusza.'] },
    { d:25,  names:'Pawła, Delfiny',                         p:['Na nawrócenie Pawła dobra pogoda — rok będzie miał uroda.','Jeśli w dzień świętego Pawła słońce świeci, rok zboże zasięci.','Na świętego Pawła połowa zimy przepadła.'] },
    { d:26,  names:'Tymoteusza, Tytusa',                     p:['Kiedy styczeń najostrzejszy, tedy roczek najpłodniejszy.','Kiedy styczeń najmroźniejszy, wtedy roczek najpłodniejszy.'] },
    { d:27,  names:'Anieli, Hieronima',                      p:['Gdy w styczniu mrozy i śniegi, będą stodoły po brzegi, gdy styczeń mrozów nie daje, prowadzi nieurodzaje.','Jeżeli pszczoła w styczniu z ula wylatuje, rzadko pomyślny rok nam obiecuje.'] },
    { d:28,  names:'Tomasza z Akwinu, Walerego',             p:['Jeżeli pszczoła w styczniu z ula wylatuje, rzadko pomyślny rok nam obiecuje.','Styczeń mrozem trzeszczeć musi, wtedy chłopa plon przydusi.'] },
    { d:29,  names:'Franciszka Salezego, Zdzisławy',         p:['Jak Święta Agnieszka wypuści śnieg z mieszka, to go nie powstrzyma ani do Franciszka.','Gdy styczeń zamglony, marzec zaśnieżony.'] },
    { d:30,  names:'Martyny, Macieja',                       p:['Gdy styczeń zamglony, marzec zaśnieżony.','Na świętą Martynę przybyło dnia na godzinę.'] },
    { d:31,  names:'Marceli, Jana Bosco',                    p:['Gdy w styczniu deszcz leje, złe robi nadzieje.','Jak styczeń zachlapany, to lipiec zapłakany.'] },
  ],
  2: [
    { d:1,   names:'Brygidy, Ignacego',                      p:['Gdy mróz w lutym ostro trzyma, tedy jest niedługa zima.','Gdy bez wiatrów luty chodzi, w kwietniu wicher nie zawodzi.'] },
    { d:2,   names:'Marii, Ofiarowania Pańskiego',           p:['Na Gromniczną połowa zimy minioną.','Na Gromniczną niedźwiedź budę poprawia albo rozwala.','Gdy w Gromnicę mróz, będzie dużo zbóż.'] },
    { d:3,   names:'Błażeja, Oskara',                        p:['Święty Błażej, gardła zagrzej.','Błażej gardło leczy — mrozy też ustępują.'] },
    { d:4,   names:'Weroniki, Andrzeja',                     p:['Gdy w lutym mróz mocno trzyma, będzie krótka zima.','W lutym wody wiele - w lecie głodne nawet cielę.'] },
    { d:5,   names:'Agaty, Adelajdy',                        p:['Święta Agata w zimę bogata.','W lutym śnieg i mróz stały, w lecie będą upały.'] },
    { d:6,   names:'Doroty, Pawła',                          p:['Gdy ciepło w lutym, zimno w marcu bywa, długo trwa zima, to jest niewątpliwa.','Gdy bez wiatrów luty chodzi, w kwietniu wicher nie zawodzi.'] },
    { d:7,   names:'Ryszarda, Romualda',                     p:['Kiedy luty pofolguje, marzec zimę zreperuje.','W lutym śnieg i mróz stały, w lecie będą upały.'] },
    { d:8,   names:'Hieronima, Jana',                        p:['Kiedy luty schodzi, człek po wodzie brodzi.','Gdy w lutym odwilż — mróz w marcu powróci.'] },
    { d:9,   names:'Apolonii, Cyryla',                       p:['Na świętą Apolonię, zaprzęgaj konie.','Apolonia z mrozem — zęby bolą, ale zima zdrowa.'] },
    { d:10,  names:'Scholastyki, Wilhelma',                  p:['W lutym gdy zagrzmi od wschodniego boku, burze i wiatry walne są w tym roku.','Scholastyka – mróz utyka, zanim Walenty nam zaświeci, obaczymy, mróz kark skręci.'] },
    { d:11,  names:'Marii z Lourdes, Lucjana',               p:['W lutym wody wiele - w lecie głodne nawet cielę.','Kiedy luty puści, to marzec wypiecze.'] },
    { d:12,  names:'Eulalii, Damiana',                       p:['Gdy luty bez mrozów i nieburzliwy, rok bywa słotny i nieurodziwy.','Kiedy luty schodzi, człek po wodzie brodzi.'] },
    { d:13,  names:'Grzegorza, Agnieszki',                   p:['Gdy w lutym do połowy zima się wysili, to na koniec miesiąca już się nie wychyli.','Kiedy luty, obuj buty.'] },
    { d:14,  names:'Walentego, Cyryla',                      p:['Na świętego Walentego ptaki się kojarzą, ludzie miłością darzą.','Na świętego Walentego bywa mróz już do niczego.','Gdy na święty Walenty deszcze, mrozy wrócą jeszcze.'] },
    { d:15,  names:'Faustyny, Jowity',                       p:['Kiedy luty, obuj buty.','Luty bywa w lód okuty.'] },
    { d:16,  names:'Julianny, Danuty',                       p:['Lepiej widzieć wilka w lesie, niż furmana w lutym w polu.','Na stycznie i lute trzeba mieć konie kute.'] },
    { d:17,  names:'Aleksego, Donata',                       p:['Gdy ciepły luty, patrz jakie masz buty.','Jak w lutym rosa pada, nocne przymrozki w maju zapowiada.'] },
    { d:18,  names:'Szymona, Konstancji',                    p:['Jeśli ci jeszcze nie dokuczył luty, to pal dobrze w kominie i miej kożuch suty.','Czasem luty ostro kuty, czasem w luty same pluty.'] },
    { d:19,  names:'Arnolda, Konrada',                       p:['W Świętego Konrada, zima nie rada.','Czasem luty się zlituje, że człek niby wiosnę czuje, ale czasem tak się zżyma, że człek prawie nie wytrzyma.'] },
    { d:20,  names:'Leona, Ludomiry',                        p:['Gdy mróz w lutym ostro trzyma, tedy jest niedługa zima.','Jeśli luty śnieżny, mroźny, spodziewaj się wczesnej wiosny.'] },
    { d:21,  names:'Eleonory, Anny',                         p:['Gdy w lutym mróz mocno trzyma, będzie krótka zima.','Gdy luty z burzami, wiosna prędko z nami.'] },
    { d:22,  names:'Marty, Piotra',                          p:['Gdy mróz w lutym dwudziestym drugim, dzień straszy nas mrozem długim.','W lutym śnieg i mróz stały, w lecie będą upały.'] },
    { d:23,  names:'Romany, Damiana',                        p:['Silne wiatry przy końcu lutego, spodziewaj się zatem lata żyznego.','Jeśli luty ciepło trzyma, będzie jeszcze w marcu zima.'] },
    { d:24,  names:'Macieja, Bogusława',                     p:['Święty Maciej lód łamie, a jak nie — to zamraża.','Kiedy Gromniczna zimę traci, to Święty Maciej (24.02) ją wzbogaci.','Święty Maciej albo topi lody, albo też je robi z wody.'] },
    { d:25,  names:'Wiktora, Cezarego',                      p:['Skoro po Macieju drzewa się ogrzeją, leć do sadu, oczyść go z owadów.','Gdy ciepło w lutym, zimno w marcu bywa, długo trwa zima, to jest niewątpliwa.'] },
    { d:26,  names:'Aleksandra, Mirosławy',                  p:['Gdy bez wiatrów luty chodzi, w kwietniu wicher nie zawodzi.','Luty gdy wiatrów i mrozów nie daje, prowadzi rok słotny i nieurodzaje.'] },
    { d:27,  names:'Gabriela, Leandra',                      p:['Luty, szykuj buty, bo nadejdą deszcze, pluty.','Kiedy kot w lutym na słonku się grzeje, musi w marcu zajść na przypiecek.'] },
    { d:28,  names:'Romana, Makarego',                       p:['Kiedy w lutym tajanie, szykuj chłopie sanie.','W lutym gdy zagrzmi od wschodniego boku, burze i wiatry walne są w tym roku.'] },
  ],
  3: [
    { d:1,   names:'Albina, Antoniny',                       p:['Marzec jak zając — ucieka i wraca.','Na Świętego Albina rzadka u ludzi mina, bo post się zaczyna.'] },
    { d:2,   names:'Heleny, Karola',                         p:['Czasem i w marcu, zetnie wodę w garncu.','W marcu jak w garncu.'] },
    { d:3,   names:'Kingi, Kunegundy',                       p:['Suchy marzec, kwiecień mokry, maj przechłodny — nie będzie rok głodny.','Śnieg marcowy owocom niezdrowy.'] },
    { d:4,   names:'Kazimierza',                             p:['W dzień świętego Kazimierza zima do morza zmierza.','Na Świętego Kazimierza wyjdzie skowronek spod perza.','Na świętego Kazimierza pełno już młodego zwierza.'] },
    { d:5,   names:'Fryderyka, Adriana',                     p:['Co marzec wypiecze, to kwiecień wysiecze.','Czasami w marcu zetnie wodę w garncu.'] },
    { d:6,   names:'Róży, Wiktora',                          p:['Kiedy w marcu deszczu wiele, nieurodzaj zboża ściele.','W marcu, gdy są grzmoty, urośnie zboże ponad płoty.'] },
    { d:7,   names:'Tomasza, Felicyty',                      p:['W marcu, gdy grzmot na lody spada, w lecie grad zapowiada.','Czasem marzec tak się podsadzi, że dwa kożuchy oblec nie zawadzi.'] },
    { d:8,   names:'Marii, Jana',                            p:['Marzec - figlarzec, przeplata, trochę zimy, trochę lata.','Ile w marcu dni mglistych, tyle w żniwa dni dżdżystych.'] },
    { d:9,   names:'Franciszki, Dominika',                   p:['Co marzec wypiecze, to kwiecień wysiecze.','Gdy Franciszka z wichrem po polu hasa, może sypnąć śniegiem powyżej pasa.'] },
    { d:10,  names:'Aleksandra, Maksa',                      p:['Gdy mróz w marcu dnia dziesiątego, jeszcze czterdzieści dni mrozu takiego.','Ile razy marzec mgłą uraczy, tyle niepogody w lecie znaczy.'] },
    { d:11,  names:'Benedykta, Rozalii',                     p:['Kiedy w marcu deszczu wiele, nieurodzaj zboża ściele.','Marzec uparty stroi z pługiem żarty.'] },
    { d:12,  names:'Grzegorza',                              p:['Na świętego Grzegorza idzie zima do morza.','Na Św. Grzegorza idzie zima do morza.','Na świętego Grzegorza, idzie zima do morza.'] },
    { d:13,  names:'Bożeny, Krystyny',                       p:['Każdy gospodarz zasiewa pierwszy groch na marca, aby też próżnego nie miał na ognicku garnca.','W marcu, gdy są grzmoty, urośnie zboże ponad płoty.'] },
    { d:14,  names:'Leontyny, Matyldy',                      p:['Gdy w marcu deszcz pada, wtedy rolnik biada, gdy słońce jaśnieje, to rolnik się śmieje.','Gdy suchy marzec, a maj mokry bywa, żyznego roku oracz się spodziewa.'] },
    { d:15,  names:'Klemensa, Longina',                      p:['Marzec, co z deszczem chadza, mokry czerwiec sprowadza.','Gdy w marcu deszcz pada, wtedy rolnik biada, gdy słonko jaśnieje, to rolnik się śmieje.'] },
    { d:16,  names:'Izabeli, Bonifacego',                    p:['Słońce marcowe, owocom niezdrowe.','Hilary zapowiada, jaka pogoda na Wielkanoc przypada.'] },
    { d:17,  names:'Patryka, Zbigniewa',                     p:['Gdy na Gertrudy zjawią się bociany, to wiosna już rychło nastanie.','Marzec zielony - niedobre plony.'] },
    { d:18,  names:'Cyryla, Edwarda',                        p:['Suchy marzec, kwiecień mokry, maj przechłodny - nie będzie rok głodny.','Na świętego Edwarda zimy pogarda.'] },
    { d:19,  names:'Józefa',                                 p:['Na świętego Józefa pięknie, zima prędko pęknie.','Na świętego Józefa sadzonki w ziemię wkładaj, bo dobry owoc w sadzie będziesz miał.','Przyjdzie święty Józef z pomocą, porówna dzień z nocą.'] },
    { d:20,  names:'Aleksandra, Klaudii',                    p:['Równonoc wiosenna — dzień z nocą w parze.','Od dnia dwudziestego marca zagrzewa słońce nawet starca.'] },
    { d:21,  names:'Benedykta, Nikifora',                    p:['Suchy marzec, mokry maj, będzie żytko jako gaj.','Jedna jaskółka nie przynosi wiosny.'] },
    { d:22,  names:'Kazimiry, Eugenii',                      p:['Jeżeli w pierwszy dzień po przesileniu marcowym burza się zdarzy, zima już nie przydarzy.','W marcu jak w garncu.'] },
    { d:23,  names:'Pelagii, Feliksa',                       p:['W marcu, gdy są grzmoty, urośnie zboże ponad płoty.','Marzec zimny i słoneczny, plon zaręcza dostateczny.'] },
    { d:24,  names:'Marka, Gabriela',                        p:['Marzec, czy słoneczny, czy płaczliwy, listopad obraz żywy.','Na Świętego Szymona nie wdziewaj już kaftana.'] },
    { d:25,  names:'Marii, Zwiastowania',                    p:['Na Zwiastowanie bocian do domu wita — wiosna jak złoto.','Na Zwiastowanie kto nie sieje, przez lato popłakuje.','Na Zwiastowanie bocian na gnieździe stanie.'] },
    { d:26,  names:'Larysy, Emanueli',                       p:['Marzec, czy słoneczny, czy płaczliwy, listopada obraz żywy.','Marzec odmienia wiatry, deszcz miesza z pogodą, więc nie dziw, jeśli starzy czują go ze szkodą.'] },
    { d:27,  names:'Ernesta, Jana',                          p:['W marcu jak w garncu.','Gdy w Ruperta niebo jasne będzie, w lipcu takiż czas pogody wszędzie.'] },
    { d:28,  names:'Anieli, Sykstusa',                       p:['Co marzec wypiecze, to kwiecień wysiecze.','Czasami w marcu zetnie wodę w garncu.'] },
    { d:29,  names:'Wiktoryna, Helmuta',                     p:['Ile mgieł w marcu, tyle deszczów w czerwcu.','Co marzec wypiecze, to kwiecień wysiecze.'] },
    { d:30,  names:'Amelii, Leonarda',                       p:['Czasem marzec tak się podsadzi, że dwa kożuchy oblec nie zawadzi.','Ile w marcu dni mglistych, tyle w żniwa dni dżdżystych.'] },
    { d:31,  names:'Beniamina, Guida',                       p:['Nie siejesz grochu w marcu, nie masz go w garncu.','Po niestatecznym marcu świat się cieszy majem.'] },
  ],
  4: [
    { d:1,   names:'Hugona, Ireny',                          p:['Kwiecień plecień — bo przeplata trochę zimy, trochę lata.','Kwiecień, plecień, bo przeplata, trochę zimy, trochę lata.','Kiedy w kwietniu słonko grzeje, wtedy chłop nie zubożeje.'] },
    { d:2,   names:'Franciszka, Urszuli',                    p:['Ciepły kwiecień, mokry maj, będzie żytko jako gaj.','Pogody kwietniowe - słoty majowe.'] },
    { d:3,   names:'Ryszarda, Ireny',                        p:['Przyjdzie kwiecień, ostatki z gumna wymieciem.','Deszcze częste w kwietniu wróżą, że owoców będzie dużo.'] },
    { d:4,   names:'Izydora, Benedykta',                     p:['Na świętego Izydora – dla bocianów pora.','Suchy marzec, maj nie chłodny, kwiecień mokry, rok nie głodny.'] },
    { d:5,   names:'Ireny, Wincentego',                      p:['Gdyby w kwietniu nie padało, to owoców będzie mało.','Kwiecień co deszczem rosi, wiele owoców przynosi.'] },
    { d:6,   names:'Celestyna, Wilhelma',                    p:['Jak przygrzeje słonko, przejdzie kwiecień łąką.','Deszcze częste w kwietniu wróżą, że owoców będzie dużo.'] },
    { d:7,   names:'Jana, Rufina',                           p:['Na świętego Donata idź po pracę do brata.','Choć i w kwietniu słonko grzeje, nieraz pole śnieg zawieje.'] },
    { d:8,   names:'Cezarego, Dionizego',                    p:['Kwiecień-plecień, bo przeplata, trochę zimy, trochę lata.','Jeśli w kwietniu pszczoły latają, to długie chłody się zapowiadają.'] },
    { d:9,   names:'Marii, Waltruda',                        p:['Kwiecień, plecień, bo przeplata, trochę zimy, trochę lata.','Deszcze częste w kwietniu wróżą, że owoców będzie dużo.'] },
    { d:10,  names:'Michała, Makarego',                      p:['Kiedy w kwietniu słonko grzeje, wtedy chłop nie zubożeje.','Gdyby w kwietniu nie padało, to owoców będzie mało.'] },
    { d:11,  names:'Leona, Filipa',                          p:['Kwiecień, co deszczem rosi, wiele owoców przynosi.','Kiedy w kwietniu słonko grzeje, wtedy chłop nie zubożeje.'] },
    { d:12,  names:'Juliusza, Zenona',                       p:['Ciepły kwiecień, mokry maj, będzie żytko jako gaj.','Pogody kwietniowe - słoty majowe.'] },
    { d:13,  names:'Przemysława, Hermenegilda',              p:['Kwiecień co deszczem rosi, wiele owoców przynosi.','Deszcze częste w kwietniu wróżą, że owoców będzie dużo.'] },
    { d:14,  names:'Waleriana, Justyny',                     p:['Gdyby w kwietniu nie padało, to owoców będzie mało.','Jak przygrzeje słonko, przejdzie kwiecień łąką.'] },
    { d:15,  names:'Anastazji, Wacława',                     p:['Kwiecień co deszczem rosi, wiele owoców przynosi.','Jak przygrzeje słonko, przejdzie kwiecień łąką.'] },
    { d:16,  names:'Benedykta, Bernadety',                   p:['Choć i w kwietniu słonko grzeje, nieraz pole śnieg zawieje.','Choć i w kwietniu słonko grzeje, nieraz pole śnieg zawieje.'] },
    { d:17,  names:'Roberta, Rudolfa',                       p:['Jeśli w kwietniu pszczoły latają, to długie chłody się zapowiadają.','Jeśli w kwietniu pszczoły latają, to długie chłody się zapowiadają.'] },
    { d:18,  names:'Bogumiły, Apoloniusza',                  p:['Kwiecień, plecień, bo przeplata, trochę zimy, trochę lata.','Mokre dni kwietnia zazwyczaj wróżą, że w lecie będzie owoców dużo.'] },
    { d:19,  names:'Tymona, Adolfa',                         p:['Ciepły kwiecień, mokry maj – będzie zboże jako gaj.','Kiedy w kwietniu słonko grzeje, wtedy chłop nie zubożeje.'] },
    { d:20,  names:'Agnieszki, Czesława',                    p:['Ciepły kwiecień, mokry maj, będzie żytko jako gaj.','Pogody kwietniowe — słoty majowe.'] },
    { d:21,  names:'Anzelma, Feliksa',                       p:['Kwiecień z ciepłem po dwudziestym — maj pracowity.','Anzelm z deszczem — maj zielony.'] },
    { d:22,  names:'Łukasza, Kai',                           p:['Pogody kwietniowe - słoty majowe.','Deszcze częste w kwietniu wróżą, że owoców będzie dużo.'] },
    { d:23,  names:'Wojciecha',                              p:['Kiedy grzmi na Wojciecha, rośnie w polu pociecha.','Gdy Wojciech mroźny, owoc tego roku będzie kosztowny.','Wojciech z słońcem — żyto się obiecuje.'] },
    { d:24,  names:'Horacego, Jerzego',                      p:['Jerzy na koniu — zima pobita.','Na świętego Jerzego wąż z dziury wychodzi.'] },
    { d:25,  names:'Marka, Jarosława',                       p:['Na Marka — słońce grzeje mocniej.','Gdyby w kwietniu nie padało, to owoców będzie mało.'] },
    { d:26,  names:'Marzeny, Klety',                         p:['Kwiecień ku końcowi — pszczoły w kwiatach.','Kwiecień co deszczem rosi, wiele owoców przynosi.'] },
    { d:27,  names:'Zyty, Teofila',                          p:['Jak przygrzeje słonko, przejdzie kwiecień łąką.','Kwiecień na końcu — sprawdź drzewa owocowe.'] },
    { d:28,  names:'Witalisa, Piotra',                       p:['Choć i w kwietniu słonko grzeje, nieraz pole śnieg zawieje.','Kwiecień ostatni — siej co możesz.'] },
    { d:29,  names:'Katarzyny ze Sieny, Roberty',            p:['Jeśli w kwietniu pszczoły latają, to długie chłody się zapowiadają.','Kwiecień, plecień, bo przeplata, trochę zimy, trochę lata.'] },
    { d:30,  names:'Katarzyny, Mariana',                     p:['Kwiecień bez deszczu — w stodole cicho.','Kiedy w kwietniu słonko grzeje, wtedy chłop nie zubożeje.','Ostatni kwiecień — maj za drzwiami.'] },
  ],
  5: [
    { d:1,   names:'Józefa Robotnika, Filipa',               p:['Maj chłodny i deszczowy — rok urodzajny.','Chłodny maj, dobry urodzaj.','Majowe deszcze — złoto dla pól.'] },
    { d:2,   names:'Zygmunta, Atanazego',                    p:['Chłodny maj, dobry urodzaj.','Gdy maj z deszczem na początku — sierpień obfity.'] },
    { d:3,   names:'Marii, Antoniny',                        p:['Ciepły kwiecień, mokry maj - będzie zboże jako gaj.','Częste w maju grzmoty rozpraszają chłopom zgryzoty.'] },
    { d:4,   names:'Floriana, Moniki',                       p:['Florian ognie gasi — deszcze przywołuje.','Na Floriana deszcz pada — pożary nie grożą.'] },
    { d:5,   names:'Ireny, Waldemara',                       p:['Deszcz majowy, chleb gotowy.','Deszcz majowy, chleb gotowy.'] },
    { d:6,   names:'Jana, Judyty',                           p:['Kiedy mokry maj, będzie żyto jako gaj.','Gdy w maju mgły poranne — upał w południe.'] },
    { d:7,   names:'Stanisława, Gizeli',                     p:['Na świętego Stanisława lato się przedstawia.','Kiedy mokry maj, będzie żyto jako gaj.'] },
    { d:8,   names:'Stanisława Biskupa, Wiktora',            p:['Dużo chrabąszczy w maju, proso będzie niby w gaju.','Gdy maj grzmi — sierpień gorący.'] },
    { d:9,   names:'Grzegorza, Bożeny',                      p:['Gdy maj jest przy pogodzie, nie bywają siana w szkodzie.'] },
    { d:10,  names:'Izydora, Antoniego',                     p:['Izydor rolnik — patron dobrych zbiorów.','Na Izydora zasiewaj najpóźniej.'] },
    { d:11,  names:'Filipa, Ignacego',                       p:['Grzmot w maju nie szkodzi, sad dobrze obrodzi.'] },
    { d:12,  names:'Pankracego, Dominika',                   p:['Pankracy mróz przynosi — strzeż sadzone.','Zimni Ogrodnicy: Pankracy, Serwacy, Bonifacy — trzy mroźne dni.'] },
    { d:13,  names:'Serwacego, Natalii',                     p:['Serwacy mroźny — drzewa owocowe cierpią.','Gdy Serwacy bez mrozu — lato gorące.'] },
    { d:14,  names:'Bonifacego, Korony',                     p:['Bonifacy z lodem — ogrodnicy płaczą.','Po Bonifacym mróz nie wraca.'] },
    { d:15,  names:'Zofii, Izydora',                         p:['Pankracy, Serwacy i Bonifacy dla drzew wielcy niedobracy.','Przed Pankracym nie ma lata, po Bonifacym mróz ulata.','Po Zimnej Zofii — mróz odpuszcza.'] },
    { d:16,  names:'Andrzeja Boboli, Jana',                  p:['Po zimnych ogrodnikach — ciepło pewne.','Jeśli w maju grzmot, rośnie wszystko w lot.'] },
    { d:17,  names:'Paschalisa, Sławomira',                  p:['Kiedy lipa w maju kwitnie, to w ulach miód zawiśnie.'] },
    { d:18,  names:'Eryka, Jana',                            p:['Gdy kukułka kuka w maju, spodziewaj się urodzaju.','Dużo chrabąszczy w maju, proso będzie niby w gaju.'] },
    { d:19,  names:'Piotra, Ivo',                            p:['Gdy kukułka kuka w maju, spodziewaj się urodzaju.'] },
    { d:20,  names:'Antoniny, Bernardyna',                   p:['Gdy maj jest przy pogodzie, nie bywają siana w szkodzie.','Gdy się maj z grzmotem odezwie na wschodzie, rok sprzyja sianu i zbożu.'] },
    { d:21,  names:'Wiktora, Tymoteusza',                    p:['Gdy się maj z grzmotem odezwie na wschodzie, rok sprzyja sianu i zbożu w urodzie.','Maj ciepły po dwudziestym — dobrze wróży.'] },
    { d:22,  names:'Romy, Julii',                            p:['Grzmot w maju nie szkodzi, sad dobrze obrodzi.','Maj bogaty sieje kwiaty.'] },
    { d:23,  names:'Dezyderego, Iwony',                      p:['Grzmot w maju sprzyja urodzaju.','Maj na końcu — lato się zbliża.'] },
    { d:24,  names:'Joanny, Zuzanny',                        p:['Majowe błoto, więcej niż złoto.'] },
    { d:25,  names:'Grzegorza VII, Urbana',                  p:['Na świętego Urbana dobre wino w beczułce schowane.','Jeśli Urban z deszczem, wino kwaśne do pieśni.','Urban słoneczny — winnica obiecuje.'] },
    { d:26,  names:'Filipa Neri, Eweliny',                   p:['Jeśli w maju grzmot, rośnie wszystko w lot.','Częste w maju grzmoty rozpraszają chłopom zgryzoty.'] },
    { d:27,  names:'Augustyna, Jana',                        p:['Maj — bydłu daj, a sam za piec uciekaj.','Maj na końcu zbiera siły do lata.'] },
    { d:28,  names:'Germana, Jarosława',                     p:['Chłodny maj, dobry urodzaj.','Kiedy lipa w maju kwitnie, to w ulach miód zawiśnie.'] },
    { d:29,  names:'Maksymiliana, Magdaleny',                p:['Deszcz majowy, chleb gotowy.'] },
    { d:30,  names:'Ferdynanda, Joanny',                     p:['Kiedy mokry maj, będzie żyto jako gaj.','Na pierwszego maja szron obiecuje dobry plon.'] },
    { d:31,  names:'Anieli, Petroneli',                      p:['Pierwszego maja deszcz, nieurodzaju wieszcz.','Gdy maj jest przy pogodzie, nie bywają siana w szkodzie.','Na końcu maja — liczy się żyto.'] },
  ],
  6: [
    { d:1,   names:'Justyny, Nikodema',                      p:['Czerwiec daje dni gorące, kosa brzęczy już na łące.','Czerwiec deszczowy — sierpień gorący.'] },
    { d:2,   names:'Marceliny, Erazma',                      p:['Czerwiec daje dni gorące, kosa brzęczy już na łące.','Czerwiec stały, grudzień doskonały.'] },
    { d:3,   names:'Klotyldy, Karola',                       p:['Czerwiec stały, grudzień doskonały.'] },
    { d:4,   names:'Franciszka, Kwiryna',                    p:['Gdy czerwiec chłodem i wodą szafuje, to zwykle rok cały popsuje.','Gdy czerwiec z burzą na początku — lato gorące.'] },
    { d:5,   names:'Bonifacego, Walburgi',                   p:['Czerwiec na maju zwykle się wzoruje, jego pluchy, pogody, często naśladuje.'] },
    { d:6,   names:'Norberta, Filipa',                       p:['Siej na świętego Norberta, będzie jęczmienia sterta.'] },
    { d:7,   names:'Roberta, Wiesławy',                      p:['Norbert, Robert, Medard to bracia młodzi, spodziewajcie się powodzi.'] },
    { d:8,   names:'Medarda',                                p:['Medard deszczem obdarzył — czterdzieści dni deszczem straszył.','Na Medarda jak pada — przez czterdzieści dni nie ustaje woda.','Medard suchy — czterdzieści dni bez deszczu.'] },
    { d:9,   names:'Diany, Felicjana',                       p:['Po Medardzie czterdzieści dni niezmienne.','Kiedy kwitnie w czerwcu bób, to największy wtedy głód, a kiedy mak, to już nie tak.'] },
    { d:10,  names:'Bogumiła, Małgorzaty',                   p:['Gdy czerwiec chłodem i wodą szafuje, to zwykle rok cały popsuje.','Od czerwca dużo zależy, czy żniwa będą jak należy.'] },
    { d:11,  names:'Barnaby, Jana',                          p:['Na świętego Barnabę idź kosić trawę.'] },
    { d:12,  names:'Jana, Onufrego',                         p:['Na św. Onufry otwierajcie kufry.'] },
    { d:13,  names:'Antoniego z Padwy',                      p:['Antoni z Padwy — kto zguby szuka, znajdzie.','Na Antoniego deszcz pada — zboże pełne wody.'] },
    { d:14,  names:'Walerego, Michała',                      p:['Pełnia czerwcowa — burza gotowa.'] },
    { d:15,  names:'Wita, Modesta',                          p:['Gdy przychodzi Witus suchy, tedy wiedzie z sobą muchy.','Na świętego Wita zboże zakwita.','Czerwiec na maju zwykle się wzoruje, jego pluchy, pogody, często naśladuje.'] },
    { d:16,  names:'Benona, Aliny',                          p:['W czerwcu grusze kwiat zrzucają, czereśnie się zapalają.','Kiedy kwitnie w czerwcu bób, to największy wtedy głód, a kiedy mak, to już nie tak.'] },
    { d:17,  names:'Laury, Marcjalisa',                      p:['W czerwcu się okaże, co nam Bóg da w darze.'] },
    { d:18,  names:'Marka, Elżbiety',                        p:['Nie trzeba w czerwcu o deszcz prosić, przyjdzie jak zaczniemy kosić.'] },
    { d:19,  names:'Gerwazego, Protazego',                   p:['Od czerwca dużo zależy, czy żniwa będą jak należy.','Na świętego Gerwazego jest w ogrodzie coś pięknego.'] },
    { d:20,  names:'Bogny, Rafaela',                         p:['Grzmoty czerwca rozweselają rolnikom serca.'] },
    { d:21,  names:'Alojzego, Rudolfa',                      p:['Na Alojzego — dzień najdłuższy.','Letnie przesilenie — słońce na szczycie.'] },
    { d:22,  names:'Pauliny, Jana',                          p:['Po przesileniu dzień zaczyna wracać.','Czerwiec zimny i wilgotny, całemu roku bardzo psotny.'] },
    { d:23,  names:'Wandy, Józefa',                          p:['Gdzie sobótki palą, tam grady nie przeszkadzają.','Na Sobótkę dziewczęta kwiatami się ozdabiają.'] },
    { d:24,  names:'Jana Chrzciciela',                       p:['Na Jana Chrzciciela słońce nad ziemią miga — urodzaj nie ucieka.','Gdy na świętego Jana rzeka wzbiera — rok w polu obfity.','Na Jana kąp się w rzece, zdrowie do ciała płynie.'] },
    { d:25,  names:'Łucji, Wilhelma',                        p:['Chrzest Jana w deszczowej wodzie, trzyma zbiory na przeszkodzie.','Czerwiec gdy zagrzmi, gdzie zorze zachodzą, ryby się obficie zrodzą.'] },
    { d:26,  names:'Jana, Dawida',                           p:['W czerwcu pełnia sprowadza burze, ostatnia kwadra zaś deszcze duże.'] },
    { d:27,  names:'Cyryla, Władysława',                     p:['Pełnia czerwcowa - burza gotowa.','Czerwiec się czerwieni, będzie dość w kieszeni.'] },
    { d:28,  names:'Leona, Anny',                            p:['Czerwiec daje dni gorące, kosa brzęczy już na łące.','Czerwiec ku końcowi — żniwa za miesiąc.'] },
    { d:29,  names:'Piotra i Pawła',                         p:['Na Piotra i Pawła żyto w głowę wchodzi — kto nie wierzy, na pole idzie.','Od Piotra i Pawła — żyto do kosy się kłania.','Gdy Piotr i Paweł słoneczni — zboże złote.'] },
    { d:30,  names:'Ottona, Emilii',                         p:['W czerwcu grusze kwiat zrzucają, czereśnie się zapalają.','Czerwiec koniec — lato w sile.'] },
  ],
  7: [
    { d:1,   names:'Mariana, Haliny',                        p:['Lipiec skwarny — rok owocny.','Deszcz lipcowy rolnikowi nie drogowy.','Lipcowe upały, wrzesień doskonały.'] },
    { d:2,   names:'Marii z Góry Karmel, Ottona',            p:['Lipiec deszczowy — sierpień suchy.','Gdy lipiec mglisty — jesień piękna.'] },
    { d:3,   names:'Tomasza, Jacka',                         p:['Gdy w lipcu słońce dopieka, burza niedaleka.'] },
    { d:4,   names:'Elżbiety, Zygmunta',                     p:['Gdy się grzmot w lipcu od południa poda, drzewom się znaczy szwank i nieuroda.'] },
    { d:5,   names:'Karoliny, Antoniego',                    p:['Jeśli upały w sianokosy i żniwa, to zima ostra i dokuczliwa, a jeżeli słota, to w zimie dużo błota.'] },
    { d:6,   names:'Dominiki, Gotarda',                      p:['Kto w lipcu patrzy chłodu, nacierpi się w zimie głodu.','Gdy lipiec z burzami — sierpień spokojny.'] },
    { d:7,   names:'Klaudii, Cyryla',                        p:['Kwiat lipcowy, napój zdrowy.'] },
    { d:8,   names:'Elżbiety, Eugeniusza',                   p:['Lipcowe deszcze dla chłopa kleszcze; jak pogoda, większa swoboda.'] },
    { d:9,   names:'Weroniki, Zenona',                       p:['Gdy się pająk w lipcu przechodzi, ze sobą deszcz przywodzi, gdy swą pajęczynę psuje, bliską burzę czuje.'] },
    { d:10,  names:'Wawrzyńca, Rufiny',                      p:['Lipcowe upały, wrzesień doskonały.'] },
    { d:11,  names:'Benedykta, Olgi',                        p:['W lipcu upały, styczeń mroźny cały.'] },
    { d:12,  names:'Jana Gwalberta, Brunona',                p:['Lipiec — ostatek chleba wypiec.'] },
    { d:13,  names:'Henryka, Sary',                          p:['Miesiąc lipiec musi przypiec i ostatki mąki wypiec.'] },
    { d:14,  names:'Kamila, Bonawentury',                    p:['Upały lipcowe, mrozy styczniowe.'] },
    { d:15,  names:'Henryka, Włodzimierza',                  p:['W lipcu upały, styczeń mroźny cały.','W lipcu pszczeli rój, nie opłaci trudu znój.'] },
    { d:16,  names:'Marii z Góry Karmel, Euzebiusza',        p:['Upały lipcowe, mrozy styczniowe.','W lipcu gdy służą pogody, bój się wielkiej wody.'] },
    { d:17,  names:'Aleksego, Andrzeja',                     p:['Gdy lipiec z deszczem, zima będzie z wiatrem.'] },
    { d:18,  names:'Sławy, Szymona',                         p:['Jeżeli w żniwa mysz w polu gniazdo wysoko zakłada, znak to, że zima srogie śniegi zapowiada.'] },
    { d:19,  names:'Wincentego, Wiesławy',                   p:['Czego lipiec nie dowarzy, tego sierpień nie dosmaży.'] },
    { d:20,  names:'Eliasza, Czesławy',                      p:['Na Eliasza burze i pioruny — rolnicy się kłaniają.','Eliasz deszczem albo suszą rządzi.','Gdy Eliasz grzmi — lato żar wyda.'] },
    { d:21,  names:'Daniela, Wawrzyńca',                     p:['Kiedy lipiec daje deszcze, długie lato będzie jeszcze.'] },
    { d:22,  names:'Marii Magdaleny',                        p:['Maria Magdalena z deszczem — grzyby po deszczu.','Na Magdaleny deszcz pada — urodzaj wróży.'] },
    { d:23,  names:'Brygidy, Apolinarego',                   p:['Jak poranek mglisty, wieczór przezroczysty.'] },
    { d:24,  names:'Kingi, Jadwigi',                         p:['Czego lipiec i sierpień nie dowarzy, tego wrzesień nie usmaży.'] },
    { d:25,  names:'Jakuba',                                 p:['Na świętego Jakuba zbierać czas grzyba.','Na Jakuba deszcz, złych żniw wieszcz.','Na święty Jakub chleba sobie nakup.'] },
    { d:26,  names:'Anny, Joachima',                         p:['Na Annę — babcie zbierają zioła.','Święta Anka pasie baranka.'] },
    { d:27,  names:'Natalii, Lilii',                         p:['Gdy w lipcu słońce dopieka, burza niedaleka.'] },
    { d:28,  names:'Innocentego, Wiktora',                   p:['Gdy się grzmot w lipcu od południa poda, drzewom się znaczy szwank i nieuroda.','Lipiec ku końcowi — żniwa zaczynają.'] },
    { d:29,  names:'Marty, Olgi',                            p:['Około dnia świętej Marty, ze żniwami już nie żarty.','Na Martę — gospodyni zbiera pierwsze żniwa.'] },
    { d:30,  names:'Piotra, Julity',                         p:['Jak po lipcu gorącym sierpień się ochłodzi, to później zima z wielkim śniegiem chodzi.','Miesiąc lipiec musi przypiec i ostatki mąki wypiec.'] },
    { d:31,  names:'Ignacego Loyoli, Fabiana',               p:['Gdy lipiec z deszczem, zima będzie z wiatrem.','Jeśli upały w sianokosy i żniwa, to zima ostra i dokuczliwa, a jeżeli słota, to w zimie dużo błota.','Koniec lipca — żniwa w pełni.'] },
  ],
  8: [
    { d:1,   names:'Alfonsa, Piotra',                        p:['W pierwszym tygodniu pogoda stała, będzie zima długa, biała.','Jeśli w sierpniu dni jasne, będą stodoły ciasne.','Kiedy sierpień przychodzi, reszta zboża z pola schodzi.'] },
    { d:2,   names:'Gustawa, Euzebiusza',                    p:['Na święty Gustaw kopy w polu ustaw.'] },
    { d:3,   names:'Nikodema, Lidii',                        p:['Pogoda na Nikodema — cały miesiąc deszczu nie ma.'] },
    { d:4,   names:'Jana Vianneya, Dominika',                p:['Gdy ciepło na Dominika, ostra zima nas dotyka.'] },
    { d:5,   names:'Marii, Kasjana',                         p:['Gdy w dni sierpnia spieka wszędzie, tedy długa zima będzie.','Gdy sierpień deszczowy — jesień długa.'] },
    { d:6,   names:'Jakuba, Sławy',                          p:['W Przemienienie Pańskie są burze szatańskie.'] },
    { d:7,   names:'Kajetana, Donata',                       p:['Święty Kajetanie, strzeż od deszczu sprzątanie.'] },
    { d:8,   names:'Dominika, Cyriaka',                      p:['Kiedy sierpień przychodzi, reszta zboża z pola schodzi.','Gdy sierpień pogodny — wrzesień spokojny.'] },
    { d:9,   names:'Romana, Teresy',                         p:['Czego sierpień nie dowarzy, tego wrzesień nie doparzy.'] },
    { d:10,  names:'Wawrzyńca',                              p:['Na świętego Wawrzyńca słońce pali, zboże w polu się wali.','Wawrzyniec słońcem pali — żniwa w polu się gonią.','Na Wawrzyńca — noc spadających gwiazd.'] },
    { d:11,  names:'Zuzanny, Klary',                         p:['Od świętej Klary są już ładne dary.'] },
    { d:12,  names:'Hilarii, Leszka',                        p:['Gdy w sierpniu z północy dmucha, następuje zwykle posucha.'] },
    { d:13,  names:'Hipolita, Poncjana',                     p:['Jeżeli w sierpniu gorąco będzie, to zima w śniegi długo zasiędzie.','Gdy sierpień na Hipolita suchy — wrzesień mokry.'] },
    { d:14,  names:'Maksymiliana, Eberharda',                p:['Wigilia Wniebowzięcia — kwiaty do kościoła.','Początki sierpnia pogodne, wróżą zimy łagodne.'] },
    { d:15,  names:'Wniebowzięcia NMP',                      p:['Na Wniebowzięcie Maryi zboże w stodole się leży.','Gdy na Matkę Boską Zielną deszcz pada — jesień mokra nadciąga.','Na Zielną — zioła poświęcone w ręku.'] },
    { d:16,  names:'Rocha, Stefana',                         p:['Na święty Roch w stodole groch.'] },
    { d:17,  names:'Jacka, Bertolda',                        p:['Jeśli w dniu Jacka nie pada, suchą jesień zapowiada.'] },
    { d:18,  names:'Heleny, Klary',                          p:['Żołędzie pełne i białe, przyszłe lato doskonałe.'] },
    { d:19,  names:'Jana Eudes, Magnusa',                    p:['Kiedy sierpień wrzos rozwija, jesień krótka, szybko mija.'] },
    { d:20,  names:'Bernarda, Sławy',                        p:['Jeśli na Bernarda ziemia twarda, to będzie zima harda, a jak miękka to lekka.'] },
    { d:21,  names:'Piusa X, Joanny',                        p:['Jeśli piękny sierpień, gotuj sobie chłopku kieszeń.'] },
    { d:22,  names:'Marii, Tymoteusza',                      p:['Jeśli w sierpniu dni jasne, będą stodoły ciasne.'] },
    { d:23,  names:'Róży z Limy, Filipa',                    p:['W sierpniu grzmotów wiele, mokrą zimę ściele.'] },
    { d:24,  names:'Bartłomieja',                            p:['Na świętego Bartłomieja dobre żniwa do koleja.','Bartłomiej lato zamknie — jesień nadciąga.','Bartłomiej z mgłą — zima wczesna.'] },
    { d:25,  names:'Ludwika, Józefy',                        p:['Gdy sierpień w upały zbywa, lato długie zwykle bywa.'] },
    { d:26,  names:'Marii Częstochowskiej, Irydy',           p:['Czego sierpień nie dowarzy, tego wrzesień nie doparzy.','W sierpniu mgły w górach — mroźne Gody, kiedy mgły w dolinach — to wróżba pogody.'] },
    { d:27,  names:'Józefa Kalasancjusza, Moniki',           p:['Gdy w dni sierpnia spieka wszędzie, tedy długa zima będzie.','Kto latem pracuje, zimą głodu nie czuje.'] },
    { d:28,  names:'Augustyna, Wiliama',                     p:['Sierpień pogodny jest dla winogron wygodny.'] },
    { d:29,  names:'Sabiny, Jana',                           p:['Dużo grzybów sierpniowych, dużo zawiei śniegowych.','Początki sierpnia pogodne, wróżą zimy łagodne.'] },
    { d:30,  names:'Róży, Feliksa',                          p:['Jak po lipcu sierpień się ochłodzi, to później zima twarda z wielkim śniegiem chodzi.','W sierpniu grzmotów wiele, mokrą zimę ściele.'] },
    { d:31,  names:'Rajmunda, Aidy',                         p:['Ostatni sierpień — lato żegna się.','Ostatni sierpnia zapowiada, jaka pogoda na wrzesień wypada.','Kiedy sierpień wrzos rozwija, jesień krótka, szybko mija.'] },
  ],
  9: [
    { d:1,   names:'Idziego, Bronisławy',                    p:['Święty Idzi wiedzie wrzesień, wnet nadejdzie dżdżysta jesień.'] },
    { d:2,   names:'Stefana, Ingrydy',                       p:['Wrzesień z deszczem — październik suchy.','Gdy wrzesień ciepły — październik mroźny.'] },
    { d:3,   names:'Grzegorza Wielkiego, Danuty',            p:['Wrzeszczy wrzesień, że już jesień.'] },
    { d:4,   names:'Rozalii, Irydy',                         p:['Gdy nadejdzie wrzesień, rolnik ma zawsze pełną kieszeń.'] },
    { d:5,   names:'Doroty, Wawrzyńca',                      p:['Gdy wrzesień bez deszczów będzie, w zimie wiatrów pełno wszędzie.'] },
    { d:6,   names:'Beaty, Magnusa',                         p:['Jak we wrześniu krety kopią po nizinach, będzie wietrzno, ale lekka zima.','Gdy wrzesień mglisty — zima wczesna.'] },
    { d:7,   names:'Reginy, Melchiora',                      p:['Święta Regina mgły rozpina.'] },
    { d:8,   names:'Narodzenia NMP',                         p:['Na Matkę Boską Siewną siej, kiedy czas sprzyja.','Sieje się na Siewną — wschodzi na wiosnę.','Na Siewną — zboże ozime w ziemię.'] },
    { d:9,   names:'Sergiusza, Piotra',                      p:['Gdy grzyby wielkie korzenie mają, wielką zimę zapowiadają.'] },
    { d:10,  names:'Mikołaja, Salomei',                      p:['Wrzesień chodzi po rosie, zbiera grzyby we wrzosie.'] },
    { d:11,  names:'Jacka, Prota',                           p:['Ze wszystkich świętych najlepszy Jacek, bo kto żyje dostał placek.'] },
    { d:12,  names:'Gwidona, Marii',                         p:['Jeśli wrzesień będzie ciepły i suchy, pewno październik nie oszczędzi pluchy.','Gdy wrzesień ciepły w połowie — październik chłodny.'] },
    { d:13,  names:'Jana Złotoustego, Maurycego',            p:['Czym dłużej jaskółki we wrześniu zostają, tym dłużej piękne i jasne dni bywają.'] },
    { d:14,  names:'Podwyższenia Krzyża',                    p:['Na Podwyższenie Świętego Krzyża jesień się przybliża.','Wrzesień z deszczem — październik z mrozem.','Na Podwyższenie — żegnaj lato.'] },
    { d:15,  names:'Marii Bolesnej, Nikodema',               p:['Pogoda na Nikodema — niedziel cztery deszczu nie ma.','Jaki pierwszy wrzesień, taka będzie jesień.'] },
    { d:16,  names:'Korneliusza, Edyty',                     p:['Im głębiej we wrześniu grzebią się robaki, tym srożej się zima da ludziom we znaki.'] },
    { d:17,  names:'Roberta, Hildegardy',                    p:['Jaką pogodę na nowiu da wrzesień, taka bywa zwykle przez całą jesień.'] },
    { d:18,  names:'Stanisławy, Ireny',                      p:['Kiedy Irena z mrozem przybywa, babie lato krótkie bywa.'] },
    { d:19,  names:'Januarego, Konstancji',                  p:['Wrzesień wrzosami strojny, lecz od pracy znojny.'] },
    { d:20,  names:'Eustachiusza, Faustyny',                 p:['Gdy we wrześniu grzybów brak, niezawodny zimy znak.'] },
    { d:21,  names:'Mateusza, Józefata',                     p:['Na świętego Mateusza dostanie kapusta kapelusza.','Na Mateusza — plony policzone.'] },
    { d:22,  names:'Tomasza, Maurycego',                     p:['Wrzesień z więdnącym liściem — zima wróżona.','Jeśli Maurycy ma jasne lice, to przyprowadzi wnet nawałnicę.'] },
    { d:23,  names:'Tekli, Linusa',                          p:['Skoro wrzesień, to już jesień, ale jabłek pełna kieszeń.','Na równonoc jesienną — noc z dniem równy.'] },
    { d:24,  names:'Marii, Gerarda',                         p:['Na Gerarda, gdy sucho, zima będzie z pluchą.'] },
    { d:25,  names:'Władysława, Aurela',                     p:['Wrześniowa słota, miarka deszczu, korzec błota.'] },
    { d:26,  names:'Kosmy i Damiana, Justyny',               p:['Czego lipiec i sierpień nie dowarzy, tego wrzesień nie dosmaży.','We wrześniu, gdy tłuste ptaki, srogo się zima da ludziom we znaki.'] },
    { d:27,  names:'Wincentego de Paul, Floriana',           p:['Wrzesień ku końcowi — jesień rządzi.','Straszna jest wrześniowa słota - miarka deszczu, korzec błota.'] },
    { d:28,  names:'Wacława, Libuszy',                       p:['Na świętego Wacława w polu pustki, w domu sława.'] },
    { d:29,  names:'Michała Archanioła',                     p:['Jeśli bociany do Michała zostały, nie będzie mrozów przez grudzień cały.','Gdy noc jasna na Michała, to nastąpi zima trwała.','Michał archanioł — jesień strzeże.'] },
    { d:30,  names:'Hieronima, Honoriusza',                  p:['Gdy wrzesień z pogodą zaczyna, zwykle przez miesiąc pogoda się trzyma.','Jeśli na świętego Prota jest pogoda albo słota, to na świętego Hieronima deszczyk jest, albo go ni ma.','Koniec września — liście w złocie.'] },
  ],
  10: [
    { d:1,   names:'Teresy, Remigiusza',                     p:['Październik z deszczem — listopad suchy.','Gdy październik mroźny, to nie będzie styczeń groźny.'] },
    { d:2,   names:'Aniołów Stróżów, Teofila',               p:['Gdy jesień zamglona, zima zaśnieżona.','Gdy w październiku ciepło chadza, w lutym mrozy naprowadza.'] },
    { d:3,   names:'Wincentego, Gwidona',                    p:['Październik chodzi po kraju, cichnie ptactwo w gaju.','Gdy październik ciepły — listopad mroźny.'] },
    { d:4,   names:'Franciszka z Asyżu',                     p:['Na Franciszka lecą liście jak płatki.','Gdy październik ciepło trzyma, zwykle mroźna bywa zima.','Gdy październik ze śniegiem przybieży, na wiosnę długo śnieg na polach leży.'] },
    { d:5,   names:'Placyda, Leonarda',                      p:['W październiku, gdy liść z drzewa niesporo opada, późną to wiosnę zapowiada.'] },
    { d:6,   names:'Brunona, Czcibora',                      p:['W październiku kawek gromada, słotne dni nam zapowiada.'] },
    { d:7,   names:'Marii Różańcowej, Justyny',              p:['Październik chodzi po kraju, cichnie ptactwo w gaju.','Kiedy październik śnieżny i chłodny, to styczeń zwykle łagodny.'] },
    { d:8,   names:'Pelagii, Benedykta',                     p:['Ile razy przed nowiem w październiku śnieg spadnie, tyle razy wśród zimy odwilży przypadnie.'] },
    { d:9,   names:'Jana z Capestrano, Elżbiety',            p:['Gdy październik z wodami, grudzień z wiatrami.'] },
    { d:10,  names:'Franciszka, Daniela',                    p:['Październik spoczynku nie chce dać, każe orać, każe siać.'] },
    { d:11,  names:'Emilii, Aleksandra',                     p:['Gdy październik ostro trzyma, zwykle potem ostra zima.'] },
    { d:12,  names:'Maksymiliana, Sławomiry',                p:['Gdy październik mokro trzyma, zwykle potem ostra zima.','Gdy październik pogodny — zima miękka.'] },
    { d:13,  names:'Edwarda, Faustyny',                      p:['Na Edwarda jesień twarda.'] },
    { d:14,  names:'Kaliksta, Benedykta',                    p:['Liść na drzewie mocno trzyma, nie tak prędko przyjdzie zima.'] },
    { d:15,  names:'Teresy z Avila, Jadwigi',                p:['Liść na drzewie mocno trzyma, nie tak prędko przyjdzie zima.','Połowa października — zima za dwa miesiące.'] },
    { d:16,  names:'Jadwigi Śląskiej, Małgorzaty',           p:['Gdy jesień zamglona, zima zaśnieżona.','Kto sieje na świętą Jadwigę, ten zbiera figę.'] },
    { d:17,  names:'Ignacego, Rozalii',                      p:['Październik ciepły, będzie luty skrzepły.'] },
    { d:18,  names:'Łukasza, Juliana',                       p:['Na Łukasza — słońce po jesiennemu.','Na świętego Łukasza jest w domu chleb i kasza.'] },
    { d:19,  names:'Piotra z Alcantary, Jana',               p:['Idzie jesień, a tu pusta kieszeń.'] },
    { d:20,  names:'Ireny, Wencelindy',                      p:['Kiedy w październiku mrozy i zawieje, w styczniu ciepłe słonko pewnie zajaśnieje.'] },
    { d:21,  names:'Urszuli, Celiny',                        p:['Święta Urszula perły rozsuła.'] },
    { d:22,  names:'Korduli, Filipa',                        p:['Październik z burzą — zima wczesna.','Święta Urszula i Kordula dzieci do pieca przytula.'] },
    { d:23,  names:'Jana z Kapistrano, Seweryna',            p:['W jesieni prędko gdy liść z drzewa spadnie, to wkrótce zima będzie, każdy zgadnie.','Gdy październik ciepło trzyma, zwykle mroźna bywa zima.'] },
    { d:24,  names:'Rafała, Antoniego',                      p:['Jaki październik, taki marzec, doznał tego niejeden starzec.'] },
    { d:25,  names:'Darii, Kryspiany',                       p:['Październik, bo paździerze baba z lnu cierlicą bierze.'] },
    { d:26,  names:'Ewarysta, Lucjana',                      p:['Październik ku końcowi — ziemia śpi.','Pierwszy śnieg w październiku, gdy na błoto pada, łagodną zimę zapowiada.'] },
    { d:27,  names:'Sabiny, Wincentego',                     p:['Jesień bezdeszczowa to zima wiatrowa.'] },
    { d:28,  names:'Szymona i Judy',                         p:['Na świętego Szymona i Judy spodziewają się śniegu i grudy.','Gdy Szymon mroźny — grudzień śnieżny.','Szymon i Juda — koniec jesieni wróżą.'] },
    { d:29,  names:'Zenobiusza, Felicji',                    p:['Gdy jesień zamglona, zima zaśnieżona.','Gdy październik ciepły na końcu — listopad mroźny.'] },
    { d:30,  names:'Alfonsa, Edmunda',                       p:['Gdy październik ze śniegiem przybieży, na wiosnę długo śnieg na polach leży.','Miesiąc październy, marca obraz wierny.'] },
    { d:31,  names:'Wolfganga, Urbana',                      p:['Ostatni październik — Wszystkich Świętych za rogiem.','Październik chodzi po kraju, cichnie ptactwo w gaju.','Koniec października — zima coraz bliżej.'] },
  ],
  11: [
    { d:1,   names:'Wszystkich Świętych',                    p:['Na Wszystkich Świętych ziemia skrzepła, to będzie zima ciepła, a jak deszcz, to trzeba będzie za piec wleźć.','Na Wszystkich Świętych od zrębu utnij gałąź dębu – jeśli soku nie ma, tęga będzie zima.','Jeśli śnieg na Wszystkich Świętych zawiedzie, to święty Marcin na białym koniu przyjedzie.'] },
    { d:2,   names:'Zaduszki, Tobiasza',                     p:['Niebo płacze, ludzie płaczą, a ubogich chlebem raczą, rozdając jałmużnę, za duszyczki różne.','Kiedy chmurny dzień Zaduszek — zima srogie niesie mrozki.'] },
    { d:3,   names:'Sylwii, Huberta',                        p:['Kiedy swego czasu goły las nastaje, święty Hubert z lasu cały obiad daje.'] },
    { d:4,   names:'Karola Boromeusza, Witosławy',           p:['Deszcze listopadowe budzą wiatry zimowe.'] },
    { d:5,   names:'Elżbiety, Zachariasza',                  p:['Gdy w listopadzie liść na szczytach drzew się trzyma, to w maju na nowe liście spadnie jeszcze zima.'] },
    { d:6,   names:'Leonarda, Feliksa',                      p:['W listopadzie kapusty pełne kadzie.'] },
    { d:7,   names:'Ernesta, Rufiny',                        p:['Jaka pogoda listopadowa, taka i marcowa.'] },
    { d:8,   names:'Seweryna, Klaudiusza',                   p:['Gdy łagodna jesień trzyma, będzie krótka, ostra zima.'] },
    { d:9,   names:'Teodora, Engelbertu',                    p:['W listopadzie goło w sadzie.'] },
    { d:10,  names:'Leona, Ludomiry',                        p:['Gdy w listopadzie wody się podniosą, to snadź w zimie deszcze roszą.'] },
    { d:11,  names:'Marcina',                                p:['Na świętego Marcina zima się zaczyna.','Gdy gęś na Marcina po lodzie chodzi — zima długo nie odchodzi.','Święty Marcin na białym koniu jedzie — zima za nim.'] },
    { d:12,  names:'Macieja, Niny',                          p:['Po Marcinie zima się zaostrza.','Jaka pogoda w listopadzie służy, taka na marzec się wróży.'] },
    { d:13,  names:'Stanisława Kostki, Dydaka',              p:['Na Stanisława Kostkę ujrzysz śniegu drobnostkę, a na Ofiarowanie przydadzą się sanie.'] },
    { d:14,  names:'Wawrzyńca, Emila',                       p:['Jeśli kret w listopadzie jeszcze późno ryje, na Nowy Rok komar wpadnie w bryję.'] },
    { d:15,  names:'Leopolda, Elżbiety',                     p:['Deszcz w połowie listopada, tęgi mróz w połowie stycznia zapowiada.','Połowa listopada — zima pewna.'] },
    { d:16,  names:'Edmunda, Małgorzaty',                    p:['Grzmot listopada dużo zboża zapowiada.'] },
    { d:17,  names:'Elżbiety Węgierskiej, Grzegorza',        p:['Deszcz w początku listopada, mrozy w stycznia zapowiada.','W połowie listopada deszczy, w połowie stycznia trzeszczy.'] },
    { d:18,  names:'Romana, Ody',                            p:['Gdy listopad z deszczami, grudzień zwykle z wiatrami.'] },
    { d:19,  names:'Elżbiety, Seweryna',                     p:['Na świętą Elżbietę bywa śnieg nad piętę.'] },
    { d:20,  names:'Feliksa, Rafaela',                       p:['W listopadzie mróz, szykuj w marcu wóz.'] },
    { d:21,  names:'Ofiarowania NMP, Janusza',               p:['Deszcze listopadowe budzą wiatry zimowe.','Gdy pogoda w Ofiarowanie, ostra zima nastanie.'] },
    { d:22,  names:'Cecylii, Marka',                         p:['Kiedy na świętą Cecylię grzmi, rolnik o dobry roku śni.'] },
    { d:23,  names:'Klemensa, Felicyty',                     p:['Święty Klemens zimę zaczyna, święty Piotr ją kończy.'] },
    { d:24,  names:'Jana od Krzyża, Flory',                  p:['Słońce listopada mrozy zapowiada.','Kwitną drzewa w listopadzie wszędzie, zima aż do maja będzie.'] },
    { d:25,  names:'Katarzyny Aleksandryjskiej, Piotra',     p:['Na Katarzynę — koła się kręcą.','Gdy listopad z deszczem, grudzień zwykle z wiatrem.'] },
    { d:26,  names:'Sylwestra, Konrada',                     p:['Jaki listopad, taki będzie marzec, prorokuje stuletni starzec.'] },
    { d:27,  names:'Waleriana, Wirgiliusza',                 p:['Gdy zbyt długo złota jesień trzyma, nagle przyjdzie zima.','Gdy w listopadzie liść na szczytach drzew trzyma, to w maju na nowe liście spadnie jeszcze zima.'] },
    { d:28,  names:'Jakuba, Stefana',                        p:['Słońce listopada mrozy zapowiada.'] },
    { d:29,  names:'Saturnina, Błażeja',                     p:['Grzmot listopada dużo zboża zapowiada.','Deszcz w początku listopada, mrozy w styczniu zapowiada.'] },
    { d:30,  names:'Andrzeja',                               p:['Na świętego Andrzeja trza kożucha dobrodzieja.','Święty Andrzej Ci ukaże, co Ci los przyniesie w darze.','Lej wosk na Andrzeja — los odczytaj.'] },
  ],
  12: [
    { d:1,   names:'Eligiusza, Blanki',                      p:['Jaki pierwszy dzień miesiąca, taki będzie aż do końca.','Jak się grudzień zaczyna, taka ma być cała zima.'] },
    { d:2,   names:'Balbiny, Bibiany',                       p:['W pierwszym tygodniu grudnia pogoda stała, będzie zima długa, biała.','Gdy grudzień ciepły — styczeń mroźny.'] },
    { d:3,   names:'Franciszka Ksawerego, Luizy',            p:['Grudzień jak łagodny wszędzie, cała zima dzieckiem będzie.','Suchy grudzień stoi za to, że sucha będzie wiosna i suche lato.'] },
    { d:4,   names:'Barbary',                                p:['Święta Barbara po lodzie, Boże Narodzenie po wodzie.','Gdy Barbara z deszczem — Boże Narodzenie ze śniegiem.','Święta Barbara po lodzie, Boże Narodzenie po wodzie.'] },
    { d:5,   names:'Saby, Kryspiny',                         p:['Piąty grudzień stycznia czyni znaki.','Pogoda grudniowa — wody połowa, lodu połowa.'] },
    { d:6,   names:'Mikołaja',                               p:['Mikołaj mroźny — cały rok śnieżny.','Na Mikołaja dzieci na prezenty czekają.','Gdy Mikołaj z deszczem — Boże Narodzenie bez śniegu.'] },
    { d:7,   names:'Ambrożego, Teodory',                     p:['Święty Ambroży zimy przysporzy.','Na święty Ambroży poprawią się mrozy.'] },
    { d:8,   names:'Niepokalanego Poczęcia NMP',             p:['Mroźny grudzień, wiele śniegu, żyzny roczek będzie w biegu.','Po suchym grudniu sucha wiosna bywa i pogoda we żniwa.'] },
    { d:9,   names:'Leokadii, Wiesławy',                     p:['Grudzień to miesiąc zawiły, czasem srogi, czasem miły.','Silne i częste wiatry w grudniu są wróżbą wielkich deszczów w marcu i kwietniu.'] },
    { d:10,  names:'Julii, Edwarda',                         p:['Gdy ptaki o północy latają, mroźną zimę przepowiadają.','Pogoda grudniowa — wody połowa, lodu połowa.'] },
    { d:11,  names:'Damazego, Biny',                         p:['Suchy grudzień stoi za to, że sucha będzie wiosna i suche lato.','Pogoda grudniowa — lodu połowa, wody połowa.'] },
    { d:12,  names:'Otylii, Aleksandra',                     p:['W zimie odkryte ucho, to w lecie sucho.','Dłużej świat zima ziębi, niż lato zagrzewa.'] },
    { d:13,  names:'Łucji',                                  p:['Łucja dnia przyczyni czy nocy — ciemności nie zmniejszy.','Na świętą Łucję dzień się o krok przybliży.','Po świętej Łucji dzień trwa najkrócej.'] },
    { d:14,  names:'Jana od Krzyża, Izydora',                p:['W pierwszym tygodniu grudnia, gdy pogoda stała, będzie zima długo biała.','Taką pogodę Nowy Rok przynosi, jaka na Jana od Krzyża się głosi.'] },
    { d:15,  names:'Niny, Celiny',                           p:['Jak w zimie piecze, to w lecie ciecze.','Czym w grudniu większy mróz, tym do worka zboże bardziej włóż.'] },
    { d:16,  names:'Albiny, Seweryna',                       p:['Grudzień zimny, śniegiem przykryty, daje rok w zboże obfity.','Gdyby kiedy w grudniu grzmiało, wiatrów byłoby niemało.'] },
    { d:17,  names:'Łazarza, Olimpii',                       p:['W grudniu rzeki kryją lody, a lud cieszy się na Gody.','Grudzień ostro mrozi drogi, wieprze bije, drwa znosi dla zimowej trwogi.'] },
    { d:18,  names:'Bogusławy, Gracjana',                    p:['Mroźny grudzień, wiele śniegu, żyzny roczek będzie w biegu.','Gdy w grudniu śnieg pada, drugi rok taki sam zapowiada.'] },
    { d:19,  names:'Dariusza, Urbana',                       p:['Grudzień z grzmotami, rok z wiatrami.','Pogoda na Urbana, to wielka wygrana.'] },
    { d:20,  names:'Filibertu, Dominiki',                    p:['Gdy ciepło na Dominika, ostra zima nas dotyka.','Na świętego Dominika głucho wszędzie, śpiew ptactwa zanika.'] },
    { d:21,  names:'Tomasza, Honoriusza',                    p:['Na Tomasza — przesilenie zimowe.','Najkrótszy dzień roku — słońce zawraca.','Na Tomasza najdłuższa noc nasza.'] },
    { d:22,  names:'Zenona, Demetriusza',                    p:['Po przesileniu dzień przybywa.','Gdy łagodna jesień trzyma, będzie krótka, ostra zima.'] },
    { d:23,  names:'Jana Kęty, Wiktorii',                    p:['Grudzień jaki, czerwiec taki.','Im więcej zimą wody, tym więcej wiosną pogody.'] },
    { d:24,  names:'Ewy, Adama',                             p:['Wigilia gwiazdkowa — gwiazda na niebie.','Gdy na Wigilię gwiazda wyraźna — rok dobry.','Jakiś we Wiliją, takiś cały rok.'] },
    { d:25,  names:'Narodzenia Pańskiego',                   p:['Boże Narodzenie ze śniegiem — Wielkanoc z kwieciem.','Gdy Boże Narodzenie zielone — Wielkanoc biała.','Na Boże Narodzenie słońce zaświeci — urodzajny rok.'] },
    { d:26,  names:'Szczepana, Dionizego',                   p:['Na Szczepana — zima potrząsa śniegiem.','Na świętego Szczepana bywa błoto po kolana.','Gdy na Szczepana mróz — do wiosny daleko.'] },
    { d:27,  names:'Jana, Fabioli',                          p:['Jak Jan Apostoł ośnieżony, św. Józef już zielony.','Jak Apostoł pokazuje, taki luty następuje.'] },
    { d:28,  names:'Młodzianków, Antoniny',                  p:['Suchy grudzień stoi za to, że sucha wiosna i suche lato.','Niewiniątek dzień pokaże, jaka pogoda w marcu się okaże.'] },
    { d:29,  names:'Tomasza Becketa, Dawida',                p:['Zima starym dokucza, a młodych naucza.','Zima nie pyta, gdzie się lato podziało.'] },
    { d:30,  names:'Dawida, Rogera',                         p:['Kiedy grzmi na lód, będzie głód.','Jeśli w grudniu często dmucha, to w marcu wciąż plucha.'] },
    { d:31,  names:'Sylwestra',                              p:['Jak Sylwester — taki cały rok nowy.','Sylwestrowa noc jasna i gwiaździsta — rok obfity.','Na Sylwestra hałasuj — złe duchy przepędź.'] },
  ],
};
