// Wspólna baza danych świąt i dni obchodzonych (2026) — jedno źródło prawdy
// używane przez swieta.html (pełna lista z filtrami) i index.html (widżet "Najbliższe ważne daty").
// Format: [dzień, miesiąc, nazwa, slug, typ(y) rozdzielone spacją]
const SWIETA_DATA=[
  [1,1,'Nowy Rok','nowy-rok','panstwowe koscielne'],
  [6,1,'Trzech Króli (Objawienie Pańskie)','trzech-kroli','koscielne'],
  [21,1,'Dzień Babci','dzien-babci','nieoficjalne'],
  [22,1,'Dzień Dziadka','dzien-dziadka','nieoficjalne'],
  [27,1,'Międzynarodowy Dzień Pamięci o Ofiarach Holokaustu','dzien-pamieci-holokaustu','miedzynarodowe'],
  [28,1,'Europejski Dzień Ochrony Danych Osobowych','dzien-ochrony-danych','miedzynarodowe'],
  [26,1,'Światowy Dzień Celnictwa','dzien-celnika','branzowe'],
  [2,2,'Dzień Handlowca','dzien-handlowca','branzowe'],
  [2,2,'Matki Bożej Gromnicznej (Dzień Świeczki)','gromniczna','koscielne'],
  [8,2,'Dzień Tradycji Służby Więziennej','dzien-sluzby-wieziennej','branzowe'],
  [21,2,'Międzynarodowy Dzień Przewodnika Turystycznego','dzien-przewodnika-turystycznego','branzowe'],
  [21,2,'Międzynarodowy Dzień Języka Ojczystego','dzien-jezyka-ojczystego','miedzynarodowe'],
  [22,2,'Dzień Ofiar Przestępstw','dzien-ofiar-przestepstw','branzowe'],
  [23,2,'Międzynarodowy Dzień Walki z Depresją','dzien-walki-z-depresja','miedzynarodowe'],
  [12,2,'Tłusty Czwartek','tlusty-czwartek','nieoficjalne'],
  [17,2,'Ostatki (Śledzik)','ostatki','nieoficjalne'],
  [17,2,'Dzień Służby Cywilnej','dzien-sluzby-cywilnej','branzowe'],
  [18,2,'Środa Popielcowa (Popielec)','popielec','koscielne'],
  [14,2,'Walentynki — Dzień Zakochanych','walentynki','nieoficjalne'],
  [19,2,'Narodowy Dzień Nauki Polskiej','dzien-nauki-polskiej','panstwowe'],
  [1,3,'Narodowy Dzień Pamięci „Żołnierzy Wyklętych”','dzien-pamieci-zolnierzy-wykletych','panstwowe'],
  [3,3,'Międzynarodowy Dzień Pisarzy i Pisarek','dzien-pisarzy','branzowe'],
  [8,3,'Międzynarodowy Dzień Kobiet','dzien-kobiet','miedzynarodowe nieoficjalne'],
  [10,3,'Dzień Mężczyzn','dzien-mezczyzn','nieoficjalne'],
  [11,3,'Dzień Sołtysa','dzien-soltysa','branzowe'],
  [15,3,'Światowy Dzień Praw Konsumenta','dzien-praw-konsumenta','miedzynarodowe'],
  [19,3,'Dzień Przedsiębiorcy i Patrona Rzemieślników','dzien-przedsiebiorcy','branzowe'],
  [21,3,'Dzień Wagarowicza / Pierwszy Dzień Wiosny','dzien-wiosny','nieoficjalne'],
  [21,3,'Topienie Marzanny','topienie-marzanny','nieoficjalne'],
  [21,3,'Międzynarodowy Dzień Lasów','dzien-lasow','miedzynarodowe'],
  [22,3,'Światowy Dzień Wody','dzien-wody','miedzynarodowe'],
  [23,3,'Światowy Dzień Meteorologii','dzien-meteorologii','branzowe'],
  [24,3,'Narodowy Dzień Pamięci Polaków ratujących Żydów pod okupacją niemiecką','dzien-pamieci-polakow-ratujacych-zydow','panstwowe'],
  [27,3,'Międzynarodowy Dzień Teatru','dzien-teatru','branzowe'],
  [29,3,'Niedziela Palmowa','niedziela-palmowa','koscielne'],
  [29,3,'Dzień Metalowca','dzien-metalowca','branzowe'],
  [1,4,'Prima Aprilis','prima-aprilis','nieoficjalne'],
  [2,4,'Wielki Czwartek','wielki-czwartek','koscielne'],
  [3,4,'Wielki Piątek','wielki-piatek','koscielne'],
  [4,4,'Wielka Sobota','wielka-sobota','koscielne'],
  [5,4,'Wielka Niedziela — Wielkanoc','wielkanoc','koscielne'],
  [6,4,'Poniedziałek Wielkanocny (Śmigus-Dyngus)','poniedzialek-wielkanocny','koscielne'],
  [7,4,'Światowy Dzień Zdrowia','dzien-zdrowia','miedzynarodowe'],
  [12,4,'Dzień Kosmonautyki','dzien-kosmonautyki','branzowe'],
  [12,4,'Niedziela Miłosierdzia Bożego','milosierdzie-boze','koscielne'],
  [14,4,'Święto Chrztu Polski','swieto-chrztu-polski','panstwowe'],
  [16,4,'Dzień Sapera (Święto Wojsk Inżynieryjnych)','dzien-sapera','branzowe'],
  [22,4,'Dzień Ziemi','dzien-ziemi','miedzynarodowe'],
  [23,4,'Światowy Dzień Książki i Praw Autorskich','dzien-ksiazki','miedzynarodowe'],
  [25,4,'Światowy Dzień Lekarzy Weterynarii','dzien-weterynarii','branzowe'],
  [25,4,'Międzynarodowy Dzień Sekretarki i Asystentki','dzien-sekretarki','branzowe'],
  [26,4,'Dzień Drogowca i Transportowca','dzien-drogowca','branzowe'],
  [27,4,'Światowy Dzień Grafika','dzien-grafika','branzowe'],
  [28,4,'Światowy Dzień Bezpieczeństwa i Ochrony Zdrowia w Pracy','dzien-bhp','branzowe'],
  [1,5,'Święto Pracy','swieto-pracy','panstwowe miedzynarodowe'],
  [2,5,'Dzień Flagi Rzeczypospolitej Polskiej','dzien-flagi','panstwowe'],
  [2,5,'Dzień Polonii i Polaków za Granicą','dzien-polonii','panstwowe'],
  [3,5,'Święto Konstytucji 3 Maja','konstytucja-3-maja','panstwowe'],
  [4,5,'Dzień Strażaka','dzien-strazaka','branzowe'],
  [4,5,'Dzień Hutnika','dzien-hutnika','branzowe'],
  [8,5,'Narodowy Dzień Zwycięstwa','dzien-zwyciestwa','panstwowe'],
  [8,5,'Dzień Bibliotekarza i Bibliotek','dzien-bibliotekarza','branzowe'],
  [8,5,'Krajowy Dzień Położnej','dzien-poloznej','branzowe'],
  [9,5,'Dzień Europy','dzien-europy','miedzynarodowe'],
  [11,5,'Dzień Doradcy Podatkowego','dzien-doradcy-podatkowego','branzowe'],
  [12,5,'Międzynarodowy Dzień Pielęgniarki i Położnej','dzien-pielegniarki','branzowe'],
  [15,5,'Międzynarodowy Dzień Rodzin','dzien-rodzin','miedzynarodowe'],
  [16,5,'Święto Straży Granicznej','swieto-strazy-granicznej','branzowe'],
  [18,5,'Krajowy Dzień Fryzjera i Kosmetyczki','dzien-fryzjera','branzowe'],
  [18,5,'Międzynarodowy Dzień Muzeów','dzien-muzeow','branzowe'],
  [17,5,'Wniebowstąpienie Pańskie','wniebowstapienie','koscielne'],
  [24,5,'Święto Wojsk Specjalnych','dzien-wojsk-specjalnych','branzowe'],
  [24,5,'Zesłanie Ducha Świętego (Zielone Świątki)','zielone-swiatki','koscielne'],
  [25,5,'Dzień Piwowara','dzien-piwowara','branzowe'],
  [26,5,'Dzień Matki','dzien-matki','nieoficjalne'],
  [27,5,'Dzień Samorządu Terytorialnego','dzien-samorzadu-terytorialnego','panstwowe'],
  [27,5,'Ogólnopolski Dzień Diagnosty Laboratoryjnego','dzien-diagnosty-laboratoryjnego','branzowe'],
  [29,5,'Dzień Weterana Działań poza Granicami Państwa','dzien-weterana','panstwowe'],
  [31,5,'Uroczystość Trójcy Przenajświętszej','trojca-swiety','koscielne'],
  [1,6,'Dzień Dziecka','dzien-dziecka','nieoficjalne'],
  [4,6,'Boże Ciało (Uroczystość Najświętszego Ciała i Krwi Chrystusa)','boze-cialo','koscielne'],
  [4,6,'Dzień Drukarza','dzien-drukarza','branzowe'],
  [7,6,'Dzień Chemika','dzien-chemika','branzowe'],
  [8,6,'Światowy Dzień Oceanów','dzien-oceanow','miedzynarodowe'],
  [9,6,'Dzień Księgowego','dzien-ksiegowego','branzowe'],
  [9,6,'Międzynarodowy Dzień Archiwów','dzien-archiwow','branzowe'],
  [13,6,'Święto Żandarmerii Wojskowej','swieto-zandarmerii','branzowe'],
  [14,6,'Światowy Dzień Krwiodawcy','dzien-krwiodawcy','miedzynarodowe'],
  [14,6,'Narodowy Dzień Pamięci Ofiar Niemieckich Nazistowskich Obozów Koncentracyjnych i Obozów Zagłady','dzien-pamieci-ofiar-obozow-koncentracyjnych','panstwowe'],
  [20,6,'Narodowy Dzień Powstań Śląskich','dzien-powstan-slaskich','panstwowe'],
  [21,6,'Międzynarodowy Dzień Jogi','dzien-jogi','miedzynarodowe'],
  [23,6,'Dzień Ojca','dzien-ojca','nieoficjalne'],
  [27,6,'Światowy Dzień Rybołówstwa','dzien-rybolowstwa','branzowe'],
  [29,6,'Dzień Ratownika WOPR','dzien-ratownika-wopr','branzowe'],
  [29,6,'Dzień Rybaka','dzien-rybaka','branzowe'],
  [1,7,'Światowy Dzień Architektury','dzien-architekta','branzowe'],
  [1,7,'Dzień Morza','dzien-morza','nieoficjalne'],
  [6,7,'Dzień Radcy Prawnego','dzien-radcy-prawnego','branzowe'],
  [11,7,'Narodowy Dzień Pamięci o Polakach – Ofiarach Ludobójstwa dokonanego przez OUN i UPA','dzien-pamieci-ofiar-ludobojstwa-wolyn','panstwowe'],
  [12,7,'Dzień Walki i Męczeństwa Wsi Polskiej','dzien-walki-i-meczenstwa-wsi-polskiej','panstwowe'],
  [24,7,'Święto Policji','swieto-policji','branzowe'],
  [1,8,'Narodowy Dzień Pamięci Powstania Warszawskiego','rocznica-powstania-warszawskiego','panstwowe'],
  [7,8,'Dzień Instruktora Nauki Jazdy','dzien-instruktora-nauki-jazdy','branzowe'],
  [10,8,'Dzień Przewodników i Ratowników Górskich','dzien-ratownika-gorskiego','branzowe'],
  [14,8,'Dzień Energetyka','dzien-energetyka','branzowe'],
  [15,8,'Wniebowzięcie NMP','wniebowziecie-nmp','koscielne'],
  [15,8,'Święto Wojska Polskiego','swieto-wojska-polskiego','panstwowe'],
  [19,8,'Światowy Dzień Pomocy Humanitarnej','dzien-pomocy-humanitarnej','miedzynarodowe'],
  [28,8,'Święto Lotnictwa Polskiego','swieto-lotnictwa-polskiego','branzowe'],
  [29,8,'Dzień Strażnika Gminnego i Miejskiego','dzien-straznika-miejskiego','branzowe'],
  [31,8,'Dzień Solidarności i Wolności','dzien-solidarnosci','panstwowe'],
  [1,9,'Rocznica wybuchu II Wojny Światowej (1939)','rocznica-1-wrzesnia','historyczne'],
  [13,9,'Dzień Programisty','dzien-programisty','branzowe'],
  [16,9,'Europejski Dzień Maszynisty Kolejowego','dzien-maszynisty','branzowe'],
  [17,9,'Rocznica agresji ZSRR na Polskę (17 września 1939)','dzien-historii','historyczne'],
  [20,9,'Ogólnopolski Dzień Przedszkolaka','dzien-przedszkolaka','nieoficjalne'],
  [21,9,'Międzynarodowy Dzień Pokoju','dzien-pokoju','miedzynarodowe'],
  [21,9,'Dzień Krajowej Administracji Skarbowej','dzien-kas','branzowe'],
  [25,9,'Dzień Budowlanych','dzien-budowlanych','branzowe'],
  [25,9,'Światowy Dzień Farmaceuty i Ogólnopolski Dzień Aptekarza','dzien-farmaceuty','branzowe'],
  [27,9,'Dzień Polskiego Państwa Podziemnego','dzien-polskiego-panstwa-podziemnego','panstwowe'],
  [30,9,'Dzień Chłopaka','dzien-chlopaka','nieoficjalne'],
  [30,9,'Międzynarodowy Dzień Tłumacza','dzien-tlumacza','branzowe'],
  [30,9,'Dzień Archiwisty','dzien-archiwisty','branzowe'],
  [1,10,'Światowy Dzień Muzyki','dzien-muzyki','miedzynarodowe'],
  [4,10,'Światowy Dzień Zwierząt','dzien-zwierzat','miedzynarodowe'],
  [5,10,'Dzień Spedytora','dzien-spedytora','branzowe'],
  [11,10,'Międzynarodowy Dzień Dziewcząt','dzien-dziewczat','miedzynarodowe'],
  [13,10,'Dzień Ratownictwa Medycznego','dzien-ratownika','branzowe'],
  [14,10,'Dzień Edukacji Narodowej (Dzień Nauczyciela)','dzien-nauczyciela','branzowe'],
  [18,10,'Dzień Łącznościowca','dzien-lacznosciowca','branzowe'],
  [19,10,'Narodowy Dzień Pamięci Duchownych Niezłomnych','dzien-pamieci-duchownych-niezlomnych','panstwowe'],
  [20,10,'Międzynarodowy Dzień Szefa Kuchni','dzien-szefa-kuchni','branzowe'],
  [25,10,'Europejski Dzień Prawnika','europejski-dzien-prawnika','branzowe'],
  [25,10,'Dzień Szewca','dzien-szewca','branzowe'],
  [31,10,'Halloween','halloween','nieoficjalne'],
  [1,11,'Wszystkich Świętych','wszystkich-swietych','koscielne'],
  [2,11,'Dzień Zaduszny (Wspomnienie Wszystkich Wiernych Zmarłych)','dzien-zaduszny','koscielne'],
  [11,11,'Święto Niepodległości','swieto-niepodleglosci','panstwowe'],
  [16,11,'Międzynarodowy Dzień Tolerancji','dzien-tolerancji','miedzynarodowe'],
  [16,11,'Dzień Służby Zagranicznej','dzien-sluzby-zagranicznej','branzowe'],
  [20,11,'Powszechny Dzień Dziecka','powszechny-dzien-dziecka','miedzynarodowe'],
  [21,11,'Dzień Pracownika Socjalnego','dzien-pracownika-socjalnego','branzowe'],
  [25,11,'Międzynarodowy Dzień Eliminacji Przemocy wobec Kobiet','dzien-eliminacji-przemocy','miedzynarodowe'],
  [25,11,'Dzień Kolejarza','dzien-kolejarza','branzowe'],
  [29,11,'Dzień Podchorążego','dzien-podchorazego','branzowe'],
  [30,11,'Andrzejki','andrzejki','nieoficjalne'],
  [4,12,'Barbórka (Dzień Górnika)','barbarka','branzowe'],
  [1,12,'Światowy Dzień AIDS','dzien-aids','miedzynarodowe'],
  [3,12,'Międzynarodowy Dzień Osób z Niepełnosprawnościami','dzien-osob-niepelnosprawnych','miedzynarodowe'],
  [5,12,'Międzynarodowy Dzień Wolontariusza','dzien-wolontariusza','miedzynarodowe'],
  [6,12,'Mikołajki (Dzień Świętego Mikołaja)','mikolajki','nieoficjalne'],
  [10,12,'Międzynarodowy Dzień Praw Człowieka','dzien-praw-czlowieka','miedzynarodowe'],
  [24,12,'Wigilia Bożego Narodzenia','wigilia','koscielne'],
  [25,12,'Boże Narodzenie (pierwszy dzień)','boze-narodzenie','koscielne'],
  [26,12,'Boże Narodzenie (drugi dzień)','boze-narodzenie-2','koscielne'],
  [27,12,'Narodowy Dzień Zwycięskiego Powstania Wielkopolskiego','dzien-zwycieskiego-powstania-wielkopolskiego','panstwowe'],
  [31,12,'Sylwester','sylwester','nieoficjalne']
];
